const STORE={theme:'eml-theme-v5',lang:'eml-lang-v5',done:'eml-grammar-done-v5',days:'eml-study-days-v5',best:'eml-quiz-best-v5',notes:'eml-notes-v5',draft:'eml-output-v5',selected:'eml-selected-v5'};
const pathStages=[
 {level:'A1',name:'Build the sentence',jp:'語順・be/do/have・基本時制・名詞句を自動化する。',tc:'自動化語序、be/do/have、基本時態與名詞片語。',goals:['Simple statements & questions','Core noun phrases','Daily survival output']},
 {level:'A2',name:'Expand everyday English',jp:'完了・未来・助動詞・比較・関係節の基礎へ。',tc:'進入完成式、未來、情態、比較與關係子句。',goals:['More time/aspect choices','Connected sentences','Short conversations']},
 {level:'B1',name:'Connect ideas',jp:'複文・reported speech・語法を使って理由と経験を説明する。',tc:'用複句、轉述與語法解釋理由和經驗。',goals:['Clause control','Narration & explanation','Independent communication']},
 {level:'B2',name:'Precision & flexibility',jp:'自然な語順・collocation・推論・言い換えを強化する。',tc:'加強自然語序、搭配、推論與改述。',goals:['Nuanced grammar','Faster reading/listening','Structured output']},
 {level:'C1',name:'Advanced control',jp:'圧縮構文・談話・register・高度な推量を使い分ける。',tc:'掌握壓縮句構、篇章、語域與高階推測。',goals:['Academic/professional control','Implicit meaning','Fluent reformulation']},
 {level:'C2',name:'Mastery direction',jp:'文法選択を意識せず、精度・自然さ・速度を同時に保つ。',tc:'在高精度、自然度與速度下近乎自動地使用英文。',goals:['Fine nuance','Style & rhetoric','Near-automatic control']}
];
const toeicPlan=[
 ['Part 1','Photographs','短い音声から人物・物・位置・進行中の動作を瞬時に取る。'],['Part 2','Question–Response','疑問詞だけでなく意図と間接応答を取る。'],['Part 3','Conversations','話者関係・目的・次の行動・暗示をchunkで追う。'],['Part 4','Talks','構成を予測しながら要点・詳細・意図を取る。'],['Part 5','Incomplete Sentences','品詞・語法・時制・一致・前置詞を短時間で処理する。'],['Part 6','Text Completion','文法だけでなく文脈・指示・論理の流れを見る。'],['Part 7','Reading Comprehension','single/multiple textsを根拠付きで高速処理する。']
];
const quizBank=[
 {band:'foundation',q:'She ___ to the lab every morning.',a:['go','goes','going','gone'],c:1,jp:'現在形で主語が she なので三単現 goes。',tc:'現在式主詞是 she，因此用 goes。'},
 {band:'foundation',q:'___ you understand this sentence?',a:['Are','Do','Does','Is'],c:1,jp:'一般動詞 understand の疑問文なので Do。',tc:'understand 是一般動詞，疑問句用 Do。'},
 {band:'foundation',q:'There ___ two problems with the current design.',a:['is','are','has','be'],c:1,jp:'複数名詞 two problems に合わせて are。',tc:'two problems 為複數，因此用 are。'},
 {band:'foundation',q:'I need ___ information before I decide.',a:['an','many','some','a'],c:2,jp:'information は不可算名詞なので some information。',tc:'information 不可數，因此用 some。'},
 {band:'foundation',q:'This laptop is ___ than my old one.',a:['more fast','faster','fastest','more faster'],c:1,jp:'fast の比較級は faster。',tc:'fast 的比較級是 faster。'},
 {band:'foundation',q:'I am used to ___ early.',a:['wake up','waking up','woke up','be wake'],c:1,jp:'be used to の to は前置詞なので -ing。',tc:'be used to 的 to 是介系詞，後接 -ing。'},
 {band:'foundation',q:'When I ___ home, I’ll call you.',a:['will get','get','got','getting'],c:1,jp:'未来のwhen節でも通常現在形。',tc:'談未來的 when 子句仍通常用現在式。'},
 {band:'foundation',q:'Could you ___ that again?',a:['said','saying','say','says'],c:2,jp:'助動詞 could の後ろは原形。',tc:'could 後接原形。'},
 {band:'advanced',q:'Rarely ___ such a dramatic improvement.',a:['we see','do we see','we do see','see we'],c:1,jp:'Rarely 前置で否定倒装。',tc:'Rarely 置首觸發倒裝。'},
 {band:'advanced',q:'I ___ on this problem all morning, and I still have not solved it.',a:['worked','have worked','have been working','am worked'],c:2,jp:'継続中の活動を強調する現在完了進行形。',tc:'強調持續至今的活動，用現在完成進行式。'},
 {band:'advanced',q:'She suggested ___ the meeting until Friday.',a:['to postpone','postponing','us to postpone','postpone us'],c:1,jp:'suggest は通常 suggest doing / suggest that ...。',tc:'suggest 通常接 doing 或 that 子句。'},
 {band:'advanced',q:'He denied ___ the confidential file.',a:['to copy','copied','copying','copy'],c:2,jp:'deny は -ing を取る。',tc:'deny 後接 -ing。'},
 {band:'advanced',q:'The data, ___ from three cameras, was synchronized.',a:['collecting','collected','was collected','to collect'],c:1,jp:'受動のreduced relativeなので過去分詞 collected。',tc:'被動縮減關係子句用過去分詞 collected。'},
 {band:'advanced',q:'The first model was accurate; the second was even ___.',a:['accurate','more accurate','most accurate','accurately'],c:1,jp:'even + comparative。',tc:'even 可強化比較級。'},
 {band:'advanced',q:'Do you know where the meeting ___?',a:['is','is it','does it be','it is?'],c:0,jp:'embedded question は平叙文語順。',tc:'嵌入問句使用陳述語序。'},
 {band:'advanced',q:'If I had known earlier, I ___ differently.',a:['would act','would have acted','acted','had acted'],c:1,jp:'過去の反事実なので third conditional。',tc:'過去反事實用 third conditional。'},
 {band:'toeic',q:'All expense reports must be submitted ___ Friday afternoon.',a:['at','by','during','until to'],c:1,jp:'締切は by + 時点。',tc:'截止時間用 by。'},
 {band:'toeic',q:'The manager asked whether the shipment ___ yet.',a:['arrived','has arrive','had arrived','was arrive'],c:2,jp:'過去の asked より前の到着を示す past perfect が自然。',tc:'到貨早於過去的 asked，使用 past perfect。'},
 {band:'toeic',q:'Applicants are advised ___ copies of all supporting documents.',a:['bring','bringing','to bring','brought'],c:2,jp:'advise + O + to-inf / be advised to-inf。',tc:'be advised + to-inf。'},
 {band:'toeic',q:'The new software is compatible ___ most operating systems.',a:['to','for','with','at'],c:2,jp:'compatible with がcollocation。',tc:'固定搭配 compatible with。'},
 {band:'toeic',q:'Because of the unexpected delay, the seminar has been ___ until next month.',a:['put off','put it off','putting off','putted off'],c:0,jp:'受動態 has been + p.p.。put off の過去分詞は put off。',tc:'被動 has been + p.p.；put 的過去分詞仍是 put。'},
 {band:'toeic',q:'The proposal was ___ detailed that the committee approved it immediately.',a:['such','so','too','enough'],c:1,jp:'so + adjective + that。',tc:'so + 形容詞 + that。'},
 {band:'toeic',q:'Neither of the two candidates ___ available on Monday.',a:['are','were','is','have'],c:2,jp:'formal test grammarでは neither of + plural noun を単数扱いすることが多い。',tc:'正式測驗文法常把 neither of + 複數名詞視為單數。'},
 {band:'toeic',q:'The documents ___ yesterday are now available online.',a:['uploading','uploaded','were uploading','upload'],c:1,jp:'documents を後置修飾する過去分詞。',tc:'過去分詞 uploaded 後置修飾 documents。'}
];
const transforms=[
 ['Negative','She works remotely.','She does not work remotely.'],['Question','They have finished the test.','Have they finished the test?'],['Embedded question','Where is the station?','Could you tell me where the station is?'],['Passive','The team developed the model.','The model was developed by the team.'],['Causative','A technician repaired my laptop.','I had my laptop repaired.'],['Reported speech','She said, “I am tired.”','She said that she was tired.'],['Participle clause','After I checked the logs, I restarted the server.','Having checked the logs, I restarted the server.'],['Comparison','Model A is accurate. Model B is more accurate.','Model B is more accurate than Model A.'],['Ellipsis','I can solve it, and she can solve it too.','I can solve it, and she can too.'],['Condition','I did not know, so I did not apply.','If I had known, I would have applied.']
];
const dictationBank=['I have been studying English for three hours.','Could you tell me where the station is?','The results suggest that the method is effective.','If I had known about the deadline, I would have applied.','The documents must be submitted by Friday afternoon.','Rarely do we see such a dramatic improvement.','There seems to be a problem with the connection.','I am used to working in a noisy environment.','Having checked the logs, we restarted the server.'];
let activeQuiz=[],dictationText=dictationBank[0],incompleteOnly=false,selectedLessonId=localStorage.getItem(STORE.selected)||grammarLessons[0]?.id;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}} function save(k,v){localStorage.setItem(k,JSON.stringify(v));}
function applyTheme(){const dark=localStorage.getItem(STORE.theme)==='dark';document.body.classList.toggle('dark',dark);$('#themeToggle').textContent=dark?'Light mode':'Dark mode'}
function applyLang(lang=localStorage.getItem(STORE.lang)||'both'){document.body.classList.remove('lang-jp','lang-tc');if(lang==='jp')document.body.classList.add('lang-jp');if(lang==='tc')document.body.classList.add('lang-tc');$$('.lang-button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem(STORE.lang,lang)}
function getDone(){return load(STORE.done,{})} function isDone(id){return !!getDone()[id]} function toggleDone(id){const d=getDone();d[id]=!d[id];save(STORE.done,d);renderGrammarList();renderReader(id);renderDashboard()}
function domainFor(id){return grammarDomains.find(d=>d.lessonIds.includes(id))||grammarDomains[grammarDomains.length-1]}
function renderDashboard(){const done=getDone(),count=grammarLessons.filter(l=>done[l.id]).length,pct=Math.round(count/grammarLessons.length*100);$('#grammarDone').textContent=`${count}/${grammarLessons.length}`;$('#overallBar').style.width=`${pct}%`;const days=load(STORE.days,[]);$('#studyDays').textContent=days.length;$('#quizBest').textContent=localStorage.getItem(STORE.best)||0;const next=grammarLessons.find(l=>!done[l.id])||grammarLessons[grammarLessons.length-1];$('#nextLessonTitle').textContent=next?next.title.split(' — ')[0]:'All core lessons complete';$('#nextLessonMeta').textContent=next?`${next.level} · ${domainFor(next.id).name}`:'Review and output';$('#continueLearning').dataset.lesson=next?.id||grammarLessons[0].id}
function renderPath(){$('#pathGrid').innerHTML=pathStages.map(x=>`<article class="path-card"><div class="level">${x.level}</div><h3>${esc(x.name)}</h3><p class="jp">${esc(x.jp)}</p><p class="tc">${esc(x.tc)}</p><ul>${x.goals.map(g=>`<li>${esc(g)}</li>`).join('')}</ul></article>`).join('')}
function renderSkills(){$('#skillGrid').innerHTML=masteryTracks.map(x=>`<article class="skill-card"><div class="skill-no">${esc(x.icon)}</div><h3>${esc(x.title)}</h3><p class="jp">${esc(x.jp)}</p><p class="tc">${esc(x.tc)}</p><span class="target">${esc(x.target)}</span></article>`).join('')}
function populateDomains(){const s=$('#grammarDomain');s.innerHTML='<option value="all">All domains</option>'+grammarDomains.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}
function lessonMatches(l){const q=$('#grammarSearch').value.trim().toLowerCase(),level=$('#grammarLevel').value,domain=$('#grammarDomain').value;const text=JSON.stringify(l).toLowerCase();if(q&&!text.includes(q))return false;if(level!=='all'&&!l.level.includes(level))return false;if(domain!=='all'&&!grammarDomains.find(d=>d.id===domain)?.lessonIds.includes(l.id))return false;if(incompleteOnly&&isDone(l.id))return false;return true}
function renderGrammarList(){const rows=grammarLessons.filter(lessonMatches);$('#grammarCount').textContent=`${rows.length} / ${grammarLessons.length}`;$('#lessonTotal').textContent=grammarLessons.length;$('#grammarList').innerHTML=rows.map(l=>{const d=domainFor(l.id);return `<button class="lesson-row ${l.id===selectedLessonId?'active':''}" data-lesson="${l.id}" role="option"><span class="row-top"><span class="level">${esc(l.level)}</span><span class="done">${isDone(l.id)?'✓ Done':''}</span></span><strong>${esc(l.title.split(' — ')[0])}</strong><small>${esc(d.jp)}</small></button>`}).join('')||'<p class="muted" style="padding:14px">No lessons match.</p>'}
function speak(t,rate=1){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=rate;const vs=speechSynthesis.getVoices();u.voice=vs.find(v=>/^en(-|_)/i.test(v.lang))||null;speechSynthesis.speak(u)}
function renderReader(id){const l=grammarLessons.find(x=>x.id===id)||grammarLessons[0];if(!l)return;selectedLessonId=l.id;localStorage.setItem(STORE.selected,l.id);const idx=grammarLessons.indexOf(l),d=domainFor(l.id),c=l.contrasts?.[0]||['Wrong form','Correct form','Check the rule.','確認規則。'];$('#grammarReader').innerHTML=`
 <div class="reader-hero"><div class="reader-meta"><span class="badge">${esc(l.level)}</span><span class="badge">${esc(d.name)}</span><span class="badge">${esc(l.focus)}</span></div><h2>${esc(l.title)}</h2><div class="reader-tc tc">${esc(l.titleTc)}</div><div class="reader-actions"><button class="primary completed-btn ${isDone(l.id)?'done':''}" data-complete="${l.id}" type="button">${isDone(l.id)?'✓ Completed':'Mark lesson complete'}</button><button class="secondary" data-speak="${esc(l.examples?.[0]||'')}" type="button">▶ Example audio</button></div></div>
 <div class="reader-body"><div class="lesson-flow"><span>1 Form</span><span>2 Meaning</span><span>3 Usage</span><span>4 Contrast</span><span>5 Examples</span><span>6 Output</span></div>
 <section class="quick-check"><h4>Before you learn · Quick check</h4><p>Which sentence is the better standard choice?</p><div class="choice-row"><button data-check="wrong" data-explain-jp="${esc(c[2])}" data-explain-tc="${esc(c[3])}">${esc(c[0])}</button><button data-check="correct" data-explain-jp="${esc(c[2])}" data-explain-tc="${esc(c[3])}">${esc(c[1])}</button></div><div class="quick-feedback"></div></section>
 <h3>Form</h3><div class="formulae">${l.formula.map(f=>`<code>${esc(f)}</code>`).join('')}</div>
 <section class="teacher-box"><h3>Teacher explanation</h3><p class="jp">${esc(l.lectureJP)}</p><p class="tc">${esc(l.lectureTC)}</p></section>
 <div class="lesson-grid"><section><h3>How to use it</h3><ul class="jp">${l.usageJP.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><ul class="tc">${l.usageTC.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section><h3>Real examples</h3><div class="example-box">${l.examples.map(x=>`<div class="example-line"><span>${esc(x)}</span><button class="speak" data-speak="${esc(x)}" type="button">▶</button></div>`).join('')}</div></section></div>
 <section><h3>Contrast & common mistakes</h3><div class="contrast-grid">${l.contrasts.map(x=>`<article class="contrast-card"><div class="wrong">× ${esc(x[0])}</div><div class="right">○ ${esc(x[1])}</div><p class="jp">${esc(x[2])}</p><p class="tc">${esc(x[3])}</p></article>`).join('')}</div></section>
 <section class="assignment"><h3>Output assignment</h3><p class="jp">${esc(l.taskJP)}</p><p class="tc">${esc(l.taskTC)}</p></section></div>
 <div class="reader-nav"><button class="secondary" type="button" data-prev="${grammarLessons[idx-1]?.id||''}" ${idx===0?'disabled':''}>← Previous</button><button class="secondary" type="button" data-next="${grammarLessons[idx+1]?.id||''}" ${idx===grammarLessons.length-1?'disabled':''}>Next →</button></div>`;renderGrammarList()}
function renderCoverage(){$('#coverageGrid').innerHTML=grammarDomains.map(d=>`<article class="coverage-card"><div class="coverage-top"><div><h3>${esc(d.name)}</h3><p class="muted">${esc(d.jp)}</p></div><span class="coverage-count">${d.topics.length} topics</span></div><div class="topic-wrap">${d.topics.map(t=>`<span class="topic">${esc(t)}</span>`).join('')}</div><button class="chip" data-domain-jump="${d.id}" type="button">Open lessons →</button></article>`).join('')}
function renderToeic(){$('#toeicGrid').innerHTML=toeicPlan.map(x=>`<article class="toeic-card"><div class="part">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}
function startQuiz(){const mode=$('#quizMode').value,pool=mode==='mixed'?quizBank:quizBank.filter(x=>x.band===mode);activeQuiz=[...pool].sort(()=>Math.random()-.5).slice(0,Math.min(10,pool.length));$('#quizResult').textContent='';$('#quizQuestions').innerHTML=activeQuiz.map((q,i)=>`<article class="question" data-q="${i}"><p>${i+1}. ${esc(q.q)}</p>${q.a.map((a,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}"> ${esc(a)}</label>`).join('')}<div class="feedback hidden"></div></article>`).join('')}
function gradeQuiz(){let score=0;activeQuiz.forEach((q,i)=>{const box=$(`[data-q="${i}"]`),sel=box.querySelector('input:checked'),ok=sel&&Number(sel.value)===q.c;if(ok)score++;const f=box.querySelector('.feedback');f.className=`feedback ${ok?'good':'bad'}`;f.innerHTML=`<strong>${ok?'✓ Correct':'✗ Review'}</strong><p class="jp">${esc(q.jp)}</p><p class="tc">${esc(q.tc)}</p>`});$('#quizResult').textContent=`${score} / ${activeQuiz.length}`;const old=Number(localStorage.getItem(STORE.best)||0),best=Math.max(old,score);localStorage.setItem(STORE.best,best);renderDashboard()}
function renderTransforms(){$('#transformList').innerHTML=transforms.map(x=>`<article class="transform-item"><strong>${esc(x[0])}</strong><p>${esc(x[1])}</p><button class="chip reveal" data-answer="${esc(x[2])}" type="button">Reveal answer</button></article>`).join('')}
function newDictation(){dictationText=dictationBank[Math.floor(Math.random()*dictationBank.length)];$('#dictationInput').value='';$('#dictationFeedback').textContent=''}
function norm(s){return s.toLowerCase().replace(/[.,?!'’]/g,'').replace(/\s+/g,' ').trim()}function checkDictation(){const got=$('#dictationInput').value,ok=norm(got)===norm(dictationText);$('#dictationFeedback').innerHTML=ok?'<strong style="color:var(--good)">✓ Correct</strong>':`<strong>Answer:</strong> ${esc(dictationText)}`}
function initStudy(){const days=load(STORE.days,[]),today=new Date().toLocaleDateString('sv-SE');$('#todayDate').textContent=today;$('#markToday').addEventListener('click',()=>{if(!days.includes(today))days.push(today);save(STORE.days,days);renderDashboard();$('#markToday').textContent='✓ Recorded'});if(days.includes(today))$('#markToday').textContent='✓ Recorded'}
function initNotes(){const n=$('#mistakeNotebook'),d=$('#outputDraft');n.value=localStorage.getItem(STORE.notes)||'';d.value=localStorage.getItem(STORE.draft)||'';n.addEventListener('input',()=>localStorage.setItem(STORE.notes,n.value));d.addEventListener('input',()=>localStorage.setItem(STORE.draft,d.value))}
function setActiveNav(){const sections=$$('.screen');const y=window.scrollY+160;let current='home';sections.forEach(s=>{if(s.offsetTop<=y)current=s.id});$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===current))}
function bind(){
 $('#themeToggle').addEventListener('click',()=>{localStorage.setItem(STORE.theme,document.body.classList.contains('dark')?'light':'dark');applyTheme()});$$('.lang-button').forEach(b=>b.addEventListener('click',()=>applyLang(b.dataset.lang)));
 ['grammarSearch','grammarLevel','grammarDomain'].forEach(id=>$('#'+id).addEventListener(id==='grammarSearch'?'input':'change',renderGrammarList));$('#showIncomplete').addEventListener('click',e=>{incompleteOnly=!incompleteOnly;e.currentTarget.classList.toggle('active',incompleteOnly);renderGrammarList()});
 $('#continueLearning').addEventListener('click',e=>{selectedLessonId=e.currentTarget.dataset.lesson;renderReader(selectedLessonId);$('#grammar').scrollIntoView({behavior:'smooth'})});
 $('#newQuiz').addEventListener('click',startQuiz);$('#gradeQuiz').addEventListener('click',gradeQuiz);$('#dictationPlay').addEventListener('click',()=>speak(dictationText,1));$('#dictationSlow').addEventListener('click',()=>speak(dictationText,.78));$('#dictationNew').addEventListener('click',newDictation);$('#dictationCheck').addEventListener('click',checkDictation);
 $$('.tab').forEach(t=>t.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(`[data-panel="${t.dataset.tab}"]`).classList.add('active')}));
 document.addEventListener('click',e=>{const lr=e.target.closest('[data-lesson]');if(lr){selectedLessonId=lr.dataset.lesson;renderReader(selectedLessonId);return}const sp=e.target.closest('[data-speak]');if(sp){speak(sp.dataset.speak);return}const cp=e.target.closest('[data-complete]');if(cp){toggleDone(cp.dataset.complete);return}const qc=e.target.closest('[data-check]');if(qc){const box=qc.closest('.quick-check'),ok=qc.dataset.check==='correct';box.querySelectorAll('[data-check]').forEach(b=>b.classList.remove('correct','wrong'));qc.classList.add(ok?'correct':'wrong');box.querySelector('.quick-feedback').innerHTML=`<p class="${ok?'right':'wrong'}">${ok?'✓ Correct':'✗ Try the other one'}</p><p class="jp">${esc(qc.dataset.explainJp)}</p><p class="tc">${esc(qc.dataset.explainTc)}</p>`;return}const prev=e.target.closest('[data-prev]');if(prev&&prev.dataset.prev){renderReader(prev.dataset.prev);$('#grammarReader').scrollIntoView({behavior:'smooth',block:'start'});return}const next=e.target.closest('[data-next]');if(next&&next.dataset.next){renderReader(next.dataset.next);$('#grammarReader').scrollIntoView({behavior:'smooth',block:'start'});return}const jump=e.target.closest('[data-domain-jump]');if(jump){$('#grammarDomain').value=jump.dataset.domainJump;renderGrammarList();$('#grammar').scrollIntoView({behavior:'smooth'});return}const rev=e.target.closest('.reveal');if(rev){const old=rev.parentElement.querySelector('.answer-reveal');if(old){old.remove()}else{const a=document.createElement('div');a.className='answer-reveal';a.textContent=rev.dataset.answer;rev.parentElement.appendChild(a)}return}});
 $('#resetProgress').addEventListener('click',()=>{if(!confirm('Reset lesson completion, study days, and quiz best?'))return;[STORE.done,STORE.days,STORE.best].forEach(k=>localStorage.removeItem(k));location.reload()});
 $('#mobileMenu').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));$$('.side-nav a').forEach(a=>a.addEventListener('click',()=>$('.sidebar').classList.remove('open')));window.addEventListener('scroll',setActiveNav,{passive:true});
}
function boot(){applyTheme();applyLang();populateDomains();renderPath();renderSkills();renderCoverage();renderToeic();renderTransforms();renderGrammarList();renderReader(selectedLessonId);startQuiz();newDictation();initStudy();initNotes();renderDashboard();bind();setActiveNav()}
document.addEventListener('DOMContentLoaded',boot);
