const masteryTracks = [
  {
    icon: '01',
    title: 'Grammar & Syntax',
    jp: '文型を覚えるだけでなく、時制・相・法・節・情報構造まで「なぜその形を選ぶか」を説明し、自分で選べる状態を目指す。',
    tc: '不只背句型，而是理解時態、體、語氣、子句與資訊結構，能說明「為什麼選這個形式」並自行運用。',
    target: 'A1 → C2',
  },
  {
    icon: '02',
    title: 'Vocabulary & Collocation',
    jp: '単語の日本語訳ではなく、語族・コロケーション・句動詞・レジスター・類義語の差までセットで覚える。',
    tc: '不只記中文意思，而是一起學詞族、搭配、片語動詞、語域與近義詞差異。',
    target: 'Active + Receptive',
  },
  {
    icon: '03',
    title: 'Pronunciation & Phonology',
    jp: '個々の音だけでなく、強勢、弱形、schwa、連結、脱落、リズム、イントネーションまで扱う。聞き取りと発話を同時に改善する。',
    tc: '不只練單音，也學重音、弱讀、schwa、連音、省音、節奏與語調，同時改善聽力與口說。',
    target: 'Clear & Natural',
  },
  {
    icon: '04',
    title: 'Listening',
    jp: '音を拾う→意味のまとまりで処理する→話者の意図や暗示まで取る、の3段階で鍛える。',
    tc: '依序訓練「辨音 → 以意群處理 → 理解說話者意圖與暗示」三個層次。',
    target: 'Detail + Inference',
  },
  {
    icon: '05',
    title: 'Reading',
    jp: '構文解析だけでなく、指示語、論理関係、段落構造、筆者の態度、推論、速読まで扱う。',
    tc: '除了句構分析，也訓練指涉、邏輯關係、段落結構、作者態度、推論與快速閱讀。',
    target: 'Accuracy + Speed',
  },
  {
    icon: '06',
    title: 'Speaking',
    jp: '正しい1文から始め、説明・比較・理由・反論・要約・即答へ広げる。流暢さと正確さを別々に訓練する。',
    tc: '從正確的一句話開始，擴展到說明、比較、理由、反駁、摘要與即答，分開訓練流暢度與正確度。',
    target: 'Interaction + Fluency',
  },
  {
    icon: '07',
    title: 'Writing',
    jp: '文法的に正しいだけでなく、読みやすい情報順序、段落、接続、語調、要約、メール、技術文書まで練習する。',
    tc: '不只要求文法正確，也練資訊排序、段落、連接、語氣、摘要、郵件與技術寫作。',
    target: 'Sentence → Essay',
  },
  {
    icon: '08',
    title: 'Pragmatics & Register',
    jp: '「文法的には正しいが不自然」を減らす領域。丁寧さ、距離感、含意、直接/間接表現、会話の自然な反応を学ぶ。',
    tc: '減少「文法對但不自然」的英文，學禮貌程度、距離感、言外之意、直接/間接表達與自然回應。',
    target: 'Natural Usage',
  },
];

const grammarLessons = [
  {
    id: 'architecture', level: 'A1-A2',
    title: 'Sentence Architecture — 文の骨格と動詞の支配力',
    titleTc: '句子骨架與動詞的支配力',
    focus: 'S / V / O / C、5文型、verb valency',
    formula: ['SV', 'SVC', 'SVO', 'SVOO', 'SVOC'],
    lectureJP: '英語では語順が文法情報を大量に持ちます。特に動詞は「後ろに何を必要とするか」を決めます。arrive は通常目的語を直接取らず、discuss は about を必要とせず目的語を直接取ります。5文型は暗記表ではなく、動詞が作れる構造を予測するための地図です。',
    lectureTC: '英文的語序承擔大量文法資訊，尤其動詞會決定後面需要什麼。arrive 通常不直接接受詞，而 discuss 可直接接受詞、不需要 about。五大句型不是背誦表，而是預測動詞能形成什麼結構的地圖。',
    usageJP: ['自動詞と他動詞を「日本語訳」ではなく構造で覚える。', 'SVC の C は S を説明し、SVOC の C は O を説明する。', 'give / show / tell のような二重目的語を取れる動詞と、explain のように取れない動詞を区別する。'],
    usageTC: ['用句構而不是翻譯記住不及物/及物動詞。', 'SVC 的 C 說明 S；SVOC 的 C 說明 O。', '區分可接受雙受詞的 give/show/tell 與不能這樣用的 explain。'],
    contrasts: [
      ['I arrived Tokyo.', 'I arrived in Tokyo.', 'arrive は自動詞。場所には通常前置詞が必要。', 'arrive 是不及物動詞，地點通常需要介系詞。'],
      ['We discussed about the issue.', 'We discussed the issue.', 'discuss 自体に「〜について話し合う」が含まれる。', 'discuss 本身已包含「討論某事」的意思。'],
      ['He explained me the problem.', 'He explained the problem to me.', 'explain は SVOO にしない。', 'explain 不能直接形成 SVOO。'],
    ],
    examples: ['The experiment failed.', 'The result seems promising.', 'We tested the model.', 'She gave me useful advice.', 'They found the interface confusing.'],
    taskJP: '自分の研究・学校・日常から、SV / SVC / SVO / SVOO / SVOC を1文ずつ作る。',
    taskTC: '用自己的研究、學校或日常各造一個 SV / SVC / SVO / SVOO / SVOC 句子。',
  },
  {
    id: 'auxiliaries', level: 'A1-B1',
    title: 'be / do / have — 英語文法の3本柱',
    titleTc: '英文文法的三大支柱',
    focus: 'main verb / auxiliary、否定、疑問、進行、完了、受動',
    formula: ['be + C / V-ing / p.p.', 'do + base verb', 'have + p.p.'],
    lectureJP: 'be・do・have は一般動詞としても助動詞としても働きます。重要なのは単語の訳ではなく「文法装置として何を作るか」です。be は状態・進行・受動、do は一般動詞文の否定・疑問・強調、have は完了を作ります。助動詞として使われるとき、その後ろの動詞形までセットで決まります。',
    lectureTC: 'be、do、have 既可以當主要動詞，也能當助動詞。重點不是翻譯，而是它們作為「文法裝置」能形成什麼：be 形成狀態/進行/被動，do 形成一般動詞的否定/疑問/強調，have 形成完成式。',
    usageJP: ['be動詞文に do を追加しない。', 'do/does/did が時制・人称を持つと、本動詞は原形に戻る。', '完了の have と所有の have を構造で見分ける。'],
    usageTC: ['be 動詞句不要再加 do。', 'do/does/did 承擔時態與人稱後，主要動詞回到原形。', '從結構區分完成式 have 與「擁有」的 have。'],
    contrasts: [
      ['Does she is busy?', 'Is she busy?', 'be 自身を主語の前へ移動する。', 'be 自己移到主詞前即可。'],
      ['He does not works here.', 'He does not work here.', 'does に三単現情報があるため work は原形。', 'does 已承擔第三人稱資訊，work 回原形。'],
      ['I have a car.', 'I have finished the task.', '前者は所有、後者は have + p.p. の完了。', '前者是擁有，後者是 have + 過去分詞的完成式。'],
    ],
    examples: ['I am tired.', 'I am working now.', 'The device was repaired.', 'Do you understand?', 'I have already sent the email.'],
    taskJP: 'be / do / have をそれぞれ「一般動詞として1文」「助動詞として1文」作る。',
    taskTC: 'be / do / have 各造一個「主要動詞用法」與「助動詞用法」的句子。',
  },
  {
    id: 'nouns', level: 'A1-B2',
    title: 'Nouns, Articles & Determiners — a / the / 無冠詞を感覚で選ぶ',
    titleTc: '名詞、冠詞與限定詞',
    focus: 'countability、generic/specific、a/an、the、zero article、some/any',
    formula: ['a/an + singular count noun', 'the + identifiable noun', 'Ø + plural/uncountable generic noun'],
    lectureJP: '冠詞は「日本語に訳せない小さい単語」ではなく、話し手が名詞をどう提示しているかを示します。a/an は聞き手がまだ特定できない1つ、the は文脈・常識・後置修飾などによって特定できるもの、無冠詞は複数や不可算名詞を一般概念として述べるときによく使います。まず可算/不可算を判断し、その次に特定性を見ると整理できます。',
    lectureTC: '冠詞不是「無法翻譯的小字」，而是表示說話者如何呈現名詞。a/an 是聽者尚不能特定的一個；the 是能從語境、常識或修飾語辨識的對象；零冠詞常用於把複數或不可數名詞當一般概念談。先判斷可數性，再判斷是否特定。',
    usageJP: ['単数可算名詞は原則として単独で置かない。', 'information / advice / research / equipment は通常不可算。', '初出 a → 次に同じ対象を指す the、という流れを理解する。'],
    usageTC: ['單數可數名詞原則上不能裸用。', 'information / advice / research / equipment 通常不可數。', '理解第一次 a、之後同一對象改用 the 的資訊流。'],
    contrasts: [
      ['I bought computer.', 'I bought a computer.', 'computer は単数可算名詞。', 'computer 是單數可數名詞。'],
      ['an advice', 'some advice / a piece of advice', 'advice は不可算。', 'advice 是不可數名詞。'],
      ['The technology is changing fast.（一般論）', 'Technology is changing fast.', '一般概念なら無冠詞が自然。', '談一般概念時零冠詞較自然。'],
    ],
    examples: ['I saw a robot in the lab. The robot was moving slowly.', 'Information is easy to copy.', 'The information you sent was useful.', 'She gave me some advice.', 'Students need feedback.'],
    taskJP: 'a / the / 無冠詞をそれぞれ2回以上使って、研究室または学校について5文書く。',
    taskTC: '至少各使用兩次 a / the / 零冠詞，寫五句關於研究室或學校的英文。',
  },
  {
    id: 'tense', level: 'A1-B2',
    title: 'Tense — 現在・過去・未来を「時間」だけで選ばない',
    titleTc: '時態：不只看時間，也看說話方式',
    focus: 'present/past、will、be going to、scheduled future、narrative tense',
    formula: ['present: V/Vs', 'past: V-ed/irregular', 'future expressions: will / be going to / present forms'],
    lectureJP: '現在形は「今していること」ではなく、習慣・事実・状態・スケジュールなど、時間の中で安定して見えるものに向きます。過去形は「過去の事実」に加えて、現在から心理的に距離を置く丁寧表現や仮定にもつながります。未来は will だけでなく、意思・予測・予定・手配済みなど意味によって形を選びます。',
    lectureTC: '現在式不等於「現在正在做」，而常表示習慣、事實、狀態、時刻表等相對穩定的內容。過去式除了過去事實，也能延伸到禮貌或假設的心理距離。未來也不是只有 will，而要依意志、預測、計畫、已安排等意義選擇形式。',
    usageJP: ['現在形 = habit/fact/state/schedule。今この瞬間の一時的動作は進行形。', 'will = 即時意思・予測、going to = 事前の意図・根拠のある予測、現在進行形 = 手配済み予定。', '時・条件の副詞節では、未来でも when/if + present を使うのが基本。'],
    usageTC: ['現在式 = 習慣/事實/狀態/時刻表；此刻暫時動作用進行式。', 'will 常表即時意志/預測；going to 表事前意圖或有根據預測；現在進行式可表已安排未來。', '時間/條件副詞子句談未來時，基本仍用 when/if + present。'],
    contrasts: [
      ['I study now.', 'I am studying now.', 'now の一時的動作なら進行形。', '此刻暫時動作用進行式。'],
      ['When I will arrive, I will call you.', 'When I arrive, I will call you.', 'when節は未来でも現在形。', 'when 子句談未來仍用現在式。'],
      ['Look at those clouds. It will rain.', 'Look at those clouds. It is going to rain.', '目の前の根拠がある予測は going to が自然。', '有眼前證據的預測用 going to 更自然。'],
    ],
    examples: ['I work from home twice a week.', 'The train leaves at 8:10 tomorrow.', 'I will answer the email tonight.', 'I am meeting my professor on Friday.', 'When I finish, I will send it.'],
    taskJP: '「明日」について will / be going to / present continuous / present simple を使う4文を作り、なぜその形か説明する。',
    taskTC: '用 will / be going to / present continuous / present simple 各寫一句關於明天的內容，並說明原因。',
  },
  {
    id: 'aspect', level: 'A2-C1',
    title: 'Aspect — 進行形・完了形・完了進行形の「見え方」',
    titleTc: '體：進行、完成、完成進行如何看事件',
    focus: 'simple vs progressive、perfect、perfect progressive、stative verbs',
    formula: ['be + V-ing', 'have + p.p.', 'have been + V-ing'],
    lectureJP: 'aspect は時間そのものより、出来事をどこから眺めるかを決めます。進行形は出来事の内部・途中を切り取り、完了形は基準時より前の出来事を基準時へつなげます。完了進行形はその継続中の活動を強調します。「現在完了 = 過去の一種」と考えると過去形との違いが曖昧になります。',
    lectureTC: 'aspect 比起「何時」，更像是在決定從哪個角度看事件。進行式把視角放在事件進行中；完成式把基準時間之前的事件連接到基準時間；完成進行式則強調持續中的活動。把現在完成只當成一種過去式會看不清與過去式的差別。',
    usageJP: ['過去形は終わった過去の時間に置く。現在完了は現在とのつながりが必要。', 'for/since、already/yet、ever/never は典型的だが、単語だけで時制を機械判断しない。', 'know/believe/own/belong など状態動詞は通常進行形にしにくい。'],
    usageTC: ['過去式放在已結束的過去時間；現在完成需與現在有連結。', 'for/since、already/yet、ever/never 常見，但不要只靠關鍵字機械選時態。', 'know/believe/own/belong 等狀態動詞通常不常用進行式。'],
    contrasts: [
      ['I have seen him yesterday.', 'I saw him yesterday.', 'yesterday は終了した過去時間。', 'yesterday 是已結束的過去時間。'],
      ['I work on this for three hours.', 'I have been working on this for three hours.', '今まで継続中の活動。', '表示持續到現在的活動。'],
      ['I am knowing the answer.', 'I know the answer.', 'know は通常状態動詞。', 'know 通常是狀態動詞。'],
    ],
    examples: ['I have lived in Japan for four years.', 'I lived in Shanghai before I came to Japan.', 'I have been working on the robot all morning.', 'The battery has died, so the robot cannot move.', 'She was sleeping when I called.'],
    taskJP: '同じ動詞を使い、past simple / present perfect / present perfect continuous の3文を作って意味の違いを説明する。',
    taskTC: '用同一動詞各造 past simple / present perfect / present perfect continuous，並說明差異。',
  },
  {
    id: 'modality', level: 'A2-C1',
    title: 'Modality — can / may / must / should / will / would の距離感',
    titleTc: '情態：可能、義務、推測與心理距離',
    focus: 'ability、permission、obligation、deduction、politeness、modal perfect',
    formula: ['modal + base verb', 'modal + have + p.p.'],
    lectureJP: '助動詞は日本語訳を1対1で覚えるより、「話し手が事実にどれだけ確信しているか」「相手へどれだけ強く要求しているか」という stance（立場）で理解します。must は強い義務だけでなく強い推量、would/could は過去だけでなく距離を作って丁寧さ・仮定を表します。',
    lectureTC: '與其把情態動詞一對一翻譯，不如用 stance 理解：說話者對事實有多確定、對對方要求有多強。must 不只表示義務，也可表示強推論；would/could 不只表示過去，也能拉開心理距離，形成禮貌或假設。',
    usageJP: ['modal の後ろは原形。時制や人称で -s を付けない。', 'must not = 禁止、do not have to = 不必要。意味は逆。', '過去推量: must/might/could/can’t + have + p.p.。'],
    usageTC: ['情態動詞後接原形，不因人稱加 -s。', 'must not = 禁止；do not have to = 不必，兩者不同。', '過去推測：must/might/could/can’t + have + p.p.。'],
    contrasts: [
      ['He can speaks English.', 'He can speak English.', 'modal の後ろは原形。', '情態動詞後接原形。'],
      ['You must not come tomorrow.', 'You do not have to come tomorrow.', '前者は禁止、後者は来る必要がない。', '前者禁止，後者是不必來。'],
      ['He must went home.', 'He must have gone home.', '過去への強い推量は must have p.p.。', '對過去的強推論用 must have p.p.。'],
    ],
    examples: ['You should check the logs first.', 'The cable might be loose.', 'He must be tired.', 'Could you send me the file?', 'The error may have been caused by a timeout.'],
    taskJP: '同じ依頼を Can / Could / Would で3段階に言い換え、推量文も must / might / can’t で3文作る。',
    taskTC: '把同一請求用 Can / Could / Would 三種距離改寫，再用 must / might / can’t 各造一個推測句。',
  },
  {
    id: 'nonfinite', level: 'A2-C1',
    title: 'Infinitives, Gerunds & Participles — to / -ing / p.p. を意味で選ぶ',
    titleTc: '不定詞、動名詞與分詞',
    focus: 'to-infinitive、gerund、participles、verb patterns、reduced clauses',
    formula: ['to + base', 'V-ing', 'p.p.'],
    lectureJP: 'to不定詞と動名詞は「未来 vs 過去」とだけ覚えると破綻します。実際には動詞ごとの補文パターンと意味のまとまりを学ぶ必要があります。remember to do / remember doing、stop to do / stop doing のように、形が変わると意味も変わる組み合わせが重要です。分詞は動詞由来ですが、形容詞・副詞的に情報を圧縮できます。',
    lectureTC: '只把 to 不定詞和動名詞背成「未來 vs 過去」會失效，實際上要學每個動詞可接的補語形式與意義。remember to do / remember doing、stop to do / stop doing 等形式一變意思也變。分詞雖來自動詞，卻能像形容詞/副詞一樣壓縮資訊。',
    usageJP: ['want/decide/plan は to、enjoy/avoid/finish は -ing を取る代表例。', '意味が変わる動詞: remember, forget, regret, stop, try。', '現在分詞は能動/進行的、過去分詞は受動/完了的な性質を持ちやすい。'],
    usageTC: ['want/decide/plan 常接 to；enjoy/avoid/finish 常接 -ing。', '形式不同意思也變的動詞：remember, forget, regret, stop, try。', '現在分詞常帶主動/進行感；過去分詞常帶被動/完成感。'],
    contrasts: [
      ['I stopped to smoke.', 'I stopped smoking.', '前者は「タバコを吸うため立ち止まった」、後者は「喫煙をやめた」。', '前者是停下來去抽菸，後者是戒掉抽菸。'],
      ['Remember to lock the door.', 'I remember locking the door.', 'これからすること vs した記憶。', '記得去做 vs 記得做過。'],
      ['I am boring.', 'I am bored.', 'boring = 人を退屈させる性質、bored = 自分が退屈を感じる状態。', 'boring 是令人無聊；bored 是自己感到無聊。'],
    ],
    examples: ['I decided to apply.', 'I avoid checking my phone while studying.', 'Try restarting the service.', 'The data collected yesterday looks clean.', 'Students working on the project meet every Friday.'],
    taskJP: 'remember / stop / try のうち2つを選び、to と -ing で意味が変わる対比例を作る。',
    taskTC: '從 remember / stop / try 選兩個，各造一組 to 與 -ing 意義不同的對比例句。',
  },
  {
    id: 'passive', level: 'A2-C1',
    title: 'Passive & Causative — 「誰がしたか」より情報の焦点を制御する',
    titleTc: '被動與使役：控制資訊焦點',
    focus: 'be/get passive、causative have/get、agent omission',
    formula: ['be + p.p.', 'get + p.p.', 'have/get + O + p.p.'],
    lectureJP: '受動態は能動態の機械的な書き換えではありません。話題として何を先頭に置きたいか、行為者が不明・自明・重要でないかによって選びます。技術文書・ニュース・研究では、プロセスや対象を主題にしたい場面が多いため頻出します。get passive は出来事性や口語的な響きが強くなることがあります。',
    lectureTC: '被動態不是把主動句機械改寫。它用來控制資訊焦點：想把什麼放在主題位置、施事者是否未知/明顯/不重要。技術文、新聞、研究常需把流程或對象放在主位，因此被動頻繁。get passive 往往更口語、事件感更強。',
    usageJP: ['by + agent は必要なときだけ書く。', '自動詞は原則として受動態にできない。', 'have/get something done は「自分でなく誰かにしてもらう/何かがされる経験」。'],
    usageTC: ['by + 施事者只有必要時才寫。', '不及物動詞原則上不能被動化。', 'have/get something done 表示請別人做或經歷某事被處理。'],
    contrasts: [
      ['The team developed the model.', 'The model was developed by the team.', 'どちらが既知情報/話題かで選ぶ。', '依哪個是已知資訊/話題來選。'],
      ['I repaired my phone.', 'I had my phone repaired.', '後者は通常、他者に修理してもらった。', '後者通常表示請別人修手機。'],
      ['He was happened to...', 'It happened to him...', 'happen は自動詞なので通常受動不可。', 'happen 是不及物動詞，通常不能被動。'],
    ],
    examples: ['The samples were collected in July.', 'No personal data is stored on the server.', 'My bike got stolen.', 'I had my laptop repaired.', 'The result can be reproduced.'],
    taskJP: '自分の研究説明を能動態3文で書き、そのうち2文を「情報の焦点」を考えて受動態へ変える。',
    taskTC: '先用三個主動句介紹自己的研究，再考慮資訊焦點，把其中兩句改成被動。',
  },
  {
    id: 'questions', level: 'A1-C1',
    title: 'Questions, Negation & Inversion — 英語の「前に出るもの」を理解する',
    titleTc: '疑問、否定與倒裝',
    focus: 'subject-aux inversion、WH questions、embedded questions、negative inversion',
    formula: ['WH + AUX + S + V?', 'embedded: WH + S + V', 'Never + AUX + S + V'],
    lectureJP: '英語の疑問文は「主語と動詞を逆にする」と覚えるより、最初の助動詞を主語の前へ出すと理解すると一貫します。助動詞がない一般動詞文では do を補います。一方、間接疑問では語順を平叙文に戻します。C1以降では否定語を前置した倒装も重要です。',
    lectureTC: '與其背「主詞和動詞顛倒」，更一致的理解是：把第一個助動詞移到主詞前。一般動詞句沒有助動詞時補 do。間接問句則恢復陳述語序。C1 之後還要掌握否定詞前置造成的倒裝。',
    usageJP: ['主語を問う Who called you? では do を使わない。', 'Do you know where he is? の embedded question は where is he にならない。', 'Never / Rarely / Not only などが文頭に来ると倒装が起きる。'],
    usageTC: ['問主詞的 Who called you? 不使用 do。', 'Do you know where he is? 的間接問句不能變成 where is he。', 'Never / Rarely / Not only 等置於句首時會觸發倒裝。'],
    contrasts: [
      ['Do you know where is he?', 'Do you know where he is?', '埋め込み疑問では通常語順。', '間接問句使用一般陳述語序。'],
      ['Who did call you?', 'Who called you?', 'who 自体が主語なら do-support 不要。', 'who 本身是主詞時不需要 do-support。'],
      ['Never I have seen...', 'Never have I seen...', '否定表現を文頭に置く強調では倒装。', '否定表達置首強調時需倒裝。'],
    ],
    examples: ['Why did you choose this method?', 'Who designed this part?', 'Could you tell me where the station is?', 'Rarely do we see such a large difference.', 'Not only did it fail, but it also corrupted the data.'],
    taskJP: '直接疑問→間接疑問を3組作る。余裕があれば Never / Rarely を使う倒装文も1文。',
    taskTC: '造三組直接問句→間接問句；有餘力再用 Never / Rarely 造一個倒裝句。',
  },
  {
    id: 'relative', level: 'A2-C1',
    title: 'Relative Clauses — 情報を後ろから正確に追加する',
    titleTc: '關係子句：從後方精確補充資訊',
    focus: 'restrictive/non-restrictive、who/which/that/whose、reduced relatives',
    formula: ['N + who/which/that + clause', 'N, who/which + clause,'],
    lectureJP: '関係詞節では「どの名詞を限定しているか」と「その情報が識別に必要か」を考えます。制限用法はどの人/物かを絞り、非制限用法はすでに特定された名詞へ追加情報を添えます。コンマの有無は単なる句読点ではなく意味を変えます。上級では分詞による reduced relative も頻繁です。',
    lectureTC: '關係子句要先判斷修飾哪個名詞，以及資訊是否用來辨識該名詞。限制用法縮小範圍；非限制用法對已確定的名詞追加資訊。逗號不是裝飾，而會改變意思。高階英文也常用分詞縮減關係子句。',
    usageJP: ['that は非制限用法では通常使わない。', '目的格関係代名詞は省略できる場合がある。', 'whose は人だけでなく物にも使える。'],
    usageTC: ['that 通常不用於非限制關係子句。', '作受詞的關係代名詞有時可省略。', 'whose 不只修飾人，也能修飾物。'],
    contrasts: [
      ['My brother who lives in Osaka is an engineer.', 'My brother, who lives in Osaka, is an engineer.', '前者は複数の兄弟から限定する含意、後者は既知の兄弟へ追加情報。', '前者暗示需從多個兄弟中辨識；後者只是補充已知兄弟的資訊。'],
      ['The book which I bought...', 'The book I bought...', '目的格なら which/that を省略可能。', '作受詞時 which/that 可省略。'],
      ['students who are working on...', 'students working on...', '関係節を分詞で圧縮できる。', '可用分詞縮減關係子句。'],
    ],
    examples: ['The engineer who designed this system works in Tokyo.', 'My laptop, which I bought last year, is already slow.', 'The method we used was simple.', 'A company whose products I admire contacted me.', 'Data collected from three cameras was synchronized.'],
    taskJP: '制限用法2文、非制限用法1文、関係代名詞省略1文を作る。',
    taskTC: '造兩個限制用法、一個非限制用法、一個省略關係代名詞的句子。',
  },
  {
    id: 'conditionals', level: 'B1-C1',
    title: 'Conditionals & Subjunctive — 現実性と距離を操作する',
    titleTc: '條件句與假設語氣：控制現實距離',
    focus: 'zero/first/second/third/mixed conditionals、wish、subjunctive',
    formula: ['If + present, present/will', 'If + past, would + V', 'If + had p.p., would have p.p.'],
    lectureJP: '条件文は0/1/2/3型を番号で暗記するより、「話し手が条件をどれくらい現実的に見ているか」と「どの時間について話しているか」で理解すると応用できます。過去形が必ず過去時間を意味するわけではなく、仮定法では現実からの距離を表します。',
    lectureTC: '與其死背 0/1/2/3 型，更有效的是看「說話者認為條件有多現實」以及「談哪個時間」。過去式不一定代表過去時間；在假設語氣中，它也用來表示與現實的距離。',
    usageJP: ['一般事実: If + present, present。現実的未来: If + present, will。', '非現実/低可能性: If + past, would + V。過去の反事実: If + had p.p., would have p.p.。', 'I wish I knew / I wish I had known で現在・過去の反事実を区別。'],
    usageTC: ['一般事實：If + present, present；現實未來：If + present, will。', '不現實/低可能：If + past, would + V；過去反事實：If + had p.p., would have p.p.。', 'I wish I knew / I wish I had known 分別表示現在與過去的反事實。'],
    contrasts: [
      ['If I will have time, I will go.', 'If I have time, I will go.', '現実的未来条件のif節は通常現在形。', '現實未來條件的 if 子句通常用現在式。'],
      ['If I was you...', 'If I were you...', 'formal/standardな仮定では were が伝統的。', '正式/標準假設語氣傳統上用 were。'],
      ['If I knew yesterday...', 'If I had known yesterday...', '過去の反事実は past perfect。', '過去反事實用過去完成式。'],
    ],
    examples: ['If you heat ice, it melts.', 'If I have time, I will go.', 'If I had more time, I would study French.', 'If I had known, I would have applied.', 'I wish I had started earlier.'],
    taskJP: '0/1/2/3 conditionalを1文ずつ、自分の現実に関係する内容で作る。',
    taskTC: '用自己的情況各造一個 zero/first/second/third conditional。',
  },
  {
    id: 'prepositions', level: 'A1-C1',
    title: 'Prepositions — 訳語暗記から「空間・関係のイメージ」へ',
    titleTc: '介系詞：從翻譯背誦轉向關係概念',
    focus: 'in/on/at、to/for、by/until、of/from、verb/adjective + preposition',
    formula: ['preposition + noun/V-ing', 'verb/adjective + fixed preposition'],
    lectureJP: '前置詞は日本語の「に・で・へ」へ一対一変換できません。at は点、on は接触/面、in は内部という空間イメージから時間・抽象関係へ拡張します。一方、depend on / interested in のような語法は意味イメージだけでは予測しきれないので、collocationとしてチャンクで覚えます。',
    lectureTC: '介系詞不能和中文/日文助詞一對一對應。at 可想成點、on 是接觸/表面、in 是內部，再延伸到時間與抽象關係。但 depend on / interested in 這類搭配不能只靠空間意象推測，需作為 collocation 記住。',
    usageJP: ['前置詞の後ろに動詞を置くなら -ing: interested in learning。', 'by Friday = 金曜までに完了、until Friday = 金曜まで継続。', 'arrive in/at、discuss Ø、enter Ø など動詞ごとの項構造も同時に覚える。'],
    usageTC: ['介系詞後接動詞時使用 -ing：interested in learning。', 'by Friday = 週五前完成；until Friday = 持續到週五。', 'arrive in/at、discuss Ø、enter Ø 等需與動詞結構一起記。'],
    contrasts: [
      ['I am interested to AI.', 'I am interested in AI.', 'interested in が固定的な組み合わせ。', '固定搭配是 interested in。'],
      ['Submit it until Friday.', 'Submit it by Friday.', '締切までに完了 = by。', '截止前完成用 by。'],
      ['We entered into the room.', 'We entered the room.', 'enter は通常他動詞。', 'enter 通常直接接受詞。'],
    ],
    examples: ['I arrived in Japan in 2022.', 'The meeting starts at 10.', 'The file is on the desktop.', 'It depends on the dataset.', 'Please finish it by Friday.'],
    taskJP: 'in/on/at、to/for、by/until の対比例を自分で作り、動詞＋前置詞collocationを5個追加する。',
    taskTC: '自己造 in/on/at、to/for、by/until 的對比例，再新增五個動詞＋介系詞搭配。',
  },
  {
    id: 'agreement', level: 'A2-C1',
    title: 'Agreement, Pronouns & Reference — 長い文でも主語を見失わない',
    titleTc: '一致、代名詞與指涉',
    focus: 'subject-verb agreement、pronoun reference、each/every、collective nouns',
    formula: ['head noun → verb agreement', 'pronoun → clear antecedent'],
    lectureJP: '主語と動詞の一致は、近くにある名詞ではなく「主語名詞句の中心語(head)」で決まります。The number of students is... と A number of students are... の違いはTOEICでも重要です。また代名詞 it/they/this が何を指すか曖昧だと、文法的に正しくても読みにくい文章になります。',
    lectureTC: '主詞動詞一致不是看離動詞最近的名詞，而是看主詞名詞片語的中心詞。The number of students is... 與 A number of students are... 的差異在 TOEIC 也很重要。代名詞 it/they/this 若指涉不清，即使文法正確也會難讀。',
    usageJP: ['each/every/everyone は意味が複数でも文法上単数。', 'the number of + plural noun は singular、a number of + plural noun は plural。', 'this が文全体を指す場合、何を指すか曖昧なら名詞を補う: this result / this problem。'],
    usageTC: ['each/every/everyone 意義上涉及多人，但文法上通常單數。', 'the number of + 複數名詞用單數動詞；a number of + 複數名詞用複數動詞。', 'this 指整件事時若不清楚，補名詞：this result / this problem。'],
    contrasts: [
      ['The number of errors are increasing.', 'The number of errors is increasing.', 'head は number。', '中心詞是 number。'],
      ['Each students have...', 'Each student has...', 'each + singular noun + singular verb。', 'each + 單數名詞 + 單數動詞。'],
      ['The robot hit the box and it broke.', 'The robot hit the box, and the box broke.', 'it が robot/box どちらか曖昧。', 'it 可能指 robot 或 box，需消除歧義。'],
    ],
    examples: ['Each student has a different task.', 'The number of applicants has increased.', 'A number of applicants are waiting.', 'The data is useful. / The data are useful. (style-dependent)', 'This result suggests that the model is overfitting.'],
    taskJP: '長い主語を3つ作って動詞を一致させる。代名詞が曖昧な文を2つ作り、明確に修正する。',
    taskTC: '造三個長主詞並正確做動詞一致，再造兩個代名詞指涉不清的句子並修正。',
  },
  {
    id: 'information', level: 'B2-C2',
    title: 'Information Structure — 強調・語順・given/new information',
    titleTc: '資訊結構：已知/新資訊與強調',
    focus: 'cleft sentences、fronting、end-focus、passive as information management',
    formula: ['It is X that...', 'What ... is X', 'fronted element + clause'],
    lectureJP: '上級英語では「文法的に正しい語順」だけでなく、どの情報を先に置き、どこを強調するかが重要です。英語は既知情報から新情報へ進む傾向があり、重い/新しい情報を文末へ置く end-focus が読みやすさに影響します。受動態やcleft構文も情報構造を制御する道具です。',
    lectureTC: '高階英文不只要求語序正確，也要控制先給什麼資訊、強調什麼。英文常從已知資訊走向新資訊，較重或新的內容常放句尾形成 end-focus。被動態與 cleft 句也是控制資訊結構的工具。',
    usageJP: ['It was yesterday that... で特定要素を対比的に強調。', 'What I need is more time. で節全体を主題化。', '長い主語を避け、it構文や受動で情報を自然に配置する。'],
    usageTC: ['It was yesterday that... 可對比強調特定成分。', 'What I need is more time. 把整個子句主題化。', '避免過長主詞，可用 it 結構或被動讓資訊配置自然。'],
    contrasts: [
      ['To understand this complicated mechanism is difficult.', 'It is difficult to understand this complicated mechanism.', 'heavy subject を後ろに置く。', '把較重的主詞移到後面。'],
      ['I need more time.', 'What I need is more time.', '後者は「必要なのは何か」を強調。', '後者強調「我需要的是什麼」。'],
      ['The researchers collected the data.（dataが話題）', 'The data was collected by the researchers.', '話題がdataなら受動が自然なことがある。', '若 data 是話題，被動更自然。'],
    ],
    examples: ['It was the calibration step that caused the error.', 'What matters most is consistency.', 'At the center of the system is a small camera.', 'The final decision will be announced tomorrow.', 'It is unclear whether the difference is significant.'],
    taskJP: '普通文3文を、cleft / what-cleft / passive / extraposition のいずれかで情報焦点を変えて書き直す。',
    taskTC: '把三個普通句用 cleft / what-cleft / passive / extraposition 改寫，改變資訊焦點。',
  },
  {
    id: 'discourse', level: 'B2-C2',
    title: 'Cohesion & Discourse — 文と文をつなぎ、論理を読ませる',
    titleTc: '篇章連貫：讓句子形成可讀的邏輯',
    focus: 'reference、substitution、ellipsis、linking adverbials、theme progression',
    formula: ['claim → reason → evidence → implication'],
    lectureJP: '自然な長文は文法的に正しい文を並べただけでは作れません。this/these/such などの指示、同義語への置換、省略、however/therefore/meanwhile のようなlinking adverbialを使って、読者が「今どの話をしているか」を追えるようにします。ただし接続語を入れすぎると機械的になります。',
    lectureTC: '自然長文不是把正確句子排在一起就完成。需用 this/these/such 等指涉、同義替換、省略，以及 however/therefore/meanwhile 等連接副詞，讓讀者能追蹤話題。但連接詞過多也會顯得機械。',
    usageJP: ['this + noun で前文全体を要約: This result / This problem。', 'however は but と文法的位置が違う。文中punctuationにも注意。', '各文の主題が急に飛ばないよう、旧情報→新情報をつなぐ。'],
    usageTC: ['用 this + 名詞總結前文：This result / This problem。', 'however 與 but 的句法位置不同，也要注意標點。', '避免每句主題突然跳躍，讓已知資訊連到新資訊。'],
    contrasts: [
      ['It failed. However we tried again.', 'It failed. However, we tried again.', 'sentence adverbial の後ろにcomma。', '句首連接副詞後通常加逗號。'],
      ['Because it was expensive. We stopped.', 'Because it was expensive, we stopped.', '従属節だけをfragmentにしない。', '不要把從屬子句單獨變成 fragment。'],
      ['The model failed. This was bad.', 'The model failed. This failure exposed a weakness in the data pipeline.', '指示語に名詞を足すと論理が明確。', '在指示詞後加名詞可讓邏輯更明確。'],
    ],
    examples: ['The model performed well on familiar data. However, its accuracy dropped on new scenes.', 'This result suggests that the training set is too narrow.', 'The first experiment measured speed; the second focused on accuracy.', 'Although the method is simple, it is robust.', 'Therefore, we decided to collect more data.'],
    taskJP: '自分の研究について5文の段落を書き、however / therefore / in contrast のうち2つだけを必要な場所に使う。',
    taskTC: '用五句寫一段自己的研究介紹，只在真正需要的地方使用 however / therefore / in contrast 中的兩個。',
  },
  {
    id: 'register', level: 'B2-C2',
    title: 'Register & Naturalness — 正しい英語から「場面に合う英語」へ',
    titleTc: '語域與自然度：從正確走向合適',
    focus: 'formal/informal、directness、hedging、stance、business/academic/conversation',
    formula: ['direct ↔ hedged', 'casual ↔ neutral ↔ formal'],
    lectureJP: '文法的に正しくても、場面に対して強すぎたり硬すぎたりすると不自然です。Could you...?、Would it be possible to...?、I was wondering if... は同じ依頼でも距離感が違います。研究・ビジネスでは may / appears to / suggests that のような hedging を使い、断定の強さを証拠に合わせます。',
    lectureTC: '文法正確也可能因為太直接或太正式而不自然。Could you...?、Would it be possible to...?、I was wondering if... 表示不同距離感。研究與商務英文常用 may / appears to / suggests that 等 hedging，讓斷言強度符合證據。',
    usageJP: ['命令形は効率的だが、人への依頼では関係性を考える。', 'academic writing では絶対表現 always/proves を必要以上に使わない。', '口語では短縮形・句動詞、正式文では名詞化や中立語彙が増える傾向。'],
    usageTC: ['命令句有效率，但對人請求時要考慮關係。', '學術寫作避免無證據地大量使用 always/proves 等絕對表達。', '口語較常用縮寫與片語動詞；正式文較常用名詞化與中性詞彙。'],
    contrasts: [
      ['Send me the file.', 'Could you send me the file?', '上下関係や緊急性がなければ後者が安全。', '若無上下關係或緊急性，後者較安全。'],
      ['This proves that our method is best.', 'These results suggest that the method is effective.', '証拠以上に断定しない。', '不要超出證據強度下結論。'],
      ['I wanna check it.', 'I would like to check it.', '場面による語域差。', '依場合選擇口語或正式語域。'],
    ],
    examples: ['Could you take a look when you have a chance?', 'Would it be possible to move the meeting?', 'The results appear to support our hypothesis.', 'I may be wrong, but I think the issue is here.', 'Thanks — that makes sense.'],
    taskJP: '「確認してください」「それは違うと思います」を casual / neutral / formal の3段階で言い換える。',
    taskTC: '把「請確認」「我覺得那不對」各改寫成 casual / neutral / formal 三種語域。',
  },
  {
    id: 'precision', level: 'C1-C2',
    title: 'C1/C2 Precision Grammar — 省略・同格・名詞化・複雑な修飾',
    titleTc: 'C1/C2 精密文法',
    focus: 'ellipsis、apposition、nominalization、complex noun phrases、parallelism',
    formula: ['N + appositive', 'nominalized clause', 'parallel A, B, and C'],
    lectureJP: 'C1/C2で差が出るのは、珍しい文法を知っているかより、複雑な内容を誤解なく圧縮できるかです。同格、名詞化、分詞、前置詞句を使うと情報密度を上げられますが、詰め込みすぎると可読性が落ちます。また and/or で並べる要素は文法形を揃える parallelism が重要です。',
    lectureTC: 'C1/C2 的差距不在於知道多少罕見文法，而在於能否把複雜內容壓縮且不產生歧義。同格、名詞化、分詞與介系詞片語能提高資訊密度，但過度堆疊會降低可讀性。and/or 並列時也要保持 parallelism。',
    usageJP: ['名詞化は文体を引き締めるが、動作主を隠しすぎない。', '長い名詞句は「中心名詞」を必ず把握する。', 'parallel structure は読みやすさだけでなく文法問題でも重要。'],
    usageTC: ['名詞化能提高正式度，但不要過度隱藏動作者。', '長名詞片語一定先找中心名詞。', '平行結構不只影響可讀性，也是常見文法判斷點。'],
    contrasts: [
      ['The system is easy to use, reliable, and it saves energy.', 'The system is easy to use, reliable, and energy-efficient.', '並列形式を揃える。', '讓並列項目的文法形式一致。'],
      ['We analyzed the data and this resulted in...', 'Our analysis of the data resulted in...', '名詞化で情報を圧縮できる。', '可用名詞化壓縮資訊。'],
      ['The fact that..., which...', 'The fact that... / This fact...', '修飾の連鎖で先行詞を曖昧にしない。', '避免修飾鏈造成先行詞不清。'],
    ],
    examples: ['Our analysis of the collected data revealed two major issues.', 'The prototype, a low-cost dual-arm robot, was built in-house.', 'The system is designed to collect, transform, and replay motion data.', 'Given the limited sample size, the result should be interpreted cautiously.', 'The main challenge is the reliable estimation of both arms under occlusion.'],
    taskJP: '自分の研究紹介を80語書き、同格1回・名詞化1回・parallel structure 1回を意図的に使う。',
    taskTC: '用約 80 字介紹自己的研究，刻意使用一次同格、一次名詞化、一次平行結構。',
  },
];

const toeicParts = [
  { part: 'Part 1', name: 'Photographs', jp: '位置・動作・状態を瞬時に言語化する。進行形と受動、前置詞、似た音の distractor に強くなる。', tc: '瞬間把位置、動作、狀態語言化；熟悉進行/被動、介系詞與近音干擾。' },
  { part: 'Part 2', name: 'Question–Response', jp: 'WH語だけで反応せず、意図・時制・間接応答を取る。「Yes/Noで返さない自然な応答」が鍵。', tc: '不要只靠 WH 詞，需抓意圖、時態與間接回答；自然回應不一定是 Yes/No。' },
  { part: 'Part 3', name: 'Conversations', jp: '話者関係・目的・次の行動・暗示を追う。設問先読みと、会話の転換語を使って情報を保持する。', tc: '追蹤人物關係、目的、下一步與暗示；利用先讀題目與轉折詞保留資訊。' },
  { part: 'Part 4', name: 'Talks', jp: 'アナウンス・留守電・説明・広告などの構造を型で捉える。冒頭で場面、途中で詳細、終盤で次の行動を取る。', tc: '掌握公告、語音、說明、廣告等結構；開頭抓場景，中段抓細節，結尾抓下一步。' },
  { part: 'Part 5', name: 'Incomplete Sentences', jp: '品詞→文型→動詞形→語法/コロケーション→意味の順に診断し、1問を長く悩まない。', tc: '依詞性→句構→動詞形式→語法/搭配→語意診斷，不要在單題停太久。' },
  { part: 'Part 6', name: 'Text Completion', jp: '単文文法だけでなく、代名詞・時制の流れ・接続・文挿入による段落整合性を見る。', tc: '不只看單句文法，也看代名詞、時態連貫、連接與插句後的段落一致性。' },
  { part: 'Part 7', name: 'Reading Comprehension', jp: '設問根拠を本文に戻して確認する。言い換え・推論・複数文書の情報統合を高速で行う。', tc: '回正文確認證據，高速處理改述、推論與多篇文件資訊整合。' },
];

const c2Habits = [
  ['Precision', '「通じる」で終わらず、なぜその冠詞・時制・前置詞・語順なのか説明できる。', '不只求能溝通，而能解釋為何選該冠詞、時態、介系詞與語序。'],
  ['Paraphrase', '同じ意味を口語・中立・正式の3通りで言い換えられる。', '同一意思能用口語、中性、正式三種方式改述。'],
  ['Inference', '書かれていない意図・態度・前提を文脈から推論する。', '從語境推論未明說的意圖、態度與前提。'],
  ['Automaticity', '基礎文法を考えず処理し、注意を内容・論理・相手へ回せる。', '基礎文法自動化，把注意力留給內容、邏輯與對方。'],
  ['Self-correction', '自分の発話・作文の不自然さを検出し、より自然な形へ修正する。', '能察覺自己口說/寫作的不自然並自行修正。'],
];

const additionalGrammarLessons = [
  {
    "id": "pronouns-possessives",
    "level": "A1-B1",
    "title": "Pronouns & Possession — 代名詞と所有を「形の一覧」ではなく役割で使う",
    "titleTc": "代名詞與所有：按句中角色選擇形式",
    "focus": "subject/object pronouns, possessives, reflexives, one/ones",
    "formula": ["I → me → my → mine", "myself / yourself / themselves", "one / ones"],
    "lectureJP": "代名詞は「同じ名詞を繰り返さないための単語」だけではありません。主格・目的格・所有格は文の中で担う役割によって形が変わります。また英語では、所有者が明らかな身体部位でも my hand のように所有を明示することが多く、再帰代名詞は主語と目的語が同一人物のときや強調に使います。one/ones は可算名詞の繰り返しを避ける重要な代用表現です。",
    "lectureTC": "代名詞不只是避免重複名詞。主格、受格、所有形式會依句中角色改變。英文也常明確標示身體部位的所有者，如 my hand。反身代名詞用於主詞與受詞相同，或用來強調；one/ones 可代替前面已知的可數名詞。",
    "usageJP": ["主語位置は I/he/she/we/they、目的語位置は me/him/her/us/them。", "my + 名詞 と mine のような所有代名詞を区別する。", "by myself は「一人で」、myself 単独の強調は「自分自身で」。"],
    "usageTC": ["主詞位置用 I/he/she/we/they，受詞位置用 me/him/her/us/them。", "區分 my + 名詞 與 mine 這類所有代名詞。", "by myself 表示「獨自」，myself 作強調表示「我本人」。"],
    "contrasts": [["Me and him went there.", "He and I went there.", "標準的な文では主語位置に主格を使う。", "標準英文中主詞位置使用主格。"], ["This is my.", "This is mine.", "名詞を伴わない所有代名詞は mine。", "不接名詞時使用所有代名詞 mine。"], ["I did it by me.", "I did it by myself.", "「一人で」は by + reflexive。", "「獨自完成」用 by + 反身代名詞。"]],
    "examples": ["She sent me the file.", "That laptop is mine.", "I built it myself.", "We introduced ourselves.", "I prefer the smaller one."],
    "taskJP": "自分・友人・所有物について、主格・目的格・所有代名詞・再帰代名詞を各1回使って5文作る。",
    "taskTC": "用自己的生活造五句，分別至少使用一次主格、受格、所有代名詞與反身代名詞。"
  },
  {
    "id": "quantifiers",
    "level": "A1-B2",
    "title": "Quantifiers — some / any / much / many / few / little を可算性と意味で選ぶ",
    "titleTc": "數量詞：依可數性與語意選擇",
    "focus": "some/any, much/many, few/little, each/every, both/either/neither",
    "formula": ["many/few + plural count", "much/little + uncountable", "each/every + singular noun"],
    "lectureJP": "数量詞は「多い・少ない」の訳だけで選ぶと間違えます。まず名詞が可算か不可算かを判断し、その上で量の大きさ、話し手の評価、肯定・否定・疑問という文脈を見ます。few と a few、little と a little は冠詞 a の有無で「ほとんどない」対「少しはある」という評価が変わります。",
    "lectureTC": "數量詞不能只看「多、少」的翻譯。先判斷名詞可數或不可數，再看數量、說話者評價以及肯定/否定/疑問語境。few 與 a few、little 與 a little 只差一個 a，但語意從「幾乎沒有」變成「至少有一些」。",
    "usageJP": ["many/few は複数可算、much/little は不可算。", "some は肯定文だけでなく、申し出・依頼など肯定的な返答を期待する疑問文でも使える。", "each は個々を、every は集合全体を一つずつ見る感覚。"],
    "usageTC": ["many/few 接複數可數；much/little 接不可數。", "some 也可用在期待肯定答覆的提議或請求問句。", "each 強調個別；every 從整體看每一個成員。"],
    "contrasts": [["I have much friends.", "I have many friends.", "friends は複数可算。", "friends 是複數可數名詞。"], ["I have few time.", "I have little time.", "time はこの意味では不可算。", "time 在此為不可數。"], ["Few people came.", "A few people came.", "前者は「ほとんど来なかった」、後者は「数人は来た」。", "前者偏負面「幾乎沒人來」，後者表示「至少有幾個人來」。"]],
    "examples": ["Do you have any questions?", "Would you like some coffee?", "We have very little time.", "Each student received feedback.", "Neither option is ideal."],
    "taskJP": "information / students / time / ideas を使い、some/any/many/much/few/little/each/every のうち6つを使って文を作る。",
    "taskTC": "使用 information / students / time / ideas，並從 some/any/many/much/few/little/each/every 中選六個造句。"
  },
  {
    "id": "there-it",
    "level": "A1-B2",
    "title": "There / It Constructions — 「存在」と「情報の置き方」を分ける",
    "titleTc": "There / It 結構：區分存在與資訊配置",
    "focus": "there is/are, existential there, dummy it, extraposition",
    "formula": ["There + be + NP", "It + be + adjective + to/that...", "It + seems/appears + that..."],
    "lectureJP": "There is/are の there は場所を表す副詞ではなく、文の後半へ新しい情報を導入するための形式主語的要素です。一方 It is important to ... の it は長い主語を後ろへ送るための仮主語です。日本語では主語を省略しやすいため、この2つの「英語が文頭を埋める仕組み」は特に重要です。",
    "lectureTC": "There is/are 的 there 並不是表示地點的副詞，而是把新資訊引入句尾的形式成分。It is important to ... 的 it 則是把較長的真正主語移到後面的虛主詞。中文與日文常可省主詞，因此這兩種英文句首配置特別重要。",
    "usageJP": ["新しい人・物の存在を導入するとき there + be が自然。", "天気・時間・距離は It is raining / It is late / It is far の it。", "長い to不定詞やthat節を後ろへ置く extraposition で読みやすくする。"],
    "usageTC": ["介紹新的人或物存在時常用 there + be。", "天氣、時間、距離常用 it：It is raining / late / far。", "把長的不定詞或 that 子句後置可提高可讀性。"],
    "contrasts": [["It is a problem in the code.", "There is a problem in the code.", "「問題が存在する」なら there is。", "表示「存在一個問題」使用 there is。"], ["To reproduce the bug is difficult.", "It is difficult to reproduce the bug.", "後者の方が自然な情報配置。", "後者更符合自然資訊配置。"], ["There is raining.", "It is raining.", "天候の形式主語は it。", "天氣的虛主詞使用 it。"]],
    "examples": ["There are two possible explanations.", "There seems to be a connection.", "It is important to verify the result.", "It appears that the server is down.", "There used to be a café here."],
    "taskJP": "存在thereを3文、仮主語itを3文、自分の研究・学校・生活の内容で作る。",
    "taskTC": "各造三個存在 there 與三個虛主詞 it 的句子，內容用自己的研究、學校或生活。"
  },
  {
    "id": "adjectives-adverbs",
    "level": "A1-B2",
    "title": "Adjectives & Adverbs — 何を修飾しているかで形と位置を決める",
    "titleTc": "形容詞與副詞：依修飾對象決定形式與位置",
    "focus": "adjective/adverb, -ed/-ing adjectives, adverb position, adjective order",
    "formula": ["adjective → noun/C", "adverb → verb/adjective/adverb/clause", "be + adjective"],
    "lectureJP": "形容詞は名詞や主語・目的語の性質を説明し、副詞は動詞・形容詞・別の副詞・文全体を修飾します。英語では語順によって何を修飾しているかが変わるため、単に -ly を付ける問題ではありません。特に hard/hardly、late/lately のように形が似ても意味が変わる語、boring/bored のような分詞形容詞は重点項目です。",
    "lectureTC": "形容詞描述名詞或主/受詞的性質；副詞可修飾動詞、形容詞、副詞或整句。英文的修飾關係很依賴位置，因此不只是加 -ly。hard/hardly、late/lately 等形式相近但意義不同，以及 boring/bored 這類分詞形容詞都很重要。",
    "usageJP": ["linking verb (be, seem, become, feel) の後ろは形容詞が基本。", "頻度副詞は一般動詞の前、be動詞の後が基本。", "-ing adjective は原因側、-ed adjective は感情を受ける側を表しやすい。"],
    "usageTC": ["be/seem/become/feel 等連綴動詞後通常接形容詞。", "頻率副詞通常在一般動詞前、be 動詞後。", "-ing 形容詞多描述造成感受的一方，-ed 多描述感受到的人。"],
    "contrasts": [["She looks beautifully.", "She looks beautiful.", "look が linking verb なら補語は形容詞。", "look 作連綴動詞時補語用形容詞。"], ["I am boring.", "I am bored.", "自分が退屈しているなら bored。", "自己感到無聊用 bored。"], ["He works hardly.", "He works hard.", "hardly は「ほとんど〜ない」。", "hardly 是「幾乎不」；努力工作用 hard。"]],
    "examples": ["The result is surprisingly good.", "She explained it clearly.", "I am genuinely interested in robotics.", "He is usually on time.", "It was an extremely difficult problem."],
    "taskJP": "形容詞補語、副詞で動詞修飾、頻度副詞、-ed/-ing形容詞を含む文を各1文作る。",
    "taskTC": "各造一句：形容詞補語、副詞修飾動詞、頻率副詞、-ed/-ing 形容詞。"
  },
  {
    "id": "comparison-degree",
    "level": "A1-C1",
    "title": "Comparison & Degree — 比較級だけでなく「程度」を精密に表す",
    "titleTc": "比較與程度：精確表達差距大小",
    "focus": "comparative/superlative, as...as, modifiers, so/such, too/enough",
    "formula": ["-er/more ... than", "as + adj/adv + as", "much/far/slightly + comparative"],
    "lectureJP": "比較は bigger than の形だけでなく、差の大きさ、同程度、上限・不足、極端さを表す体系です。much/far/a lot は比較級を強め、slightly/a little は差を小さくします。too は「必要以上で問題」、enough は「必要量に達する」という評価を含みます。so/such は後ろに来る品詞構造が異なります。",
    "lectureTC": "比較不只是 bigger than，也是一套表達差距大小、同等程度、過度或不足的系統。much/far/a lot 強化比較級，slightly/a little 表示小幅差異。too 含有「過度而成問題」，enough 表示「達到所需程度」。so 與 such 後面的結構也不同。",
    "usageJP": ["much/far/even + comparative、slightly/a bit + comparative。", "as ... as / not as ... as で同程度・差を表す。", "too + adjective + to、adjective + enough + to の語順を区別。"],
    "usageTC": ["much/far/even 可加強比較級；slightly/a bit 表示小差距。", "as ... as / not as ... as 表示同等或較低程度。", "區分 too + adjective + to 與 adjective + enough + to 的語序。"],
    "contrasts": [["more easier", "much easier", "二重比較は不可。強めるなら much。", "不能雙重比較；加強程度用 much。"], ["so difficult problem", "such a difficult problem", "so + adjective、such + (a) + adjective + noun。", "so 接形容詞；such 接名詞片語。"], ["enough fast", "fast enough", "enough が形容詞/副詞を修飾すると後置。", "enough 修飾形容詞/副詞時放後面。"]],
    "examples": ["This version is far more stable.", "The two methods are almost as accurate.", "The dataset is too small to draw a conclusion.", "The model is fast enough for real-time use.", "It was such a useful explanation that I saved it."],
    "taskJP": "比較級を強める文、as...as、too、enough、so/such をそれぞれ1文作る。",
    "taskTC": "各造一句：加強比較級、as...as、too、enough、so/such。"
  },
  {
    "id": "future-forms",
    "level": "A2-B2",
    "title": "Future Forms — will だけではない「未来の見方」",
    "titleTc": "未來表達：不只 will，而是說話者如何看未來",
    "focus": "will, be going to, present continuous, present simple, future continuous/perfect",
    "formula": ["will + V", "be going to + V", "be V-ing (arrangement)", "will be V-ing / will have p.p."],
    "lectureJP": "英語には単一の「未来時制」があるというより、未来についての予測・意思・事前計画・確定した予定を異なる形で表します。will はその場の意思や予測、be going to は事前意図や現在の根拠がある予測、現在進行形は具体的な手配済み予定に向きます。上級では future continuous/perfect で未来の途中・締切までの完了を表します。",
    "lectureTC": "英文與其說只有一個「未來時態」，不如說用不同形式表達預測、臨時決定、既有計畫與已安排的行程。will 常表當下決定或預測；be going to 表預先意圖或有目前證據的預測；現在進行式常表已安排的未來。高階再用 future continuous/perfect 表未來進行中或期限前完成。",
    "usageJP": ["その場の決定 I’ll answer it.、事前計画 I’m going to apply.。", "手配済み I’m meeting her tomorrow.。", "時・条件節では未来でも when/if + present を使う。"],
    "usageTC": ["臨時決定 I’ll answer it；預先計畫 I’m going to apply。", "已安排的行程可用現在進行式。", "時間/條件子句談未來時仍常用現在式：when/if + present。"],
    "contrasts": [["I will meeting him tomorrow.", "I am meeting him tomorrow.", "手配済み予定は現在進行形が自然。", "已安排的行程用現在進行式自然。"], ["When I will arrive, I will call you.", "When I arrive, I will call you.", "when節は未来でも通常現在形。", "when 子句談未來通常仍用現在式。"], ["Look at those clouds. It will rain.", "Look at those clouds. It is going to rain.", "現在の証拠に基づく予測は going to が自然。", "有眼前證據的預測用 going to 更自然。"]],
    "examples": ["I’ll take care of it.", "I’m going to update my portfolio this weekend.", "We’re meeting at two tomorrow.", "This time tomorrow, I’ll be flying to Taipei.", "By Friday, I’ll have finished the report."],
    "taskJP": "同じ「明日の予定」を will / going to / present continuous で3通り書き、意味の違いも一言説明する。",
    "taskTC": "把同一個「明天的事情」分別用 will / going to / present continuous 寫三句，並說明語感差異。"
  },
  {
    "id": "habitual-forms",
    "level": "A2-B2",
    "title": "Habits & Familiarity — used to / would / be used to / get used to",
    "titleTc": "過去習慣與習慣適應：used to 系列",
    "focus": "used to, would, be used to, get used to, past simple",
    "formula": ["used to + V", "would + V (repeated past action)", "be/get used to + noun/V-ing"],
    "lectureJP": "used to は「過去にはそうだったが今は違う」という対比を含み、過去の状態にも反復行動にも使えます。would は過去の反復行動には使えますが、状態には通常使いません。be used to は「〜に慣れている」で to は前置詞なので名詞または -ing、get used to は慣れる過程です。",
    "lectureTC": "used to 含有「以前如此、現在不同」的對比，可描述過去狀態或反覆行為。would 可描述過去反覆行為，但通常不用於狀態。be used to 表「習慣於」，其中 to 是介系詞，後接名詞或 -ing；get used to 表逐漸適應。",
    "usageJP": ["used to + 原形。否定・疑問は didn’t use to / Did ... use to? が一般的。", "would は文脈上「過去」が明確な反復動作で使う。", "be used to の to は不定詞ではないので V-ing。"],
    "usageTC": ["used to + 原形；否定/疑問常用 didn’t use to / Did ... use to?。", "would 用於上下文已明確是過去的反覆動作。", "be used to 的 to 是介系詞，因此後面動詞用 -ing。"],
    "contrasts": [["I am used to wake up early.", "I am used to waking up early.", "be used to の to は前置詞。", "be used to 的 to 是介系詞。"], ["I would live in Shanghai.（過去の状態）", "I used to live in Shanghai.", "過去の状態は used to が自然。", "過去狀態用 used to 較自然。"], ["I use to work there.", "I used to work there.", "肯定文は used to。", "肯定句用 used to。"]],
    "examples": ["I used to take the train every day.", "When I was a child, we would visit my grandparents every summer.", "I’m used to working late.", "It took me months to get used to the commute.", "I didn’t use to drink coffee."],
    "taskJP": "過去の状態、過去の反復行動、現在慣れていること、慣れつつあることを1文ずつ作る。",
    "taskTC": "各造一句：過去狀態、過去反覆行為、現在已習慣的事、正在適應的事。"
  },
  {
    "id": "modal-perfects",
    "level": "B1-C1",
    "title": "Modal Perfects — must have / might have / should have で過去を推量・評価する",
    "titleTc": "情態完成式：推測與評價過去事件",
    "focus": "must/might/could/can’t/should + have p.p.",
    "formula": ["modal + have + p.p.", "must have = strong deduction", "should have = criticism/regret"],
    "lectureJP": "modal + have + 過去分詞は「過去の事実そのもの」ではなく、話し手がその過去をどう判断しているかを表します。must have は強い推量、might/could have は可能性、can’t have は強い否定推量、should have は「そうするのが望ましかったのに」という後悔・批判になります。",
    "lectureTC": "modal + have + 過去分詞不是單純敘述過去事實，而是表達說話者如何判斷那個過去。must have 表強烈推論；might/could have 表可能；can’t have 表強烈否定推論；should have 常表示本來應該做卻沒做的後悔或批評。",
    "usageJP": ["must have p.p. は過去の確信度の高い推量で、過去の義務ではない。", "could have p.p. は「可能だったが実現しなかった」意味にもなる。", "should have / shouldn’t have は事後評価。"],
    "usageTC": ["must have p.p. 表對過去的強推論，不是過去義務。", "could have p.p. 也可表示「本來有可能但沒有發生」。", "should have / shouldn’t have 是事後評價。"],
    "contrasts": [["He must went home.", "He must have gone home.", "過去推量は modal + have + p.p.。", "過去推測用 modal + have + 過去分詞。"], ["You should finished it.", "You should have finished it.", "過去への批判・後悔は should have p.p.。", "對過去的批評/後悔用 should have p.p.。"], ["He must have to leave yesterday.", "He had to leave yesterday.", "過去の義務なら had to。", "過去義務用 had to。"]],
    "examples": ["She must have forgotten the meeting.", "The file might have been deleted accidentally.", "You should have backed up the data.", "He can’t have finished already.", "We could have chosen a simpler approach."],
    "taskJP": "昨日の出来事について must have / might have / can’t have / should have / could have を各1回使って推測・評価する。",
    "taskTC": "針對昨天的事情，各用一次 must have / might have / can’t have / should have / could have 做推測或評價。"
  },
  {
    "id": "multiword-verbs",
    "level": "A2-C1",
    "title": "Phrasal & Multi-word Verbs — 「動詞＋粒子」を一つの語彙文法として覚える",
    "titleTc": "片語動詞與多詞動詞：把動詞＋小品詞當一個單位",
    "focus": "phrasal verbs, prepositional verbs, separability, pronoun placement",
    "formula": ["V + particle", "V + preposition", "V + particle + preposition"],
    "lectureJP": "look up, look after, put off のような表現は単語ごとに直訳せず、一つの意味単位として学ぶ必要があります。さらに、目的語を間に入れられるか、代名詞ならどこに置くかという文法も重要です。look up the word / look the word up は可能でも、look it up のように代名詞は通常間に置きます。",
    "lectureTC": "look up、look after、put off 等不能逐字直譯，而要作為一個意義單位學習。同時要掌握是否可分離，以及代名詞受詞的位置。例如 look up the word / look the word up 都可，但代名詞通常必須放中間：look it up。",
    "usageJP": ["separable phrasal verb では名詞目的語は前後両方可能な場合がある。", "代名詞目的語は put it off / turn it down のように中間へ。", "look after のような prepositional verb は分離しない。"],
    "usageTC": ["可分離片語動詞的名詞受詞有時可放中間或後面。", "代名詞受詞通常放中間：put it off / turn it down。", "look after 這類介系詞動詞不可分離。"],
    "contrasts": [["look up it", "look it up", "代名詞は粒子の前。", "代名詞放在小品詞前。"], ["look the child after", "look after the child", "look after は分離不可。", "look after 不可分離。"], ["discuss about the issue", "discuss the issue", "discuss は prepositional verb ではない。", "discuss 本身直接接受詞。"]],
    "examples": ["Please fill out this form.", "I’ll look it up.", "We had to put the meeting off.", "She looks after the equipment.", "The system ran out of memory."],
    "taskJP": "自分がよく使いそうなphrasal verbを5つ選び、目的語の位置も意識して例文を作る。",
    "taskTC": "選五個自己常用的片語動詞，並注意受詞位置各造句。"
  },
  {
    "id": "complementation",
    "level": "B1-C2",
    "title": "Verb Complementation — 動詞の後ろに何を置けるかを体系化する",
    "titleTc": "動詞補語模式：系統掌握動詞後可接什麼",
    "focus": "V + to-inf, V + -ing, V + object + to-inf, that-clause, bare infinitive",
    "formula": ["V + to V", "V + V-ing", "V + O + to V", "V + that-clause"],
    "lectureJP": "英語では「動詞の意味」を知っていても、その後ろに取れる構造を知らないと文を作れません。suggest は suggest doing / suggest that ...、want は want to do / want O to do、make は make O do のように補文パターンが異なります。上級語彙ほど「語法＝文法」として覚える必要があります。",
    "lectureTC": "即使知道動詞意思，不知道它後面能接什麼結構，仍無法正確造句。suggest 可接 doing 或 that 子句；want 可接 to do 或 O to do；make 則是 make O do。程度越高，越需要把「語法＝文法」一起記。",
    "usageJP": ["動詞を覚えるとき「意味＋後続パターン＋例文」で覚える。", "make/let/help の bare infinitive と want/allow/ask の to-infinitive を区別。", "recommend/suggest/consider など、母語干渉で誤りやすい動詞を重点化。"],
    "usageTC": ["記動詞時一起記「意思＋後續模式＋例句」。", "區分 make/let/help 的原形與 want/allow/ask 的 to-infinitive。", "特別注意 recommend/suggest/consider 等易受母語干擾的動詞。"],
    "contrasts": [["I suggested him to go.", "I suggested that he go / I suggested going.", "suggest は通常 O + to-inf を取らない。", "suggest 通常不接 O + to-inf。"], ["She made me to wait.", "She made me wait.", "active make + O + bare infinitive。", "主動 make + O + 原形。"], ["They allowed us enter.", "They allowed us to enter.", "allow + O + to-infinitive。", "allow + O + to-infinitive。"]],
    "examples": ["I decided to apply.", "They considered changing the design.", "I want you to check this.", "The teacher made us rewrite it.", "The evidence suggests that the method works."],
    "taskJP": "decide / avoid / want / make / suggest / allow を使い、異なる補文パターンの例文を6文作る。",
    "taskTC": "使用 decide / avoid / want / make / suggest / allow，分別造六個不同補語模式的句子。"
  },
  {
    "id": "noun-clauses",
    "level": "A2-C1",
    "title": "Noun & Content Clauses — that / whether / WH節を「名詞の位置」に入れる",
    "titleTc": "名詞子句與內容子句：把完整命題放進名詞位置",
    "focus": "that-clauses, whether/if clauses, WH clauses, extraposition",
    "formula": ["V + that + clause", "whether/if + S + V", "WH + S + V"],
    "lectureJP": "文の中で「何を知っているのか」「何が問題なのか」といった内容全体を名詞のように扱うのが名詞節です。that節、whether/if節、WH節が中心で、埋め込み疑問では疑問文語順にしません。上級では名詞・形容詞の後ろに内容節を置く the fact that / aware that も重要です。",
    "lectureTC": "把「知道什麼」「問題是什麼」這整個命題當名詞使用，就是名詞子句。主要有 that、whether/if、WH 子句。嵌入式疑問使用陳述語序。高階還需掌握 the fact that、aware that 等名詞/形容詞後的內容子句。",
    "usageJP": ["think/know/believe + that節では that を省略できることが多い。", "whether は前置詞後・to不定詞前・選択肢を明示するときに if より広く使える。", "embedded WH clause は what he said / where she went の語順。"],
    "usageTC": ["think/know/believe 後的 that 常可省略。", "whether 比 if 可用範圍更廣，如介系詞後、to 前或明示兩種選擇。", "嵌入 WH 子句用 what he said / where she went 的陳述語序。"],
    "contrasts": [["I don’t know where is he.", "I don’t know where he is.", "埋め込み疑問は平叙文語順。", "嵌入問句用陳述語序。"], ["It depends on if it works.", "It depends on whether it works.", "前置詞 on の後ろは whether が標準的。", "介系詞 on 後標準用 whether。"], ["The fact which he left...", "The fact that he left...", "内容を示す同格thatは関係代名詞ではない。", "表示內容的同位語 that 不是關係代名詞。"]],
    "examples": ["I think that the result is reliable.", "We need to decide whether to continue.", "What he said surprised me.", "The question is whether the cost is justified.", "I was aware that the deadline had changed."],
    "taskJP": "that節、whether節、WH節、the fact that を1文ずつ使う。",
    "taskTC": "各造一句使用 that 子句、whether 子句、WH 子句與 the fact that。"
  },
  {
    "id": "adverbial-clauses",
    "level": "A2-C1",
    "title": "Adverbial Clauses & Linkers — 時・理由・条件・譲歩を論理でつなぐ",
    "titleTc": "副詞子句與連接語：用邏輯連接時間、原因、條件與讓步",
    "focus": "because/since/as, although/even though, while/whereas, unless, despite/in spite of",
    "formula": ["because + clause", "although + clause", "despite + noun/V-ing"],
    "lectureJP": "接続表現は訳語が似ていても、後ろに「節」を取るのか「名詞句」を取るのか、論理関係が何なのかが異なります。although は節、despite は名詞句/動名詞。while は時間だけでなく対比、since は時間だけでなく理由を表します。文章理解では、こうしたlinkerが論理構造を示す標識になります。",
    "lectureTC": "連接表達即使翻譯相似，後面接子句或名詞片語的文法不同，邏輯關係也不同。although 接子句，despite 接名詞片語/動名詞；while 可表時間也可表對比，since 可表時間也可表原因。閱讀時這些 linker 是文章邏輯的重要標誌。",
    "usageJP": ["because + clause / because of + noun phrase。", "although/even though + clause / despite/in spite of + noun/V-ing。", "unless = if ... not だが、すべての否定条件で機械的に置換できるわけではない。"],
    "usageTC": ["because + 子句 / because of + 名詞片語。", "although/even though + 子句 / despite/in spite of + 名詞/V-ing。", "unless 約等於 if ... not，但不能在所有否定條件中機械替換。"],
    "contrasts": [["Despite it was raining...", "Although it was raining... / Despite the rain...", "despite の後ろは節を直接置かない。", "despite 後不能直接接完整子句。"], ["Because of the server failed...", "Because the server failed...", "because of の後ろは名詞句。", "because of 後接名詞片語。"], ["Unless you don’t hurry...", "Unless you hurry...", "unless 自体に否定条件が含まれる。", "unless 本身已有否定條件。"]],
    "examples": ["Although the task was difficult, we finished it.", "We postponed the test because the sensor had failed.", "Despite being tired, she kept working.", "Whereas Model A is faster, Model B is more accurate.", "I’ll call you when I arrive."],
    "taskJP": "理由・譲歩・対比・条件・時間を表す副詞節を各1文作る。",
    "taskTC": "各造一句表達原因、讓步、對比、條件、時間。"
  },
  {
    "id": "reported-speech",
    "level": "B1-C1",
    "title": "Reported Speech — 時制を機械的に戻すのではなく「視点」を移す",
    "titleTc": "轉述語：不是機械退時，而是移動敘述視角",
    "focus": "reported statements/questions, backshift, pronoun/time shifts, say/tell",
    "formula": ["said (that) + clause", "told + O + clause", "asked + WH/whether + S + V"],
    "lectureJP": "reported speech の backshift は「必ず一つ過去にする規則」ではなく、発話時点から報告時点へ視点を移す結果として起こります。今も真実なら現在形を保つこともあります。代名詞、this/that、today/that day、here/there なども視点に合わせて変わります。質問を報告するときは語順を平叙文へ戻します。",
    "lectureTC": "轉述語的 backshift 不是「一定退一個時態」的機械規則，而是從原說話時間移到轉述時間後的結果。如果內容現在仍成立，也可能保留現在式。代名詞、this/that、today/that day、here/there 也需依視角調整。轉述問句則恢復陳述語序。",
    "usageJP": ["say は通常目的語を直接取らず say to someone、tell は tell someone。", "reported question では do/does/did を使わず語順も平叙文。", "一般真理や今も続く事実は backshift しないことがある。"],
    "usageTC": ["say 通常不直接接受詞人稱：say to someone；tell 則 tell someone。", "轉述問句不用 do/does/did，語序回陳述句。", "普遍真理或現在仍成立的事實可不退時。"],
    "contrasts": [["He said me that...", "He told me that... / He said to me that...", "say と tell の項構造が違う。", "say 與 tell 的受詞結構不同。"], ["She asked where was I.", "She asked where I was.", "reported question は平叙文語順。", "轉述問句使用陳述語序。"], ["He told that he was busy.", "He said that he was busy.", "tell は通常「誰に」を必要とする。", "tell 通常需要「告訴誰」。"]],
    "examples": ["She said that she was tired.", "He told me that the meeting had been cancelled.", "They asked whether I needed help.", "The teacher said that water boils at 100°C.", "She asked where I had put the key."],
    "taskJP": "直接話法の発言2つと質問2つを、自分でreported speechへ書き換える。",
    "taskTC": "把兩個直接敘述與兩個直接問句改寫成轉述語。"
  },
  {
    "id": "reporting-verbs",
    "level": "B2-C2",
    "title": "Reporting Verbs — say/tell の先へ進み、意図まで正確に報告する",
    "titleTc": "轉述動詞：超越 say/tell，精確表達說話意圖",
    "focus": "advise, suggest, warn, deny, admit, remind, accuse, recommend",
    "formula": ["V + to-inf", "V + O + to-inf", "V + V-ing", "V + that-clause", "V + prep + V-ing"],
    "lectureJP": "上級では「何を言ったか」だけでなく、助言・警告・否認・認める・主張するなど発話行為を選ぶことで文章が精密になります。ただし reporting verb ごとに後続パターンが異なるため、意味と構文をセットで学ぶ必要があります。Cambridge/British CouncilのC1でも重要な領域です。",
    "lectureTC": "高階英文不只報告「說了什麼」，還可用 advise、warn、deny、admit 等表達發話行為，使文章更精確。但每個 reporting verb 的後續結構不同，所以必須把語意與句型一起學。",
    "usageJP": ["advise/remind/warn + O + to-inf。", "admit/deny/suggest + V-ing / that-clause など動詞ごとの型を覚える。", "accuse + O + of + V-ing、apologise for + V-ing のような前置詞もセット。"],
    "usageTC": ["advise/remind/warn + O + to-inf。", "admit/deny/suggest 可接 V-ing 或 that 子句等，依動詞記模式。", "accuse + O + of + V-ing、apologise for + V-ing 等介系詞也要一起記。"],
    "contrasts": [["He suggested me to wait.", "He suggested waiting / suggested that I wait.", "suggest は通常 O + to-inf 不可。", "suggest 通常不接 O + to-inf。"], ["She reminded to call him.", "She reminded me to call him.", "remind は誰に、を示す目的語が必要。", "remind 需要指出提醒誰。"], ["He denied to take it.", "He denied taking it.", "deny は -ing を取る。", "deny 後接 -ing。"]],
    "examples": ["She advised me to apply early.", "He denied leaking the document.", "The report suggests reducing the number of steps.", "They warned us not to touch the device.", "She admitted that she had made a mistake."],
    "taskJP": "advise / deny / suggest / warn / admit / remind を使い、それぞれ異なる構文で6文作る。",
    "taskTC": "使用 advise / deny / suggest / warn / admit / remind，按各自句型造六句。"
  },
  {
    "id": "tags-responses",
    "level": "A2-C1",
    "title": "Question Tags, Short Answers & Response Grammar — 会話を自然につなぐ",
    "titleTc": "附加問句、簡答與回應文法：讓對話自然延續",
    "focus": "question tags, short answers, so/neither, echo questions, auxiliaries in responses",
    "formula": ["statement, aux + pronoun?", "So + aux + S", "Neither/Nor + aux + S"],
    "lectureJP": "実際の会話では毎回答えを完全な文で言いません。英語は助動詞を使って short answer、question tag、So do I / Neither do I のような反応を作ります。これらは「会話文法」で、Listeningでも非常に重要です。tag question の肯否は主節に合わせ、イントネーションによって本当に質問しているか確認だけかも変わります。",
    "lectureTC": "真實對話不會每次都用完整句回答。英文利用助動詞形成 short answer、question tag、So do I / Neither do I 等回應。這是重要的「對話文法」，對聽力也很關鍵。附加問句的肯否需配合主句，語調還會影響它是實際提問還是確認。",
    "usageJP": ["肯定文 + negative tag、否定文 + positive tag が基本。", "short answer は Yes, I do. / No, she isn’t. のように適切な助動詞を再利用。", "So do I / Neither can I は相手の発言への一致を短く示す。"],
    "usageTC": ["基本為肯定主句＋否定 tag，否定主句＋肯定 tag。", "簡答重複適當助動詞：Yes, I do. / No, she isn’t.。", "So do I / Neither can I 簡潔表示與對方相同。"],
    "contrasts": [["You like it, do you?", "You like it, don’t you?", "通常の確認tagは極性を反転。", "一般確認 tag 需反轉肯否。"], ["Yes, I like.", "Yes, I do.", "short answer では助動詞を使う。", "簡答使用助動詞。"], ["I don’t either. → So do I.", "I don’t either. → Neither do I.", "否定への一致は Neither/Nor。", "對否定陳述表示一致用 Neither/Nor。"]],
    "examples": ["You’ve met her before, haven’t you?", "No, I haven’t.", "I love this place. — So do I.", "I can’t hear it. — Neither can I.", "You did what?"],
    "taskJP": "question tagを3つ、short answerを3つ、So/Neither responseを2組作る。",
    "taskTC": "造三個附加問句、三個簡答、兩組 So/Neither 回應。"
  },
  {
    "id": "participle-clauses",
    "level": "B2-C2",
    "title": "Participle & Reduced Clauses — 情報を圧縮し、文を上級化する",
    "titleTc": "分詞子句與縮減子句：壓縮資訊",
    "focus": "present/past/perfect participle clauses, reduced relatives, dangling participles",
    "formula": ["V-ing, main clause", "p.p., main clause", "Having + p.p., main clause"],
    "lectureJP": "分詞節は because/when/after などの従属節を圧縮し、書き言葉を密度高くできます。ただし省略された主語は原則として主節の主語と一致しなければならず、Walking down the street, the rain started. のような dangling participle は避けます。Having + p.p. は主節より前に完了したことを明確にできます。",
    "lectureTC": "分詞子句可壓縮 because/when/after 等從屬子句，使書面語更緊湊。但被省略的主詞原則上要與主句主詞一致，避免 Walking down the street, the rain started. 這類懸垂分詞。Having + 過去分詞可明確表示先於主句完成。",
    "usageJP": ["同時/原因/結果など文脈で関係を解釈する。", "受動なら p.p. で始めることが多い。", "主語一致を必ず確認し、曖昧なら完全な節に戻す。"],
    "usageTC": ["同時、原因、結果等關係由語境判斷。", "被動意義常用過去分詞開頭。", "一定確認省略主詞與主句主詞一致，若曖昧則改回完整子句。"],
    "contrasts": [["Walking to school, the rain started.", "Walking to school, I got caught in the rain.", "walking の意味上の主語は I。", "walking 的隱含主詞需是 I。"], ["After I had finished the test, I left.", "Having finished the test, I left.", "完了分詞で先行動作を圧縮。", "用完成分詞壓縮先發生的動作。"], ["The data which was collected...", "The data collected...", "受動の関係節を過去分詞で縮減。", "可用過去分詞縮減被動關係子句。"]],
    "examples": ["Having checked the logs, I restarted the server.", "Built in 2025, the prototype is still being tested.", "Students working in the lab must wear glasses.", "Given enough data, the model performs well.", "Compared with the baseline, our method is faster."],
    "taskJP": "完全な従属節3文を分詞節へ書き換え、主語一致を確認する。",
    "taskTC": "把三個完整從屬子句改寫成分詞子句，並檢查隱含主詞是否一致。"
  },
  {
    "id": "ellipsis-substitution",
    "level": "B2-C2",
    "title": "Ellipsis & Substitution — 繰り返さず、自然で密度の高い英語にする",
    "titleTc": "省略與替代：避免重複，讓英文自然緊湊",
    "focus": "ellipsis, do so, one/ones, so/not, auxiliary substitution",
    "formula": ["auxiliary + Ø", "do so", "one/ones", "I think so / I hope not"],
    "lectureJP": "上級英語では、文法的に復元できる情報をあえて言わないことで自然さと結束性を作ります。助動詞の後ろの動詞句省略、do so、one/ones、I think so / I hope not などが代表例です。省略は「短くする技術」ではなく、聞き手が何を復元できるかを利用する談話文法です。",
    "lectureTC": "高階英文常把可從語法與上下文恢復的內容省略，以提高自然度與銜接性。常見形式包括助動詞後省略動詞片語、do so、one/ones、I think so / I hope not。省略不是單純「縮短」，而是利用聽者可恢復資訊的篇章文法。",
    "usageJP": ["I can, but she can’t. のように助動詞だけ残せる。", "do so は動作内容の繰り返しを避け、one/ones は可算名詞を代用。", "so/not はthink/hope/supposeなどの節内容を代用できる。"],
    "usageTC": ["I can, but she can’t. 可只保留助動詞。", "do so 代替動作內容；one/ones 代替可數名詞。", "so/not 可代替 think/hope/suppose 等後面的整個命題。"],
    "contrasts": [["I can solve it, and she can solve it too.", "I can solve it, and she can too.", "反復するVPを省略できる。", "可省略重複的動詞片語。"], ["I need a new laptop, a lighter laptop.", "I need a new laptop, a lighter one.", "one で名詞反復を避ける。", "用 one 避免重複名詞。"], ["Will it work? I think that it will work.", "Will it work? I think so.", "so が命題全体を代用。", "so 可代替整個命題。"]],
    "examples": ["I haven’t finished yet, but she has.", "If you need to restart the system, please do so.", "The cheaper option is actually the better one.", "Will they accept it? I hope so.", "Some students chose Python; others chose C++."],
    "taskJP": "同じ名詞・動詞句・節を繰り返している英文を5つ作り、ellipsis/substitutionで自然に短くする。",
    "taskTC": "先寫五個有名詞、動詞片語或子句重複的英文，再用省略/替代改得自然。"
  },
  {
    "id": "punctuation-usage",
    "level": "A2-C1",
    "title": "Punctuation, Capitalisation & Written Grammar — 書き言葉の文法を完成させる",
    "titleTc": "標點、大小寫與書面文法",
    "focus": "comma, semicolon, colon, apostrophe, sentence boundaries, capitalisation",
    "formula": ["independent clause ; independent clause", "introductory clause, main clause", "possessive ’s"],
    "lectureJP": "句読点は装飾ではなく、文の構造と情報関係を可視化する文法の一部です。comma splice、run-on sentence、apostrophe の所有と複数の混同は、上級Writingでも評価を落とします。英語では固有名詞・曜日・月・言語名などの大文字規則も日本語と異なります。",
    "lectureTC": "標點不是裝飾，而是把句構與資訊關係視覺化的書面文法。comma splice、run-on sentence，以及所有格 apostrophe 與複數混淆，即使高階寫作也會扣分。英文的專有名詞、星期、月份、語言名稱等大寫規則也與中日文不同。",
    "usageJP": ["独立節同士を comma だけでつながない。接続詞、semicolon、periodを使う。", "apostrophe は所有・省略に使い、通常の複数には使わない。", "導入副詞節・長い前置きの後のcommaで構造を見せる。"],
    "usageTC": ["兩個獨立子句不能只用 comma 連接；要用連接詞、分號或句號。", "apostrophe 用於所有或縮寫，不用於普通複數。", "導入副詞子句或較長前置成分後用 comma 顯示結構。"],
    "contrasts": [["The model failed, we restarted it.", "The model failed, so we restarted it.", "comma splice を避ける。", "避免 comma splice。"], ["three robot’s", "three robots", "普通の複数にapostrophe不要。", "普通複數不加 apostrophe。"], ["monday / english", "Monday / English", "曜日・言語名は大文字。", "星期與語言名稱大寫。"]],
    "examples": ["Although the test failed, we learned something useful.", "The first model was fast; the second was more accurate.", "There was one problem: the battery was empty.", "The student’s laptop was missing.", "I study English on Monday evenings."],
    "taskJP": "comma spliceを2つ修正し、semicolon・colon・apostropheをそれぞれ使う文を作る。",
    "taskTC": "修正兩個 comma splice，並各造一句使用 semicolon、colon、apostrophe。"
  }
];
grammarLessons.push(...additionalGrammarLessons);

const grammarDomains = [
  {"id":"sentence","name":"Sentence & Clause Architecture","jp":"文の骨格・節・語順","lessonIds":["architecture","auxiliaries","there-it","questions"],"topics":["SV/SVC/SVO/SVOO/SVOC","transitivity & valency","be/do/have","there is/are","dummy it","negation","direct & embedded questions","inversion"]},
  {"id":"noun","name":"Noun Phrase System","jp":"名詞句・冠詞・数量・代名詞","lessonIds":["nouns","pronouns-possessives","quantifiers","agreement"],"topics":["countability","a/an/the/zero article","determiners","some/any","much/many","few/little","each/every","both/either/neither","pronouns","possessives","reflexives","agreement & reference"]},
  {"id":"verbtime","name":"Tense, Aspect & Modality","jp":"時制・相・未来・法","lessonIds":["tense","aspect","future-forms","modality","modal-perfects","habitual-forms","conditionals"],"topics":["present/past","future forms","progressive aspect","perfect aspect","perfect progressive","stative verbs","modal meanings","modal perfects","used to/would","conditionals","wish/subjunctive"]},
  {"id":"verbpatterns","name":"Verb Patterns & Voice","jp":"動詞語法・非定形・態","lessonIds":["nonfinite","passive","complementation","multiword-verbs"],"topics":["to-infinitive","gerunds","participles","verb complementation","bare infinitive","passive voice","get passive","causatives","phrasal verbs","prepositional verbs"]},
  {"id":"modifier","name":"Modification & Comparison","jp":"形容詞・副詞・比較・前置詞","lessonIds":["adjectives-adverbs","comparison-degree","prepositions"],"topics":["adjectives vs adverbs","-ed/-ing adjectives","adverb position","degree adverbs","comparatives","superlatives","as...as","too/enough","so/such","prepositions of time/place/movement","adjective/verb + preposition"]},
  {"id":"clauses","name":"Complex Clauses","jp":"複文・関係・内容・副詞節","lessonIds":["relative","noun-clauses","adverbial-clauses","participle-clauses","reported-speech","reporting-verbs"],"topics":["defining relatives","non-defining relatives","reduced relatives","that clauses","whether/if clauses","WH clauses","adverbial clauses","concession/contrast","participle clauses","reported statements/questions","reporting verb patterns"]},
  {"id":"interaction","name":"Interaction Grammar","jp":"会話・応答の文法","lessonIds":["questions","tags-responses","register"],"topics":["question tags","short answers","so/neither","echo questions","politeness","directness","hedging","formal/neutral/casual register"]},
  {"id":"discourse","name":"Discourse & Information","jp":"談話・情報構造・結束性","lessonIds":["information","discourse","ellipsis-substitution"],"topics":["given/new information","fronting","cleft sentences","cohesion","reference chains","linking devices","ellipsis","substitution","avoiding repetition"]},
  {"id":"precision","name":"Advanced Written Precision","jp":"C1/C2精密文法・書き言葉","lessonIds":["precision","participle-clauses","reporting-verbs","punctuation-usage"],"topics":["nominalisation","apposition","complex noun phrases","advanced modification","parallelism","compressed clauses","academic reporting","punctuation","capitalisation","sentence boundaries"]}
];
