const masteryTracks = [
  {
    icon: '01',
    title: 'Grammar & Syntax',
    jp: '文型を覚えるだけでなく、時制・相・法・節・情報構造まで「なぜその形を選ぶか」を説明し、自分で選べる状態を目指す。',
    tc: '不只背句型，而是理解時態、體、語氣、子句與資訊結構，能說明「為什麼選這個形式」並自行運用。',
    target: 'A1 → C2',
  },
  {
    icon: '02',
    title: 'Vocabulary & Collocation',
    jp: '単語の日本語訳ではなく、語族・コロケーション・句動詞・レジスター・類義語の差までセットで覚える。',
    tc: '不只記中文意思，而是一起學詞族、搭配、片語動詞、語域與近義詞差異。',
    target: 'Active + Receptive',
  },
  {
    icon: '03',
    title: 'Pronunciation & Phonology',
    jp: '個々の音だけでなく、強勢、弱形、schwa、連結、脱落、リズム、イントネーションまで扱う。聞き取りと発話を同時に改善する。',
    tc: '不只練單音，也學重音、弱讀、schwa、連音、省音、節奏與語調，同時改善聽力與口說。',
    target: 'Clear & Natural',
  },
  {
    icon: '04',
    title: 'Listening',
    jp: '音を拾う→意味のまとまりで処理する→話者の意図や暗示まで取る、の3段階で鍛える。',
    tc: '依序訓練「辨音 → 以意群處理 → 理解說話者意圖與暗示」三個層次。',
    target: 'Detail + Inference',
  },
  {
    icon: '05',
    title: 'Reading',
    jp: '構文解析だけでなく、指示語、論理関係、段落構造、筆者の態度、推論、速読まで扱う。',
    tc: '除了句構分析，也訓練指涉、邏輯關係、段落結構、作者態度、推論與快速閱讀。',
    target: 'Accuracy + Speed',
  },
  {
    icon: '06',
    title: 'Speaking',
    jp: '正しい1文から始め、説明・比較・理由・反論・要約・即答へ広げる。流暢さと正確さを別々に訓練する。',
    tc: '從正確的一句話開始，擴展到說明、比較、理由、反駁、摘要與即答，分開訓練流暢度與正確度。',
    target: 'Interaction + Fluency',
  },
  {
    icon: '07',
    title: 'Writing',
    jp: '文法的に正しいだけでなく、読みやすい情報順序、段落、接続、語調、要約、メール、技術文書まで練習する。',
    tc: '不只要求文法正確，也練資訊排序、段落、連接、語氣、摘要、郵件與技術寫作。',
    target: 'Sentence → Essay',
  },
  {
    icon: '08',
    title: 'Pragmatics & Register',
    jp: '「文法的には正しいが不自然」を減らす領域。丁寧さ、距離感、含意、直接/間接表現、会話の自然な反応を学ぶ。',
    tc: '減少「文法對但不自然」的英文，學禮貌程度、距離感、言外之意、直接/間接表達與自然回應。',
    target: 'Natural Usage',
  },
];

const grammarLessons = [
  {
    id: 'architecture', level: 'A1-A2',
    title: 'Sentence Architecture — 文の骨格と動詞の支配力',
    titleTc: '句子骨架與動詞的支配力',
    focus: 'S / V / O / C、5文型、verb valency',
    formula: ['SV', 'SVC', 'SVO', 'SVOO', 'SVOC'],
    lectureJP: '英語では語順が文法情報を大量に持ちます。特に動詞は「後ろに何を必要とするか」を決めます。arrive は通常目的語を直接取らず、discuss は about を必要とせず目的語を直接取ります。5文型は暗記表ではなく、動詞が作れる構造を予測するための地図です。',
    lectureTC: '英文的語序承擔大量文法資訊，尤其動詞會決定後面需要什麼。arrive 通常不直接接受詞，而 discuss 可直接接受詞、不需要 about。五大句型不是背誦表，而是預測動詞能形成什麼結構的地圖。',
    usageJP: ['自動詞と他動詞を「日本語訳」ではなく構造で覚える。', 'SVC の C は S を説明し、SVOC の C は O を説明する。', 'give / show / tell のような二重目的語を取れる動詞と、explain のように取れない動詞を区別する。'],
    usageTC: ['用句構而不是翻譯記住不及物/及物動詞。', 'SVC 的 C 說明 S；SVOC 的 C 說明 O。', '區分可接受雙受詞的 give/show/tell 與不能這樣用的 explain。'],
    contrasts: [
      ['I arrived Tokyo.', 'I arrived in Tokyo.', 'arrive は自動詞。場所には通常前置詞が必要。', 'arrive 是不及物動詞，地點通常需要介系詞。'],
      ['We discussed about the issue.', 'We discussed the issue.', 'discuss 自体に「〜について話し合う」が含まれる。', 'discuss 本身已包含「討論某事」的意思。'],
      ['He explained me the problem.', 'He explained the problem to me.', 'explain は SVOO にしない。', 'explain 不能直接形成 SVOO。'],
    ],
    examples: ['The experiment failed.', 'The result seems promising.', 'We tested the model.', 'She gave me useful advice.', 'They found the interface confusing.'],
    taskJP: '自分の研究・学校・日常から、SV / SVC / SVO / SVOO / SVOC を1文ずつ作る。',
    taskTC: '用自己的研究、學校或日常各造一個 SV / SVC / SVO / SVOO / SVOC 句子。',
  },
  {
    id: 'auxiliaries', level: 'A1-B1',
    title: 'be / do / have — 英語文法の3本柱',
    titleTc: '英文文法的三大支柱',
    focus: 'main verb / auxiliary、否定、疑問、進行、完了、受動',
    formula: ['be + C / V-ing / p.p.', 'do + base verb', 'have + p.p.'],
    lectureJP: 'be・do・have は一般動詞としても助動詞としても働きます。重要なのは単語の訳ではなく「文法装置として何を作るか」です。be は状態・進行・受動、do は一般動詞文の否定・疑問・強調、have は完了を作ります。助動詞として使われるとき、その後ろの動詞形までセットで決まります。',
    lectureTC: 'be、do、have 既可以當主要動詞，也能當助動詞。重點不是翻譯，而是它們作為「文法裝置」能形成什麼：be 形成狀態/進行/被動，do 形成一般動詞的否定/疑問/強調，have 形成完成式。',
    usageJP: ['be動詞文に do を追加しない。', 'do/does/did が時制・人称を持つと、本動詞は原形に戻る。', '完了の have と所有の have を構造で見分ける。'],
    usageTC: ['be 動詞句不要再加 do。', 'do/does/did 承擔時態與人稱後，主要動詞回到原形。', '從結構區分完成式 have 與「擁有」的 have。'],
    contrasts: [
      ['Does she is busy?', 'Is she busy?', 'be 自身を主語の前へ移動する。', 'be 自己移到主詞前即可。'],
      ['He does not works here.', 'He does not work here.', 'does に三単現情報があるため work は原形。', 'does 已承擔第三人稱資訊，work 回原形。'],
      ['I have a car.', 'I have finished the task.', '前者は所有、後者は have + p.p. の完了。', '前者是擁有，後者是 have + 過去分詞的完成式。'],
    ],
    examples: ['I am tired.', 'I am working now.', 'The device was repaired.', 'Do you understand?', 'I have already sent the email.'],
    taskJP: 'be / do / have をそれぞれ「一般動詞として1文」「助動詞として1文」作る。',
    taskTC: 'be / do / have 各造一個「主要動詞用法」與「助動詞用法」的句子。',
  },
  {
    id: 'nouns', level: 'A1-B2',
    title: 'Nouns, Articles & Determiners — a / the / 無冠詞を感覚で選ぶ',
    titleTc: '名詞、冠詞與限定詞',
    focus: 'countability、generic/specific、a/an、the、zero article、some/any',
    formula: ['a/an + singular count noun', 'the + identifiable noun', 'Ø + plural/uncountable generic noun'],
    lectureJP: '冠詞は「日本語に訳せない小さい単語」ではなく、話し手が名詞をどう提示しているかを示します。a/an は聞き手がまだ特定できない1つ、the は文脈・常識・後置修飾などによって特定できるもの、無冠詞は複数や不可算名詞を一般概念として述べるときによく使います。まず可算/不可算を判断し、その次に特定性を見ると整理できます。',
    lectureTC: '冠詞不是「無法翻譯的小字」，而是表示說話者如何呈現名詞。a/an 是聽者尚不能特定的一個；the 是能從語境、常識或修飾語辨識的對象；零冠詞常用於把複數或不可數名詞當一般概念談。先判斷可數性，再判斷是否特定。',
    usageJP: ['単数可算名詞は原則として単独で置かない。', 'information / advice / research / equipment は通常不可算。', '初出 a → 次に同じ対象を指す the、という流れを理解する。'],
    usageTC: ['單數可數名詞原則上不能裸用。', 'information / advice / research / equipment 通常不可數。', '理解第一次 a、之後同一對象改用 the 的資訊流。'],
    contrasts: [
      ['I bought computer.', 'I bought a computer.', 'computer は単数可算名詞。', 'computer 是單數可數名詞。'],
      ['an advice', 'some advice / a piece of advice', 'advice は不可算。', 'advice 是不可數名詞。'],
      ['The technology is changing fast.（一般論）', 'Technology is changing fast.', '一般概念なら無冠詞が自然。', '談一般概念時零冠詞較自然。'],
    ],
    examples: ['I saw a robot in the lab. The robot was moving slowly.', 'Information is easy to copy.', 'The information you sent was useful.', 'She gave me some advice.', 'Students need feedback.'],
    taskJP: 'a / the / 無冠詞をそれぞれ2回以上使って、研究室または学校について5文書く。',
    taskTC: '至少各使用兩次 a / the / 零冠詞，寫五句關於研究室或學校的英文。',
  },
  {
    id: 'tense', level: 'A1-B2',
    title: 'Tense — 現在・過去・未来を「時間」だけで選ばない',
    titleTc: '時態：不只看時間選形式',
    focus: 'present simple、past simple、future expressions、time reference',
    formula: ['present: V / V-s', 'past: V-ed / irregular', 'future: will / be going to / present forms'],
    lectureJP: '英語の現在形は「今この瞬間」を表す形ではなく、習慣・一般事実・状態・スケジュールなど、時間幅のある捉え方に向きます。「今やっている」は通常進行形です。また英語に単純な未来時制が1個あるというより、will、be going to、現在進行形、現在形などを意味に応じて選びます。',
    lectureTC: '英文現在簡單式並不是「此刻正在做」的形式，而適合習慣、一般事實、狀態與時刻表等具有時間幅度的情況。「現在正在做」通常用進行式。未來也不是只有一個固定未來式，而是依意義選 will、be going to、現在進行式或現在式。',
    usageJP: ['習慣・反復には現在形、現在進行中の動作には進行形。', '明確な過去時間と現在完了を混ぜない。', 'will はその場の意思・予測、be going to は既存の意図や根拠ある予測に強い。'],
    usageTC: ['習慣反覆用現在式，正在進行用進行式。', '明確過去時間不要與現在完成式混用。', 'will 常表當下決定/預測，be going to 更常表既有計畫或有根據的預測。'],
    contrasts: [
      ['I study English now.', 'I am studying English now.', 'now が「今まさに」なら進行形が基本。', 'now 表示此刻正在進行時，通常用進行式。'],
      ['I have seen him yesterday.', 'I saw him yesterday.', 'yesterday は完結した過去時間。', 'yesterday 是明確且已結束的過去時間。'],
      ['I will meet my professor at 3.（予定）', 'I am meeting my professor at 3.', '個人的に確定した予定は現在進行形が自然なことが多い。', '已安排好的個人行程常用現在進行式更自然。'],
    ],
    examples: ['I usually work at a café.', 'I am working at home today.', 'The meeting starts at nine.', 'I decided yesterday.', 'I am going to redesign the arm.'],
    taskJP: '同じ動詞 study を使い、習慣・今進行中・昨日・確定した明日の予定の4文を作る。',
    taskTC: '用同一個 study，分別造「習慣、現在進行、昨天、明天已安排」四句。',
  },
  {
    id: 'aspect', level: 'A2-C1',
    title: 'Aspect — 進行形・完了形・完了進行形の「見え方」',
    titleTc: '體：進行、完成、完成進行的視角',
    focus: 'progressive、perfect、perfect progressive、state verbs',
    formula: ['be + V-ing', 'have + p.p.', 'have been + V-ing'],
    lectureJP: 'Aspect（相）は、出来事を時間軸のどこに置くかではなく「内部をどう見るか」を表します。進行形は途中をズームして一時的・未完了として見せ、完了形は基準時より前の出来事を現在/過去/未来の基準点につなげます。完了進行形は継続してきた活動そのものに焦点を当てます。',
    lectureTC: 'Aspect（體）不是決定事情在時間軸哪裡，而是決定「怎麼看這件事」。進行式把鏡頭放在過程中，常帶暫時/未完成感；完成式把較早的事件連到現在、過去或未來的基準點；完成進行式則聚焦持續中的活動。',
    usageJP: ['know / believe / own など状態動詞は通常進行形にしにくい。', '現在完了は過去形の丁寧版ではなく、現在との関連が必要。', '結果に焦点: have done / 活動の継続に焦点: have been doing。'],
    usageTC: ['know / believe / own 等狀態動詞通常不易使用進行式。', '現在完成不是過去式的高級版，而必須與現在有關聯。', '重結果用 have done；重持續活動用 have been doing。'],
    contrasts: [
      ['I am knowing the answer.', 'I know the answer.', 'know は典型的な状態動詞。', 'know 是典型狀態動詞。'],
      ['I have finished the report.', 'I have been writing the report.', '前者は完了結果、後者は活動の継続。', '前者強調完成結果，後者強調持續活動。'],
      ['I lived in Japan for five years.（今は不明/終了）', 'I have lived in Japan for five years.（今につながる）', '基準点とのつながりが意味を変える。', '是否與現在基準點相連會改變意思。'],
    ],
    examples: ['She is staying with a friend this week.', 'I have lost my key.', 'We have tested three versions.', 'I have been debugging since morning.', 'By next month, I will have finished the prototype.'],
    taskJP: '自分のプロジェクトについて have done と have been doing を使い、結果と継続を対比する2文を作る。',
    taskTC: '用自己的專案造 have done 與 have been doing 兩句，對比「結果」與「持續活動」。',
  },
  {
    id: 'modality', level: 'A2-C1',
    title: 'Modality — can / may / must / should / will / would の距離感',
    titleTc: '情態：可能性、義務與心理距離',
    focus: 'ability、permission、probability、obligation、politeness、epistemic modality',
    formula: ['modal + base verb', 'modal + have + p.p.'],
    lectureJP: '助動詞は単なる「〜できる」「〜すべき」の翻訳ではなく、話し手が命題にどれくらい確信しているか、相手にどれくらい圧力をかけるか、現実からどれくらい距離を置くかを表します。would/could が丁寧に聞こえるのも、この「距離」を作る働きと関係します。',
    lectureTC: '情態助動詞不只是「可以、應該」的翻譯，而是表達說話者對命題的確信程度、對對方施加多少壓力、以及與現實保持多少心理距離。would/could 聽起來較禮貌，也與這種「距離感」有關。',
    usageJP: ['must / have to / should は義務の強さと情報源が異なる。', 'may / might / could は可能性のニュアンスが重なるが同一ではない。', 'modal + have + p.p. で過去への推量・後悔・批判を表せる。'],
    usageTC: ['must / have to / should 的義務強度與來源不同。', 'may / might / could 都能表可能性，但語感不完全相同。', 'modal + have + 過去分詞可表對過去的推測、後悔或批評。'],
    contrasts: [
      ['You must submit it today.', 'You should submit it today.', 'must は強い必要、should は助言・期待。', 'must 是強制必要；should 偏建議/期待。'],
      ['Can you help me?', 'Could you help me?', 'could は能力の過去だけでなく、依頼を一段遠ざけて丁寧にする。', 'could 不只表過去能力，也用心理距離讓請求更禮貌。'],
      ['He must be tired.', 'He must have been tired.', '前者は現在の強い推量、後者は過去。', '前者推測現在，後者推測過去。'],
    ],
    examples: ['You may want to restart the system.', 'That could be a problem.', 'You should have told me earlier.', 'He must have forgotten the meeting.', 'Would you mind checking this?'],
    taskJP: '同じ依頼「これを確認してください」を can / could / would を使って3段階の距離感で表す。',
    taskTC: '把「請幫我確認這個」分別用 can / could / would 表達三種不同距離感。',
  },
  {
    id: 'nonfinite', level: 'A2-C1',
    title: 'Infinitives, Gerunds & Participles — to / -ing / p.p. を意味で選ぶ',
    titleTc: '不定詞、動名詞與分詞',
    focus: 'to-infinitive、gerund、present/past participle、complement patterns',
    formula: ['to + base', 'V-ing', 'p.p.'],
    lectureJP: 'to不定詞と動名詞は「未来 vs 過去」とだけ覚えると破綻します。実際には動詞ごとの補文パターンと意味のまとまりを学ぶ必要があります。remember to do / remember doing、stop to do / stop doing のように、形が変わると意味も変わる組み合わせが重要です。分詞は動詞由来ですが、形容詞・副詞的に情報を圧縮できます。',
    lectureTC: '只把 to 不定詞和動名詞背成「未來 vs 過去」會失效，實際上要學每個動詞可接的補語形式與意義。remember to do / remember doing、stop to do / stop doing 等形式一變意思也變。分詞雖來自動詞，卻能像形容詞/副詞一樣壓縮資訊。',
    usageJP: ['want/decide/plan は to、enjoy/avoid/finish は -ing を取る代表例。', '意味が変わる動詞: remember, forget, regret, stop, try。', '現在分詞は能動/進行的、過去分詞は受動/完了的な性質を持ちやすい。'],
    usageTC: ['want/decide/plan 常接 to；enjoy/avoid/finish 常接 -ing。', '形式不同意思也變的動詞：remember, forget, regret, stop, try。', '現在分詞常帶主動/進行感；過去分詞常帶被動/完成感。'],
    contrasts: [
      ['I stopped to smoke.', 'I stopped smoking.', '前者は「タバコを吸うため立ち止まった」、後者は「喫煙をやめた」。', '前者是停下來去抽菸，後者是戒掉抽菸。'],
      ['Remember to lock the door.', 'I remember locking the door.', 'これからすること vs した記憶。', '記得去做 vs 記得做過。'],
      ['I am boring.', 'I am bored.', 'boring = 人を退屈させる性質、bored = 自分が退屈を感じる状態。', 'boring 是令人無聊；bored 是自己感到無聊。'],
    ],
    examples: ['I decided to apply.', 'I avoid checking my phone while studying.', 'Try restarting the service.', 'The data collected yesterday looks clean.', 'Students working on the project meet every Friday.'],
    taskJP: 'remember / stop / try のうち2つを選び、to と -ing で意味が変わる対比例を作る。',
    taskTC: '從 remember / stop / try 選兩個，各造一組 to 與 -ing 意義不同的對比例句。',
  },
  {
    id: 'passive', level: 'A2-C1',
    title: 'Passive & Causative — 「誰がしたか」より情報の焦点を制御する',
    titleTc: '被動與使役：控制資訊焦點',
    focus: 'be/get passive、causative have/get、agent omission',
    formula: ['be + p.p.', 'get + p.p.', 'have/get + O + p.p.'],
    lectureJP: '受動態は能動態の機械的な書き換えではありません。話題として何を先頭に置きたいか、行為者が不明・自明・重要でないかによって選びます。技術文書・ニュース・研究では、プロセスや対象を主題にしたい場面が多いため頻出します。get passive は出来事性や口語的な響きが強くなることがあります。',
    lectureTC: '被動態不是把主動句機械改寫。它用來控制資訊焦點：想把什麼放在主題位置、施事者是否未知/明顯/不重要。技術文、新聞、研究常需把流程或對象放在主位，因此被動頻繁。get passive 往往更口語、事件感更強。',
    usageJP: ['by + agent は必要なときだけ書く。', '自動詞は原則として受動態にできない。', 'have/get something done は「自分でなく誰かにしてもらう/何かがされる経験」。'],
    usageTC: ['by + 施事者只有必要時才寫。', '不及物動詞原則上不能被動化。', 'have/get something done 表示請別人做或經歷某事被處理。'],
    contrasts: [
      ['The team developed the model.', 'The model was developed by the team.', 'どちらが既知情報/話題かで選ぶ。', '依哪個是已知資訊/話題來選。'],
      ['I repaired my phone.', 'I had my phone repaired.', '後者は通常、他者に修理してもらった。', '後者通常表示請別人修手機。'],
      ['He was happened to...', 'It happened to him...', 'happen は自動詞なので通常受動不可。', 'happen 是不及物動詞，通常不能被動。'],
    ],
    examples: ['The samples were collected in July.', 'No personal data is stored on the server.', 'My bike got stolen.', 'I had my laptop repaired.', 'The result can be reproduced.'],
    taskJP: '自分の研究説明を能動態3文で書き、そのうち2文を「情報の焦点」を考えて受動態へ変える。',
    taskTC: '先用三個主動句介紹自己的研究，再考慮資訊焦點，把其中兩句改成被動。',
  },
  {
    id: 'questions', level: 'A1-C1',
    title: 'Questions, Negation & Inversion — 英語の「前に出るもの」を理解する',
    titleTc: '疑問、否定與倒裝',
    focus: 'subject-aux inversion、WH questions、embedded questions、negative inversion',
    formula: ['WH + AUX + S + V?', 'embedded: WH + S + V', 'Never + AUX + S + V'],
    lectureJP: '英語の疑問文は「主語と動詞を逆にする」と覚えるより、最初の助動詞を主語の前へ出すと理解すると一貫します。助動詞がない一般動詞文では do を補います。一方、間接疑問では語順を平叙文に戻します。C1以降では否定語を前置した倒装も重要です。',
    lectureTC: '與其背「主詞和動詞顛倒」，更一致的理解是：把第一個助動詞移到主詞前。一般動詞句沒有助動詞時補 do。間接問句則恢復陳述語序。C1 之後還要掌握否定詞前置造成的倒裝。',
    usageJP: ['主語を問う Who called you? では do を使わない。', 'Do you know where he is? の embedded question は where is he にならない。', 'Never / Rarely / Not only などが文頭に来ると倒装が起きる。'],
    usageTC: ['問主詞的 Who called you? 不使用 do。', 'Do you know where he is? 的間接問句不能變成 where is he。', 'Never / Rarely / Not only 等置於句首時會觸發倒裝。'],
    contrasts: [
      ['Do you know where is he?', 'Do you know where he is?', '埋め込み疑問では通常語順。', '間接問句使用一般陳述語序。'],
      ['Who did call you?', 'Who called you?', 'who 自体が主語なら do-support 不要。', 'who 本身是主詞時不需要 do-support。'],
      ['Never I have seen...', 'Never have I seen...', '否定表現を文頭に置く強調では倒装。', '否定表達置首強調時需倒裝。'],
    ],
    examples: ['Why did you choose this method?', 'Who designed this part?', 'Could you tell me where the station is?', 'Rarely do we see such a large difference.', 'Not only did it fail, but it also corrupted the data.'],
    taskJP: '直接疑問→間接疑問を3組作る。余裕があれば Never / Rarely を使う倒装文も1文。',
    taskTC: '造三組直接問句→間接問句；有餘力再用 Never / Rarely 造一個倒裝句。',
  },
  {
    id: 'relative', level: 'A2-C1',
    title: 'Relative Clauses — 情報を後ろから正確に追加する',
    titleTc: '關係子句：從後方精確補充資訊',
    focus: 'restrictive/non-restrictive、who/which/that/whose、reduced relatives',
    formula: ['N + who/which/that + clause', 'N, who/which + clause,'],
    lectureJP: '関係詞節では「どの名詞を限定しているか」と「その情報が識別に必要か」を考えます。制限用法はどの人/物かを絞り、非制限用法はすでに特定された名詞へ追加情報を添えます。コンマの有無は単なる句読点ではなく意味を変えます。上級では分詞による reduced relative も頻繁です。',
    lectureTC: '關係子句要先判斷修飾哪個名詞，以及資訊是否用來辨識該名詞。限制用法縮小範圍；非限制用法對已確定的名詞追加資訊。逗號不是裝飾，而會改變意思。高階英文也常用分詞縮減關係子句。',
    usageJP: ['that は非制限用法では通常使わない。', '目的格関係代名詞は省略できる場合がある。', 'whose は人だけでなく物にも使える。'],
    usageTC: ['that 通常不用於非限制關係子句。', '作受詞的關係代名詞有時可省略。', 'whose 不只修飾人，也能修飾物。'],
    contrasts: [
      ['My brother who lives in Osaka is an engineer.', 'My brother, who lives in Osaka, is an engineer.', '前者は複数の兄弟から限定する含意、後者は既知の兄弟へ追加情報。', '前者暗示需從多個兄弟中辨識；後者只是補充已知兄弟的資訊。'],
      ['The book which I bought...', 'The book I bought...', '目的格なら which/that を省略可能。', '作受詞時 which/that 可省略。'],
      ['students who are working on...', 'students working on...', '関係節を分詞で圧縮できる。', '可用分詞縮減關係子句。'],
    ],
    examples: ['The engineer who designed this system works in Tokyo.', 'My laptop, which I bought last year, is already slow.', 'The method we used was simple.', 'A company whose products I admire contacted me.', 'Data collected from three cameras was synchronized.'],
    taskJP: '制限用法2文、非制限用法1文、関係代名詞省略1文を作る。',
    taskTC: '造兩個限制用法、一個非限制用法、一個省略關係代名詞的句子。',
  },
  {
    id: 'conditionals', level: 'B1-C1',
    title: 'Conditionals & Subjunctive — 現実性と距離を操作する',
    titleTc: '條件句與假設語氣：控制現實距離',
    focus: 'zero/first/second/third/mixed conditionals、wish、subjunctive',
    formula: ['If + present, present/will', 'If + past, would + V', 'If + had p.p., would have p.p.'],
    lectureJP: '条件文は0/1/2/3型を番号で暗記するより、「話し手が条件をどれくらい現実的に見ているか」と「どの時間について話しているか」で理解すると応用できます。過去形が必ず過去時間を意味するわけではなく、仮定法では現実からの距離を表します。',
    lectureTC: '與其死背 0/1/2/3 型，更有效的是看「說話者認為條件有多現實」以及「談哪個時間」。過去式不一定代表過去時間；在假設語氣中，它也用來表示與現實的距離。',
    usageJP: ['一般事実: If + present, present。現実的未来: If + present, will。', '非現実/低可能性: If + past, would。過去反実: If + had p.p., would have p.p.。', 'If I were you は標準的な仮定表現。'],
    usageTC: ['一般事實：If + 現在, 現在；現實未來：If + 現在, will。', '低可能/非現實：If + 過去, would；過去反事實：If + had p.p., would have p.p.。', 'If I were you 是標準假設用法。'],
    contrasts: [
      ['If it rains tomorrow, I would stay home.', 'If it rains tomorrow, I will stay home.', '現実的な未来条件なら通常 will。', '現實可能的未來條件通常用 will。'],
      ['If I was you...', 'If I were you...', '口語では was も聞くが、標準的仮定では were が安全。', '口語可聽到 was，但正式標準用 were 較安全。'],
      ['If I knew, I would tell you.', 'If I had known, I would have told you.', '現在/一般の非現実 vs 過去の反実。', '現在/一般非現實 vs 過去反事實。'],
    ],
    examples: ['If you heat ice, it melts.', 'If I have time tonight, I will call you.', 'If I had more money, I would travel more.', 'If I had known about the deadline, I would have applied.', 'I wish I had started earlier.'],
    taskJP: '自分の現実的な予定、非現実な希望、過去の後悔をそれぞれ条件文で1文ずつ。',
    taskTC: '分別用條件句寫一個現實計畫、一個不太現實的願望、一個過去後悔。',
  },
  {
    id: 'prepositions', level: 'A1-C1',
    title: 'Prepositions — 訳語暗記から「空間・関係のイメージ」へ',
    titleTc: '介系詞：從翻譯背誦轉成關係意象',
    focus: 'in/on/at、to/for、by/with、verb/adjective + preposition',
    formula: ['preposition + noun phrase / V-ing'],
    lectureJP: '前置詞は日本語の「に・で・へ」と1対1対応しません。at は点、on は接触面、in は内部という中心イメージから、時間や抽象関係へ意味が拡張します。また depend on、interested in、responsible for のような組み合わせはコロケーションとして覚える必要があります。',
    lectureTC: '介系詞不會與中文/日文助詞一對一對應。at 的核心是「點」、on 是「接觸面」、in 是「內部」，再延伸到時間與抽象關係。此外 depend on、interested in、responsible for 等要當搭配整組記憶。',
    usageJP: ['時間: at 3:00 / on Monday / in August。', '手段・道具: by train / with a tool。', '前置詞の後ろに動詞を置くなら基本 -ing。'],
    usageTC: ['時間：at 3:00 / on Monday / in August。', '手段工具：by train / with a tool。', '介系詞後若接動詞，通常用 -ing。'],
    contrasts: [
      ['discuss about', 'discuss + object', '前置詞が必要かは動詞パターンで決まる。', '是否需要介系詞由動詞搭配決定。'],
      ['by using a camera', 'with a camera', 'by は方法、with は道具を表しやすい。', 'by 偏方法，with 偏工具。'],
      ['I am good in Python.', 'I am good at Python.', 'good at は定型的な形。', 'good at 是固定搭配。'],
    ],
    examples: ['The meeting starts at 2 p.m.', 'I was born in May.', 'The file is on the desktop.', 'We collected data with three cameras.', 'I am interested in robotics.'],
    taskJP: 'in/on/at を時間と場所で各1回、by/with を各1回使って6文作る。',
    taskTC: 'in/on/at 分別在時間與地點至少使用一次，另用 by/with 各一次，共寫六句。',
  },
  {
    id: 'agreement', level: 'A2-C1',
    title: 'Agreement, Pronouns & Reference — 長い文でも主語を見失わない',
    titleTc: '一致、代名詞與指涉',
    focus: 'subject-verb agreement、pronoun reference、each/every、collective nouns',
    formula: ['singular S + singular V', 'plural S + plural V'],
    lectureJP: '上級になるほど三単現のルール自体ではなく、長い名詞句の中で「本当の主語」がどれかを見抜く力が重要になります。The number of... is / A number of... are のような構造や、each/every、either/neither、関係詞節が挟まる文はTOEICでも一般英文でも誤りやすい部分です。',
    lectureTC: '到了高階，重點不再只是知道第三人稱單數規則，而是能在長名詞片語中找出真正主詞。The number of... is / A number of... are、each/every、either/neither、插入關係子句等都容易出錯。',
    usageJP: ['前置詞句の中の名詞に動詞を引っ張られない。', 'each/every は意味上複数でも文法上一人ずつ扱う。', '代名詞 it/they/this が何を指すか曖昧にしない。'],
    usageTC: ['不要被介系詞片語內的名詞干擾動詞一致。', 'each/every 雖語意涉及多個，但文法上逐一處理。', '避免 it/they/this 的指涉不清。'],
    contrasts: [
      ['The number of users are increasing.', 'The number of users is increasing.', '主語中心は number。', '主詞核心是 number。'],
      ['A number of users is waiting.', 'A number of users are waiting.', 'a number of = many の意味で複数扱い。', 'a number of 表 many，視為複數。'],
      ['Each of the students have...', 'Each of the students has...', '中心語 each は単数。', '核心 each 為單數。'],
    ],
    examples: ['The quality of these results is improving.', 'A number of issues remain unresolved.', 'Every student has access to the system.', 'Neither option works well.', 'The model that uses three cameras performs better.'],
    taskJP: '長い主語（of句または関係詞節を含む）を3つ作り、動詞一致を自分で説明する。',
    taskTC: '造三個包含 of 片語或關係子句的長主詞，並自己解釋動詞為何用單數/複數。',
  },
  {
    id: 'information', level: 'B2-C2',
    title: 'Information Structure — 強調・語順・given/new information',
    titleTc: '資訊結構：強調、語序與新舊資訊',
    focus: 'cleft sentences、fronting、inversion、end-focus、topic/comment',
    formula: ['It is X that...', 'What S V is X', 'Only then + AUX + S + V'],
    lectureJP: 'C1/C2では「文法的に正しい」だけでなく、どの情報を先に置き、どこを強く聞かせるかが重要です。英語は一般に既知情報→新情報、軽い要素→重い要素へ流すと読みやすくなります。cleft（分裂文）やfronting、倒装は、情報の焦点を意図的に操作する道具です。',
    lectureTC: 'C1/C2 不只要求文法正確，也要能控制資訊順序與焦點。英文通常依「已知→新資訊」、「輕→重」排列會更自然。cleft、fronting、倒裝都是刻意控制焦點的工具。',
    usageJP: ['It-cleft は特定要素を対比的に強調する。', 'What-cleft は内容を名詞節化して焦点を後ろへ置ける。', '長く重い情報は文末へ置く end-weight が自然になりやすい。'],
    usageTC: ['It-cleft 用來對比強調特定成分。', 'What-cleft 把內容名詞化並把焦點放後面。', '較長較重的資訊通常放句尾更自然。'],
    contrasts: [
      ['I need more time.', 'What I need is more time.', '後者は「必要なのは何か」を強く焦点化。', '後者強調「我真正需要的是什麼」。'],
      ['John fixed it yesterday.', 'It was John who fixed it yesterday.', 'John を対比強調。', '對比強調 John。'],
      ['Only then I understood...', 'Only then did I understand...', '制限表現の前置で倒装。', '限制表達置首時需倒裝。'],
    ],
    examples: ['What matters most is reliability.', 'It was the timing that caused the problem.', 'Only after testing the hardware did we find the bug.', 'At the center of the system is a small controller.', 'One thing I still need to improve is my English.'],
    taskJP: '普通のSVO文を3つ選び、it-cleft / what-cleft / fronting のいずれかで焦点を変えて書き直す。',
    taskTC: '選三個普通 SVO 句，分別用 it-cleft / what-cleft / fronting 改變資訊焦點。',
  },
  {
    id: 'discourse', level: 'B2-C2',
    title: 'Cohesion & Discourse — 文と文をつなぎ、論理を読ませる',
    titleTc: '篇章銜接：讓句子形成清楚邏輯',
    focus: 'reference、substitution、connectors、theme-rheme、paragraph logic',
    formula: ['claim → reason → evidence → implication'],
    lectureJP: '上級英文の読み書きでは、個々の文法より「文同士がどうつながるか」が品質を決めます。however を増やせば論理的になるわけではありません。代名詞、言い換え、繰り返し、接続表現、段落の主題文を使って、読者が前の情報から次の情報へ迷わず進めるように設計します。',
    lectureTC: '高階閱讀與寫作中，品質常由「句子之間如何連接」決定，而不是單句文法。不是多放 however 就會更有邏輯，而要利用代名詞、改述、關鍵詞重複、連接語與主題句，讓讀者能順利從已知資訊走向新資訊。',
    usageJP: ['however / therefore / moreover の論理関係を正確に使う。', 'this / these が何を受けるか明確にする。', '同じ名詞の機械的反復を避けつつ、重要語は適切に反復して話題を維持する。'],
    usageTC: ['準確使用 however / therefore / moreover 的邏輯關係。', '讓 this / these 的指涉清楚。', '避免機械重複同一名詞，但關鍵詞需要適度重複以維持主題。'],
    contrasts: [
      ['The method is cheap. However, it is also fast.', 'The method is cheap. Moreover, it is fast.', '逆接でなければ however は不適切。', '若不是轉折，however 不合適。'],
      ['This is important.', 'This limitation is important.', 'this + 名詞で指示内容を明示すると読みやすい。', '用 this + 名詞明確指出內容更易讀。'],
      ['Because X. Therefore Y.', 'Because X, Y. / X. Therefore, Y.', '接続の役割を重複させない。', '不要重複表達同一因果關係。'],
    ],
    examples: ['The first prototype was inexpensive. However, its motors were too weak.', 'This limitation led us to redesign the shoulder joint.', 'The new design uses stronger motors; therefore, it can carry a heavier load.', 'In contrast, the software architecture required only minor changes.', 'Overall, the results suggest that the approach is feasible.'],
    taskJP: '自分の研究について5文の段落を書き、however / therefore / in contrast のうち2つだけを必要な場所に使う。',
    taskTC: '用五句寫一段自己的研究介紹，只在真正需要的地方使用 however / therefore / in contrast 中的兩個。',
  },
  {
    id: 'register', level: 'B2-C2',
    title: 'Register & Naturalness — 正しい英語から「場面に合う英語」へ',
    titleTc: '語域與自然度：從正確走向合適',
    focus: 'formal/informal、directness、hedging、stance、business/academic/conversation',
    formula: ['direct ↔ hedged', 'casual ↔ neutral ↔ formal'],
    lectureJP: '文法的に正しくても、場面に対して強すぎたり硬すぎたりすると不自然です。Could you...?、Would it be possible to...?、I was wondering if... は同じ依頼でも距離感が違います。研究・ビジネスでは may / appears to / suggests that のような hedging を使い、断定の強さを証拠に合わせます。',
    lectureTC: '文法正確也可能因為太直接或太正式而不自然。Could you...?、Would it be possible to...?、I was wondering if... 表示不同距離感。研究與商務英文常用 may / appears to / suggests that 等 hedging，讓斷言強度符合證據。',
    usageJP: ['命令形は効率的だが、人への依頼では関係性を考える。', 'academic writing では絶対表現 always/proves を必要以上に使わない。', '口語では短縮形・句動詞、正式文では名詞化や中立語彙が増える傾向。'],
    usageTC: ['命令句有效率，但對人請求時要考慮關係。', '學術寫作避免無證據地大量使用 always/proves 等絕對表達。', '口語較常用縮寫與片語動詞；正式文較常用名詞化與中性詞彙。'],
    contrasts: [
      ['Send me the file.', 'Could you send me the file?', '上下関係や緊急性がなければ後者が安全。', '若無上下關係或緊急性，後者較安全。'],
      ['This proves that our method is best.', 'These results suggest that the method is effective.', '証拠以上に断定しない。', '不要超出證據強度下結論。'],
      ['I wanna check it.', 'I would like to check it.', '場面による語域差。', '依場合選擇口語或正式語域。'],
    ],
    examples: ['Could you take a look when you have a chance?', 'Would it be possible to move the meeting?', 'The results appear to support our hypothesis.', 'I may be wrong, but I think the issue is here.', 'Thanks — that makes sense.'],
    taskJP: '「確認してください」「それは違うと思います」を casual / neutral / formal の3段階で言い換える。',
    taskTC: '把「請確認」「我覺得那不對」各改寫成 casual / neutral / formal 三種語域。',
  },
  {
    id: 'precision', level: 'C1-C2',
    title: 'C1/C2 Precision Grammar — 省略・同格・名詞化・複雑な修飾',
    titleTc: 'C1/C2 精密文法',
    focus: 'ellipsis、apposition、nominalization、complex noun phrases、parallelism',
    formula: ['N + appositive', 'nominalized clause', 'parallel A, B, and C'],
    lectureJP: 'C1/C2で差が出るのは、珍しい文法を知っているかより、複雑な内容を誤解なく圧縮できるかです。同格、名詞化、分詞、前置詞句を使うと情報密度を上げられますが、詰め込みすぎると可読性が落ちます。また and/or で並べる要素は文法形を揃える parallelism が重要です。',
    lectureTC: 'C1/C2 的差距不在於知道多少罕見文法，而在於能否把複雜內容壓縮且不產生歧義。同格、名詞化、分詞與介系詞片語能提高資訊密度，但過度堆疊會降低可讀性。and/or 並列時也要保持 parallelism。',
    usageJP: ['名詞化は文体を引き締めるが、動作主を隠しすぎない。', '長い名詞句は「中心名詞」を必ず把握する。', 'parallel structure は読みやすさだけでなく文法問題でも重要。'],
    usageTC: ['名詞化能提高正式度，但不要過度隱藏動作者。', '長名詞片語一定先找中心名詞。', '平行結構不只影響可讀性，也是常見文法判斷點。'],
    contrasts: [
      ['The system is easy to use, reliable, and it saves energy.', 'The system is easy to use, reliable, and energy-efficient.', '並列形式を揃える。', '讓並列項目的文法形式一致。'],
      ['We analyzed the data and this resulted in...', 'Our analysis of the data resulted in...', '名詞化で情報を圧縮できる。', '可用名詞化壓縮資訊。'],
      ['The fact that..., which...', 'The fact that... / This fact...', '修飾の連鎖で先行詞を曖昧にしない。', '避免修飾鏈造成先行詞不清。'],
    ],
    examples: ['Our analysis of the collected data revealed two major issues.', 'The prototype, a low-cost dual-arm robot, was built in-house.', 'The system is designed to collect, transform, and replay motion data.', 'Given the limited sample size, the result should be interpreted cautiously.', 'The main challenge is the reliable estimation of both arms under occlusion.'],
    taskJP: '自分の研究紹介を80語書き、同格1回・名詞化1回・parallel structure 1回を意図的に使う。',
    taskTC: '用約 80 字介紹自己的研究，刻意使用一次同格、一次名詞化、一次平行結構。',
  },
];

const toeicParts = [
  { part: 'Part 1', name: 'Photographs', jp: '位置・動作・状態を瞬時に言語化する。進行形と受動、前置詞、似た音の distractor に強くなる。', tc: '瞬間把位置、動作、狀態語言化；熟悉進行/被動、介系詞與近音干擾。' },
  { part: 'Part 2', name: 'Question–Response', jp: 'WH語だけで反応せず、意図・時制・間接応答を取る。「Yes/Noで返さない自然な応答」が鍵。', tc: '不要只靠 WH 詞，需抓意圖、時態與間接回答；自然回應不一定是 Yes/No。' },
  { part: 'Part 3', name: 'Conversations', jp: '話者関係・目的・次の行動・暗示を追う。設問先読みと、会話の転換語を使って情報を保持する。', tc: '追蹤人物關係、目的、下一步與暗示；利用先讀題目與轉折詞保留資訊。' },
  { part: 'Part 4', name: 'Talks', jp: 'アナウンス・留守電・説明・広告などの構造を型で捉える。冒頭で場面、途中で詳細、終盤で次の行動を取る。', tc: '掌握公告、語音、說明、廣告等結構；開頭抓場景，中段抓細節，結尾抓下一步。' },
  { part: 'Part 5', name: 'Incomplete Sentences', jp: '品詞→文型→動詞形→語法/コロケーション→意味の順に診断し、1問を長く悩まない。', tc: '依詞性→句構→動詞形式→語法/搭配→語意診斷，不要在單題停太久。' },
  { part: 'Part 6', name: 'Text Completion', jp: '単文文法だけでなく、代名詞・時制の流れ・接続・文挿入による段落整合性を見る。', tc: '不只看單句文法，也看代名詞、時態連貫、連接與插句後的段落一致性。' },
  { part: 'Part 7', name: 'Reading Comprehension', jp: '設問根拠を本文に戻して確認する。言い換え・推論・複数文書の情報統合を高速で行う。', tc: '回正文確認證據，高速處理改述、推論與多篇文件資訊整合。' },
];

const c2Habits = [
  ['Precision', '「通じる」で終わらず、なぜその冠詞・時制・前置詞・語順なのか説明できる。', '不只求能溝通，而能解釋為何選該冠詞、時態、介系詞與語序。'],
  ['Paraphrase', '同じ意味を口語・中立・正式の3通りで言い換えられる。', '同一意思能用口語、中性、正式三種方式改述。'],
  ['Inference', '書かれていない意図・態度・前提を文脈から推論する。', '從語境推論未明說的意圖、態度與前提。'],
  ['Automaticity', '基礎文法を考えず処理し、注意を内容・論理・相手へ回せる。', '基礎文法自動化，把注意力留給內容、邏輯與對方。'],
  ['Self-correction', '自分の発話・作文の不自然さを検出し、より自然な形へ修正する。', '能察覺自己口說/寫作的不自然並自行修正。'],
];
