window.grammarChapters = window.grammarChapters || [];
window.grammarChapters.push(
{
 id:'present-time',level:'A1-B2',domain:'Tense, Aspect & Modality',title:'08 · Present Time — 現在形は「今している」ではない',titleTc:'08 · 現在時間 — 現在式不等於「現在正在做」',
 overviewJP:'英語の現在形は習慣・事実・状態・予定された出来事などを表します。「今この瞬間の動作」は通常進行形です。',overviewTC:'英文現在式常表示習慣、事實、狀態、固定時程；「此刻正在做」通常用進行式。',
 outcomesJP:['現在形の4主要用法を区別する','三単現を自動化する','状態動詞と動作動詞を区別する'],outcomesTC:['區分現在式四大用法','自動化第三人稱單數','區分狀態與動作動詞'],
 units:[
 {id:'habit-fact',title:'習慣・反復・一般事実',level:'A1',explainJP:'現在形の中心は「現在を含む広い時間」で成立することです。always/usually/often/every day などと相性がよく、科学的事実や普遍的傾向にも使います。',explainTC:'現在式核心是「包含現在的一段廣泛時間」。常與 always/usually/often/every day 使用，也表示一般事實。',rulesJP:['習慣・routine','一般事実・恒常的性質','頻度副詞は一般動詞の前、beの後が基本'],rulesTC:['習慣/例行','一般事實/恆常性質','頻率副詞一般在普通動詞前、be 後'],examples:[['I study English every morning.','習慣。','習慣。'],['Water boils at 100°C at sea level.','一般事実。','一般事實。'],['She is usually busy on Mondays.','beの後ろにusually。','usually 在 be 後。']],contrasts:[['I am study English every day.','I study English every day.','習慣にbe + 原形は使わない。','習慣不能用 be + 原形。']],drillJP:'自分の平日routineを現在形10文で書く。',drillTC:'用現在式寫10句自己的平日 routine。'},
 {id:'stative',title:'Stative verbs — know, like, belong, need...',level:'A1-B2',explainJP:'状態動詞は知識・感情・所有・知覚・関係などの「状態」を表し、通常は進行形にしません。ただし think/have/see/taste など意味によって動作用法になる動詞もあります。',explainTC:'狀態動詞表示知識、感情、所有、知覺、關係，通常不用進行式。但 think/have/see/taste 等依意思可變成動作。',rulesJP:['know/believe/understand/want/need/belong/own は典型状態動詞','意味が一時的・動作的なら進行形になる場合がある','I am loving it のような広告・口語的特殊用法もある'],rulesTC:['know/believe/understand/want/need/belong/own 常是狀態動詞','暫時或動作用法可用進行','也有 I am loving it 等特殊口語用法'],examples:[['I understand the problem.','通常進行形にしない。','通常不用進行式。'],['I think this is correct.','think=考える/思うという状態的意見。','think 表示意見。'],['I am thinking about changing jobs.','think about=検討という活動。','think about 是正在考慮。']],contrasts:[['I am knowing the answer.','I know the answer.','knowは通常状態動詞。','know 通常是狀態動詞。']],drillJP:'think/have/see/taste を状態用法と動作用法の両方で例文化。',drillTC:'用 think/have/see/taste 各造狀態與動作用法。'},
 {id:'scheduled-present',title:'未来なのに現在形 — schedules & time clauses',level:'A2-B1',explainJP:'時刻表・固定スケジュールには現在形を使えます。また when/if/before/after/until/as soon as などの未来を表す従属節では、通常willではなく現在形を使います。',explainTC:'時刻表與固定行程可用現在式。未來的 when/if/before/after/until/as soon as 從句通常不用 will，而用現在式。',rulesJP:['The train leaves at 8.','When I arrive, I will call you.','主節にwill、時間/条件節は現在形が基本'],rulesTC:['The train leaves at 8.','When I arrive, I will call you.','主句可 will，時間/條件從句用現在式'],examples:[['The meeting starts at ten tomorrow.','固定予定。','固定行程。'],['I will text you when I get home.','when節はget。','when 從句用 get。'],['If it rains, we will stay inside.','if節はrains。','if 從句用 rains。']],contrasts:[['When I will arrive, I will call you.','When I arrive, I will call you.','通常future time clauseではwillを使わない。','未來時間從句通常不用 will。']],drillJP:'when/if/as soon as/untilを使う未来文を各2文。',drillTC:'用 when/if/as soon as/until 各造2個未來句。'}]
},
{
 id:'past-time',level:'A1-C1',domain:'Tense, Aspect & Modality',title:'09 · Past Time — 過去形・過去進行・過去習慣',titleTc:'09 · 過去時間 — 過去式、過去進行、過去習慣',
 overviewJP:'過去形は「過去に起きた」だけでなく、現在から切り離された時間として提示します。過去進行・used to・wouldとの組み合わせで過去の背景や習慣を細かく表現できます。',overviewTC:'過去式不只表示「發生在過去」，也把事件呈現為與現在分離的時間。過去進行、used to、would 可進一步表示背景與習慣。',outcomesJP:['past simpleの完結性を理解する','past continuousで背景を描ける','used to/wouldとの違いを説明できる'],outcomesTC:['理解過去式的完成/切離感','用過去進行描述背景','解釋 used to/would 差異'],
 units:[
 {id:'past-simple',title:'Past simple — 過去の完結した事実',level:'A1',explainJP:'past simpleは過去の明確な時点・期間に置かれ、現在から切り離された出来事を述べます。yesterday/last year/in 2024/when I was... などとよく使います。',explainTC:'過去式表示位於明確過去時間、與現在切開的事件，常與 yesterday/last year/in 2024 等使用。',rulesJP:['規則動詞-ed / 不規則形','否定・疑問はdid + 原形','過去時間表現と相性がよい'],rulesTC:['規則 -ed / 不規則形','否定疑問 did + 原形','常配明確過去時間'],examples:[['I moved to Japan in 2022.','過去の完結事実。','過去完成事件。'],['She did not attend the meeting.','did not + attend。','did not + attend。'],['When did you start?','did + start。','did + start。']],contrasts:[['Did you started?','Did you start?','didが過去を持つ。','過去由 did 承擔。']],drillJP:'自分の人生の過去イベントを年代順に8文書く。',drillTC:'按時間順序寫8句自己過去事件。'},
 {id:'past-continuous',title:'Past continuous — 背景・進行中・中断',level:'A2-B1',explainJP:'was/were + V-ing は過去のある時点で途中だった活動を表します。物語の背景、同時進行、短い出来事に中断された長い活動によく使います。',explainTC:'was/were + V-ing 表示過去某時正在進行的活動，常用於背景、同時進行、被短事件打斷的長活動。',rulesJP:['背景: It was raining.','長い活動 + when + short event','while + progressive が典型'],rulesTC:['背景：It was raining','長活動 + when + 短事件','while 常配進行式'],examples:[['I was studying when she called.','勉強中に電話。','正在讀書時她打來。'],['While I was cooking, he was cleaning.','同時進行。','同時進行。'],['At nine, I was still working.','過去時点の途中。','九點時仍在工作。']],contrasts:[['I studied when she called.','I was studying when she called.','後者は「進行中に割り込んだ」関係が明確。','後者明確表示被插入的進行活動。']],drillJP:'when/whileを使ったpast simple + past continuousを5組。',drillTC:'用 when/while 寫5組過去式＋過去進行。'},
 {id:'used-to-would',title:'used to / would — 過去の習慣と状態',level:'A2-B2',explainJP:'used toは過去の習慣・状態が今は違うという含意を持ちます。wouldは物語の中で繰り返した行動を表せますが、通常be/know/liveのような状態には使いにくいです。',explainTC:'used to 表示過去習慣/狀態，常暗示現在不同。would 可描述過去反覆行為，但通常不適合 be/know/live 等狀態。',rulesJP:['used to + base: 行動も状態も可','would + base: 繰り返し行動','be used to + noun/-ing = 慣れている とは別物'],rulesTC:['used to + 原形：行動/狀態皆可','would：反覆行為','be used to + 名詞/-ing = 習慣於，完全不同'],examples:[['I used to live in Shanghai.','過去状態。','過去狀態。'],['Every summer, we would visit my grandparents.','繰り返し行動。','反覆行為。'],['I am used to commuting by train.','電車通勤に慣れている。','習慣搭電車通勤。']],contrasts:[['I would live in Shanghai.（過去状態の意味）','I used to live in Shanghai.','状態ならused toが自然。','狀態用 used to 更自然。']],drillJP:'used to / would / be used to / get used to を各2文。',drillTC:'用 used to / would / be used to / get used to 各造2句。'}]
},
{
 id:'future-forms',level:'A2-C1',domain:'Tense, Aspect & Modality',title:'10 · Future Forms — willだけで未来を表さない',titleTc:'10 · 未來表達 — 未來不只有 will',
 overviewJP:'英語には単純な「未来時制」一つではなく、will / be going to / present continuous / present simple / be about to / future continuous / future perfect など、意味の違う未来表現があります。',overviewTC:'英文未來不是單一時態，而有 will / be going to / 現在進行 / 現在式 / be about to / 未來進行 / 未來完成等不同語意。',outcomesJP:['willとgoing toを意味で選ぶ','arrangementとscheduleを区別する','future continuous/perfectを使える'],outcomesTC:['依意思選 will/going to','區分安排與時程','使用未來進行/未來完成'],
 units:[
 {id:'will',title:'will — 即時判断・予測・意志',level:'A2-B1',explainJP:'willは単なる未来マーカーではありません。話している瞬間の決定、意志、約束、話し手の予測などに使われます。',explainTC:'will 不只是未來標記，也表示當下決定、意願、承諾、說話者預測。',rulesJP:['instant decision','promise/offer/willingness','prediction based on opinion'],rulesTC:['當下決定','承諾/提議/意願','基於意見的預測'],examples:[['I will help you.','今決めた/意志。','當下決定/意願。'],['I think it will work.','予測。','預測。'],['I will not tell anyone.','約束。','承諾。']],contrasts:[['Look at those clouds. It will rain.','Look at those clouds. It is going to rain.','目に見える根拠がある予測はgoing toが典型。','有眼前證據常用 going to。']],drillJP:'instant decision / promise / prediction のwillを各3文。',drillTC:'用 will 做當下決定、承諾、預測各3句。'},
 {id:'going-to',title:'be going to — 事前意図・現在の根拠',level:'A2-B1',explainJP:'going toは話す前からある意図・計画、または現在見えている証拠からの予測に使います。',explainTC:'going to 表示說話前已有的意圖/計畫，或根據目前證據的預測。',rulesJP:['prior intention','evidence-based prediction','go/comeではpresent continuousの方が自然な場合も多い'],rulesTC:['事前意圖','有證據的預測','go/come 等常用現在進行表示安排'],examples:[['I am going to apply next week.','事前計画。','事前計畫。'],['It is going to fall.','今見える兆候。','眼前跡象。'],['We are going to redesign the arm.','意図。','意圖。']],contrasts:[['I will apply next week.','I am going to apply next week.','前者は意志/予測、後者は既存計画を強く示す。','後者更明顯表示已有計畫。']],drillJP:'will/going to の意味差が出る対比例を5組。',drillTC:'寫5組 will/going to 對比例句。'},
 {id:'arrangement-schedule',title:'Present continuous vs present simple for future',level:'A2-B2',explainJP:'現在進行形は個人的に具体的な手配が済んだ未来、現在形は時刻表・公式スケジュールなど固定された未来に使います。',explainTC:'現在進行表示已安排好的個人未來；現在式表示時刻表、官方時程等固定未來。',rulesJP:['I am meeting... = arrangement','The train leaves... = timetable','時間表現を添えると未来意味が明確'],rulesTC:['I am meeting = 已安排','The train leaves = 時刻表','加時間表達明確未來'],examples:[['I am meeting my professor tomorrow.','約束済み。','已約好。'],['The flight departs at 6:30.','時刻表。','時刻表。'],['We are presenting on Friday.','予定済みイベント。','已安排的活動。']],contrasts:[['I meet my professor tomorrow.','I am meeting my professor tomorrow.','個人的手配には進行形が自然。','個人安排用進行式更自然。']],drillJP:'自分の来週の予定をarrangementとscheduleに分けて各4文。',drillTC:'把下週計畫分成 arrangement/schedule 各4句。'},
 {id:'future-cont-perfect',title:'Future continuous / perfect — 未来の途中と未来までの完了',level:'B1-C1',explainJP:'will be V-ingは未来のある時点で進行中、will have p.p.は未来の基準時までに完了していることを表します。will have been V-ingは継続期間に焦点を置きます。',explainTC:'will be V-ing 表示未來某時正在進行；will have p.p. 表示到未來基準點前已完成；will have been V-ing 強調持續時間。',rulesJP:['this time tomorrow → future continuous','by + future point → future perfect','for + duration + by... → future perfect progressive'],rulesTC:['this time tomorrow 常配未來進行','by + 未來時間常配未來完成','持續期間可用未來完成進行'],examples:[['This time tomorrow, I will be flying to Taipei.','未来の途中。','未來某時正在進行。'],['By Friday, I will have finished the report.','金曜までに完了。','週五前完成。'],['By June, I will have been working here for a year.','継続期間。','到六月已持續一年。']],contrasts:[['By Friday, I will finish the report.','By Friday, I will have finished the report.','後者は基準時までの完了を明確化。','後者更清楚表達截止前完成。']],drillJP:'by next month / this time tomorrow / for two years by...を使い3種類作る。',drillTC:'用 by next month / this time tomorrow / for two years by... 各造句。'}]
},
{
 id:'progressive-aspect',level:'A1-C1',domain:'Tense, Aspect & Modality',title:'11 · Progressive Aspect — 「進行中」以上の意味',titleTc:'11 · 進行體 — 不只表示「正在做」',
 overviewJP:'progressiveは出来事を内部から「途中」として見るアスペクトです。今進行中だけでなく、一時性、変化、反復への感情、未来予定にも使われます。',overviewTC:'進行體把事件從內部看成「進行中」。除了此刻動作，也表示暫時性、變化、帶情緒的反覆與未來安排。',outcomesJP:['temporary/permanentを区別する','changing situationを表せる','always + progressiveの感情色を理解する'],outcomesTC:['區分暫時/永久','表示變化中的狀況','理解 always + progressive 的情緒'],
 units:[
 {id:'in-progress',title:'Action in progress — 基準時の途中',level:'A1',explainJP:'be + V-ingの基本は、基準時点で活動が始まっていてまだ終わっていないことです。基準時は現在だけでなく過去・未来にも設定できます。',explainTC:'be + V-ing 基本表示在基準時間活動已開始但未結束。基準點可在現在、過去或未來。',rulesJP:['am/is/are V-ing','was/were V-ing','will be V-ing'],rulesTC:['現在進行','過去進行','未來進行'],examples:[['I am reading now.','現在途中。','現在進行。'],['I was reading at ten.','過去途中。','過去進行。'],['I will be reading tonight.','未来途中。','未來進行。']],contrasts:[['I read now.','I am reading now.','「今まさに」は進行形が基本。','「現在正在」通常用進行式。']],drillJP:'同じ動詞を現在・過去・未来の進行形にする。',drillTC:'同一動詞改成現在/過去/未來進行。'},
 {id:'temporary-change',title:'Temporary situation / changing trend',level:'A2-B2',explainJP:'進行形は「永久的ではない」「現在の一時的な状況」「変化が進んでいる」ことも示します。live/work/stayなどはsimpleとの対比が重要です。',explainTC:'進行式也表示非永久、目前暫時狀況或持續變化。live/work/stay 等與 simple 的對比很重要。',rulesJP:['I live... = 比較的恒常','I am living... = 一時的','get/become/increase/change など変化動詞と相性がよい'],rulesTC:['I live = 較恆常','I am living = 暫時','get/become/increase/change 常用進行'],examples:[['I am staying with a friend this week.','一時的。','暫時。'],['The system is becoming more stable.','変化中。','正在變化。'],['More companies are using AI.','傾向の進展。','趨勢正在發展。']],contrasts:[['I work from home this week.','I am working from home this week.','一時的期間なら進行形が自然。','暫時期間用進行更自然。']],drillJP:'permanent vs temporaryを表すsimple/progressive対比を5組。',drillTC:'寫5組 simple/progressive 表達永久與暫時差異。'},
 {id:'always-progressive',title:'always + progressive — 反復への感情',level:'B1-C1',explainJP:'always/constantly/forever + progressiveは単純な頻度ではなく、話し手の苛立ち・驚き・称賛など主観的評価を帯びることがあります。',explainTC:'always/constantly/forever + 進行式不只是頻率，也可帶抱怨、驚訝、讚賞等主觀評價。',rulesJP:['simple always = 中立的習慣','progressive always = 感情を帯びやすい','文脈・イントネーションで評価が決まる'],rulesTC:['simple always = 中立習慣','進行 always = 常帶情緒','語境與語調決定評價'],examples:[['He always loses his keys.','中立的頻度。','中立頻率。'],['He is always losing his keys.','「また失くしてる」感。','有「老是這樣」的情緒。'],['She is always helping people.','称賛にもなり得る。','也可表示讚賞。']],contrasts:[['She always helps me.','She is always helping me.','後者は話し手の感情が強い。','後者主觀情緒更強。']],drillJP:'complaintとpraiseのalways progressiveを各3文。',drillTC:'用 always progressive 寫3句抱怨＋3句讚賞。'}]
},
{
 id:'perfect-aspect',level:'A2-C2',domain:'Tense, Aspect & Modality',title:'12 · Perfect Aspect — have + p.p.を「過去形の難しい版」にしない',titleTc:'12 · 完成體 — 不要把 have + p.p. 當成較難的過去式',
 overviewJP:'perfectは「ある基準時より前の出来事を、その基準時と関連づけて見る」アスペクトです。現在完了・過去完了・未来完了は同じ原理で理解できます。',overviewTC:'完成體表示「基準時間之前的事件，並與該基準時間建立關聯」。現在完成、過去完成、未來完成可用同一原理理解。',outcomesJP:['present perfectとpast simpleを選べる','experience/result/continuationを区別する','past/future perfectへ原理を拡張する','perfect progressiveとの差を説明する'],outcomesTC:['選擇現在完成或過去式','區分經驗/結果/持續','延伸到過去/未來完成','解釋完成與完成進行差異'],
 units:[
 {id:'present-perfect-core',title:'Present perfect — 過去と現在をつなぐ',level:'A2-B1',explainJP:'have/has + p.p.は過去の出来事を「現在に関係するもの」として提示します。経験、現在結果、未完了期間、継続など複数の用法があります。',explainTC:'have/has + p.p. 把過去事件呈現為「與現在有關」。可表示經驗、現在結果、未完成期間與持續。',rulesJP:['具体的に終わった過去時点を示さないことが多い','ever/never/already/yet/just とよく使う','today/this weekなど未完了期間とも使える'],rulesTC:['通常不搭已結束的明確過去時間','常搭 ever/never/already/yet/just','可搭 today/this week 等未結束期間'],examples:[['I have visited Kyoto three times.','経験。','經驗。'],['I have lost my key.','今鍵がない結果。','現在仍受影響。'],['I have read two papers today.','todayがまだ続く。','今天尚未結束。']],contrasts:[['I have visited Kyoto last year.','I visited Kyoto last year.','last yearは完結した過去期間。','last year 是已結束過去。']],drillJP:'experience/result/unfinished timeを各3文。',drillTC:'經驗/結果/未完成期間各造3句。'},
 {id:'since-for-continuation',title:'since / for / how long — 継続',level:'A2-B2',explainJP:'現在まで続く状態にはpresent perfectを使います。sinceは開始点、forは期間です。状態動詞ではsimple perfect、活動の継続感を強調するとperfect progressiveが自然です。',explainTC:'持續到現在的狀態常用現在完成。since 表開始點，for 表期間。狀態動詞常用 simple perfect；活動持續常用 perfect progressive。',rulesJP:['since + point','for + duration','How long have you...?'],rulesTC:['since + 起點','for + 時長','How long have you...?'],examples:[['I have lived here since 2022.','開始点。','起點。'],['I have lived here for four years.','期間。','時長。'],['How long have you known her?','knowは状態。','know 是狀態。']],contrasts:[['I live here since 2022.','I have lived here since 2022.','現在までの継続は完了形。','持續至今用完成式。']],drillJP:'since/for/how longを使う継続文を各3文。',drillTC:'用 since/for/how long 各造3句。'},
 {id:'past-perfect',title:'Past perfect — 過去の中のさらに前',level:'B1-C1',explainJP:'had + p.p.は過去の基準時より前の出来事を示します。出来事の順序が文脈で明白なら必ずしも使う必要はありませんが、因果や順序を明確にするのに有効です。',explainTC:'had + p.p. 表示早於某過去基準點的事件。若順序已清楚不一定必須，但可明確因果與先後。',rulesJP:['past reference pointより前','by the time / after / before と共起','物語でbackstoryを示す'],rulesTC:['早於過去基準點','常與 by the time/after/before 使用','故事中表背景前史'],examples:[['When I arrived, the meeting had already started.','到着より前に開始。','到達前已開始。'],['She was tired because she had slept badly.','原因がさらに前。','更早的原因。'],['By 2020, they had developed three prototypes.','2020より前の累積。','截至2020已完成。']],contrasts:[['When I arrived, the meeting started.','When I arrived, the meeting had started.','前者は到着時に開始、後者は到着前に開始。','前者同時，後者更早。']],drillJP:'二つの過去イベントを時系列で5組作り、必要な方にpast perfect。',drillTC:'寫5組兩個過去事件，用 past perfect 標示更早者。'},
 {id:'perfect-progressive',title:'Perfect progressive — 継続活動とその痕跡',level:'B1-C1',explainJP:'have been V-ingは過去から基準時まで続く「活動そのもの・期間・繰り返し」を強調します。simple perfectは完成量・結果を強く見る傾向があります。',explainTC:'have been V-ing 強調從過去持續到基準點的活動、期間或反覆；simple perfect 更常聚焦完成量或結果。',rulesJP:['How long / for / sinceと相性','活動動詞で自然','状態動詞は通常simple perfect'],rulesTC:['常搭 how long/for/since','活動動詞自然','狀態動詞通常 simple perfect'],examples:[['I have been studying for three hours.','活動の継続。','活動持續。'],['I have read three chapters.','完成量。','完成數量。'],['It has been raining.','現在の濡れた結果も示唆。','也暗示現在留下痕跡。']],contrasts:[['I have written emails all morning.','I have been writing emails all morning.','後者は活動継続を強調、前者は成果にも焦点を置ける。','後者強調過程，前者可聚焦成果。']],drillJP:'read/write/work/studyでsimple perfectとperfect progressiveの対比を作る。',drillTC:'用 read/write/work/study 比較 simple perfect 與 perfect progressive。'}]
},
{
 id:'core-modals',level:'A2-C1',domain:'Tense, Aspect & Modality',title:'13 · Core Modals — can / could / may / might / must / should / will / would',titleTc:'13 · 核心情態動詞',
 overviewJP:'助動詞は「可能・義務」の単語置換ではなく、話し手の確信度、権限、丁寧さ、距離感を表すシステムです。',overviewTC:'情態動詞不是單純替換「可能/義務」，而是表示說話者的確信度、權限、禮貌與距離感。',outcomesJP:['ability/permission/possibilityを区別する','must/have to/shouldを使い分ける','could/wouldの心理的距離を理解する'],outcomesTC:['區分能力/許可/可能性','區分 must/have to/should','理解 could/would 的心理距離'],
 units:[
 {id:'can-could',title:'can / could — 能力・許可・可能・距離',level:'A2-B2',explainJP:'canは現在の能力・許可・一般可能性。couldは過去能力だけでなく、より控えめな可能性・依頼にも使われます。',explainTC:'can 表現在能力、許可、一般可能；could 除過去能力外，也表示較保守可能性與較禮貌請求。',rulesJP:['can + base','could = past ability / tentative possibility / polite request','特定の一回成功は was able to が自然な場合'],rulesTC:['can + 原形','could 可過去能力/保守可能/禮貌請求','一次成功常用 was able to'],examples:[['I can swim.','能力。','能力。'],['It could be a hardware issue.','控えめな可能性。','保守可能性。'],['Could you help me?','丁寧依頼。','禮貌請求。']],contrasts:[['Yesterday I could fix the bug.（一回の成功）','Yesterday I was able to fix the bug.','特定の成功はwas able toが自然。','一次成功用 was able to 更自然。']],drillJP:'can/couldを能力・可能性・依頼で各2文。',drillTC:'用 can/could 做能力、可能性、請求各2句。'},
 {id:'may-might',title:'may / might — 可能性と許可の距離',level:'A2-B2',explainJP:'may/mightは可能性を表し、mightはより控えめ・仮定的になることが多いですが、確率を固定的な数字で覚えない方がよいです。mayはフォーマルな許可にも使います。',explainTC:'may/might 表可能性，might 常較保守或假設，但不應硬背固定概率。may 也可表示正式許可。',rulesJP:['may/might + base','mightは距離を置く傾向','May I...? は比較的フォーマル'],rulesTC:['may/might + 原形','might 較有距離感','May I...? 較正式'],examples:[['It may rain later.','可能性。','可能性。'],['This might explain the error.','控えめな仮説。','保守假設。'],['May I come in?','許可。','許可。']],contrasts:[['It might definitely fail.','It might fail. / It will definitely fail.','mightとdefinitelyは意味衝突しやすい。','might 與 definitely 常語意衝突。']],drillJP:'研究仮説をmay/mightで5文。',drillTC:'用 may/might 寫5個研究假設。'},
 {id:'must-have-to-should',title:'must / have to / should — 義務・必要・助言',level:'A2-B2',explainJP:'mustは話し手が強く必要と判断する義務や強い推論、have toは外的事情による必要、shouldは推奨・期待を表すのが基本です。否定形の意味差は特に重要です。',explainTC:'must 常表示說話者認為必要的強義務或強推論；have to 偏外在必要；should 表建議或期待。否定形式差異很重要。',rulesJP:['must not = 禁止','do not have to = 不必要','should not = しない方がよい'],rulesTC:['must not = 禁止','do not have to = 不必','should not = 不建議'],examples:[['You must wear a helmet.','強い義務。','強義務。'],['I have to submit this by Friday.','締切という外的必要。','外在必要。'],['You should back up your files.','助言。','建議。']],contrasts:[['You must not come tomorrow.','You do not have to come tomorrow.','前者は禁止、後者は来る必要がない。','前者禁止，後者不必。']],drillJP:'must not / do not have to / should not の意味差が明確な場面を各3文。',drillTC:'用 must not / do not have to / should not 各造3句。'},
 {id:'will-would-distance',title:'will / would — 意志・習慣・仮定・丁寧さ',level:'B1-C1',explainJP:'wouldは単なるwillの過去形ではありません。仮定、過去習慣、丁寧な依頼・希望、未来から距離を置く表現など多機能です。',explainTC:'would 不只是 will 的過去式，也表示假設、過去習慣、禮貌請求/希望與心理距離。',rulesJP:['Would you...? = 丁寧','would in conditionals','would rather / would like'],rulesTC:['Would you...? 禮貌','條件句中的 would','would rather / would like'],examples:[['Would you open the window?','丁寧依頼。','禮貌請求。'],['I would choose the second option.','仮定的意見。','假設性意見。'],['I would like to ask a question.','丁寧な希望。','禮貌表達希望。']],contrasts:[['I want to ask a question.','I would like to ask a question.','後者は距離を置き丁寧。','後者更有禮貌與距離。']],drillJP:'will/wouldを同じ場面で言い換え、丁寧さ・確実性の差を説明する。',drillTC:'同情境用 will/would 改寫並解釋禮貌/確定度差異。'}]
},
{
 id:'modal-perfects',level:'B1-C2',domain:'Tense, Aspect & Modality',title:'14 · Modal Perfects — must have / might have / should have / could have',titleTc:'14 · 情態完成式 — 對過去推論與評價',
 overviewJP:'modal + have + p.p. は過去の出来事に対する現在の推論・後悔・批判・可能性を表します。上級会話・Writingで非常に重要です。',overviewTC:'modal + have + p.p. 表示對過去事件的現在推論、後悔、批評或可能性，是高階口語與寫作的重要結構。',outcomesJP:['過去推論の確信度を調整する','should have/could haveの反実性を理解する','否定形も正確に使う'],outcomesTC:['調整對過去推論的確信度','理解 should have/could have 的反事實','正確使用否定'],
 units:[
 {id:'past-deduction',title:'must have / may have / might have / cannot have',level:'B1-C1',explainJP:'過去に何が起きたかを証拠から推論するときに使います。must haveは強い確信、may/might/could haveは可能性、cannot/could not haveは強い否定推論です。',explainTC:'根據證據推測過去事件時使用。must have 表強確信，may/might/could have 表可能，cannot/could not have 表強否定推論。',rulesJP:['modal + have + p.p.','must have ≠ 義務の過去','確率を固定数字で覚えない'],rulesTC:['modal + have + p.p.','must have 不是過去義務','不要硬背固定機率'],examples:[['He must have forgotten.','ほぼ確信。','高度確信。'],['The file might have been deleted.','可能性。','可能性。'],['She cannot have seen the message.','見たはずがない。','不可能看到。']],contrasts:[['He must forgot.','He must have forgotten.','過去推論はhave + p.p.。','過去推論用 have + p.p.。']],drillJP:'同じ原因不明のトラブルについてmust/might/cannot haveを各2仮説。',drillTC:'對同一故障用 must/might/cannot have 各寫2個假設。'},
 {id:'should-have',title:'should have / ought to have — 過去への評価・後悔',level:'B1-C1',explainJP:'should have p.p. は「実際にはそうしなかったが、そうするのが望ましかった」という過去への評価です。should not haveは「してしまったが、しない方がよかった」。',explainTC:'should have p.p. 表示實際沒做但本來應該做；should not have 表示做了但本來不該做。',rulesJP:['反実的評価を含むことが多い','advice after the fact','ought to haveも近いがややフォーマル'],rulesTC:['常含反事實評價','事後建議/後悔','ought to have 較正式'],examples:[['I should have studied more.','実際は十分しなかった。','實際沒充分讀。'],['You should not have sent that email.','送ってしまった。','實際寄了。'],['We ought to have tested it earlier.','より早く試すべきだった。','本應更早測試。']],contrasts:[['I should study more.','I should have studied more.','現在/未来の助言 vs 過去への後悔。','現在建議 vs 過去後悔。']],drillJP:'最近の失敗をshould have/should not haveで5文。',drillTC:'用 should have/should not have 寫5句最近的失誤反思。'},
 {id:'could-have',title:'could have / would have — 実現しなかった可能性',level:'B2-C2',explainJP:'could have p.p. は「可能だったが実現しなかった」や過去可能性、would have p.p. は条件が違えば起きた結果を表します。文脈によりcould haveが単なる推測になることにも注意します。',explainTC:'could have p.p. 可表示「本來可以但沒實現」或過去可能性；would have p.p. 表示若條件不同本會發生的結果。',rulesJP:['could have = unrealized option / possibility','would have = hypothetical result','if + past perfect とよく組む'],rulesTC:['could have = 未實現選項/可能性','would have = 假設結果','常與 if + past perfect 搭配'],examples:[['I could have taken the train, but I drove.','選択可能だった。','本可選火車但沒選。'],['I would have helped if I had known.','条件が満たされなかった。','條件未滿足。'],['The error could have come from the sensor.','過去可能性。','過去可能性。']],contrasts:[['If I knew, I would have helped.','If I had known, I would have helped.','過去の反実条件はpast perfect。','過去反事實條件用 past perfect。']],drillJP:'unrealized optionとthird conditionalを各3文。',drillTC:'未實現選項與第三條件句各造3句。'}]
},
{
 id:'questions-negation',level:'A1-C1',domain:'Interaction Grammar',title:'15 · Questions & Negation — 疑問・否定・間接疑問を体系化',titleTc:'15 · 疑問與否定 — 系統化問句、否定、間接問句',
 overviewJP:'英語の疑問文は「主語と動詞を逆にする」ではなく、最初の助動詞を主語の前に出す仕組みとして理解すると一貫します。否定も助動詞の後ろにnotを置くのが基本です。',overviewTC:'英文問句與其背「主詞動詞倒裝」，不如理解為把第一個助動詞移到主詞前。否定基本把 not 放在助動詞後。',outcomesJP:['yes/noとWH疑問を作れる','subject questionを区別する','embedded questionを正しい語順にする','negative questionの含意を理解する'],outcomesTC:['製作 yes/no 與 WH 問句','區分主詞問句','正確使用間接問句語序','理解否定疑問的含意'],
 units:[
 {id:'yes-no',title:'Yes/No questions — auxiliary inversion',level:'A1',explainJP:'beや助動詞がある場合はそれを主語の前へ出します。一般動詞しかない場合はdo/does/didを補います。',explainTC:'已有 be 或助動詞時移到主詞前；只有一般動詞時補 do/does/did。',rulesJP:['Are you...? / Can you...?','Do you...?','完了: Have you...?'],rulesTC:['Are/Can + S','Do/Does/Did + S + V','完成：Have + S + p.p.'],examples:[['Are you ready?','be inversion。','be 倒裝。'],['Do you understand?','do-support。','do-support。'],['Have you finished?','have inversion。','have 倒裝。']],contrasts:[['Do you are ready?','Are you ready?','be文にdo不要。','be 句不需要 do。']],drillJP:'be/general/modal/perfectの4種類で疑問文を各3つ。',drillTC:'be/一般動詞/modal/完成各造3個問句。'},
 {id:'wh-questions',title:'WH questions — 何を聞いているかで構造が変わる',level:'A1-B2',explainJP:'WH語が目的語・補語・副詞の場合は通常WH + auxiliary + S + Vですが、WH語自体が主語ならdo-supportや倒置は起きません。',explainTC:'WH 詞若作受詞/補語/副詞，通常 WH + 助動詞 + S + V；若 WH 本身是主詞，則不用 do-support 或倒裝。',rulesJP:['What did you buy?','Who called you? = subject question','How long / how often / how much など複合WH'],rulesTC:['What did you buy?','Who called you? 主詞問句','how long/how often/how much 等'],examples:[['Why did you choose this method?','why + did。','why + did。'],['Who designed this system?','whoが主語。','who 是主詞。'],['How long have you lived here?','duration question。','問持續時間。']],contrasts:[['Who did call you?','Who called you?','中立的subject questionではdo不要。','一般主詞問句不用 do。']],drillJP:'目的語WH 5文＋主語WH 5文。',drillTC:'受詞WH 5句＋主詞WH 5句。'},
 {id:'embedded-questions',title:'Embedded questions — 丁寧に聞くと語順は平叙文',level:'A2-B2',explainJP:'Could you tell me...? / Do you know...? の中に質問を埋め込むと、内部は疑問語順ではなく平叙文語順になります。yes/no型はif/whetherを使います。',explainTC:'把問句嵌入 Could you tell me...? / Do you know...? 後，內部使用陳述語序。yes/no 型用 if/whether。',rulesJP:['WH + S + V','if/whether + S + V','内部でdo-supportしない'],rulesTC:['WH + S + V','if/whether + S + V','內部不用 do-support'],examples:[['Do you know where he is?','where + he + is。','where + he + is。'],['Could you tell me when the store closes?','closesが内部動詞。','內部用 closes。'],['I wonder whether she received it.','yes/no埋め込み。','yes/no 間接問句。']],contrasts:[['Do you know where is he?','Do you know where he is?','embedded questionは平叙文語順。','間接問句用陳述語序。']],drillJP:'直接疑問10個をembedded questionに変換。',drillTC:'把10個直接問句改成間接問句。'},
 {id:'negative-questions',title:'Negative questions — 驚き・確認・期待',level:'B1-C1',explainJP:"Don't you...? / Isn't it...? は単なる否定疑問ではなく、話し手が肯定を期待している、驚いている、確認したい等の含意を持ちます。答えのYes/Noは事実に合わせます。",explainTC:'Don\'t you...? / Isn\'t it...? 常表示預期肯定、驚訝或確認。Yes/No 依事實回答。',rulesJP:['Aren’t you coming? = 来ると思っていた','Didn’t you know? = 知っていると思った','Yes = 肯定命題が真、No = 否定命題が真'],rulesTC:['Aren’t you coming? 有原本以為會來的含意','Didn’t you know? 表驚訝','Yes/No 依事實真假'],examples:[['Aren’t you tired?','疲れていると思う/確認。','預期對方累。'],['Didn’t she tell you?','伝えたと思っていた驚き。','以為她有告訴你。'],['Don’t you agree?','同意を期待。','期待對方同意。']],contrasts:[['Don’t you like coffee? — Yes, I don’t.','Don’t you like coffee? — No, I don’t.','英語のYes/Noは後続命題に合わせる。','英文 Yes/No 跟後面命題一致。']],drillJP:'驚き・確認・肯定期待のnegative questionを各2文。',drillTC:'用否定疑問表示驚訝、確認、期待肯定各2句。'}]
}
);