window.grammarChapters = window.grammarChapters || [];
window.grammarChapters.push(
{
 id:'adjectives-adverbs',level:'A1-C1',domain:'Modification & Comparison',title:'16 · Adjectives & Adverbs — 何を修飾するかで形と位置が変わる',titleTc:'16 · 形容詞與副詞 — 依修飾對象決定形式與位置',
 overviewJP:'形容詞は名詞や補語として人・物の性質を、adverbは動詞・形容詞・他の副詞・文全体を修飾します。語順、-ly、gradable/non-gradable、sentence adverbsまで整理します。',overviewTC:'形容詞修飾名詞或作補語；副詞可修飾動詞、形容詞、其他副詞或整句。本章整理語序、-ly、程度與句副詞。',
 outcomesJP:['adjective/adverbを役割で選ぶ','副詞位置を意味に応じて決める','gradable/non-gradableに合うdegree adverbを使う'],outcomesTC:['依角色選形容詞/副詞','依意思決定副詞位置','搭配可分級/不可分級形容詞'],
 units:[
 {id:'adj-vs-adv',title:'Adjective vs adverb — good / well, careful / carefully',level:'A1-B1',explainJP:'形容詞は名詞を修飾したりbe/seem/look/feelなどの補語になります。副詞は動作の仕方などを説明します。ただし fast/hard/late のように -ly なしで副詞になる語もあります。',explainTC:'形容詞修飾名詞或作 be/seem/look/feel 等補語；副詞說明動作方式。但 fast/hard/late 等副詞不一定有 -ly。',rulesJP:['linking verbの後ろは形容詞が基本','一般動詞の仕方は副詞','-ly = 副詞と機械的に決めない'],rulesTC:['連綴動詞後通常形容詞','一般動詞方式常用副詞','不要把 -ly 機械等同副詞'],examples:[['She looks tired.','lookはlinking verb。','look 是連綴動詞。'],['She worked carefully.','workedを修飾。','修飾 worked。'],['He runs fast.','fastは副詞でも同形。','fast 作副詞仍同形。']],contrasts:[['The system works good.','The system works well.','worksを修飾するのでwell。','修飾 works 用 well。']],drillJP:'look/feel/sound/work/runを使いadjective/adverb対比を5組。',drillTC:'用 look/feel/sound/work/run 寫5組形容詞/副詞對比。'},
 {id:'adverb-position',title:'Adverb position — frequency / manner / sentence adverb',level:'A2-B2',explainJP:'副詞は種類によって自然な位置が違います。頻度副詞は一般動詞の前・beの後、mannerは目的語の後ろが多く、fortunately/probablyなどは文全体への態度を示します。',explainTC:'不同副詞有不同自然位置。頻率副詞多在一般動詞前、be 後；方式副詞常在受詞後；fortunately/probably 等可修飾整句。',rulesJP:['I usually work... / I am usually...','S + V + O + carefully が基本','sentence adverbは文頭・助動詞周辺など'],rulesTC:['usually：一般動詞前、be 後','方式副詞常在 V+O 後','句副詞可在句首或助動詞附近'],examples:[['I usually study at night.','頻度。','頻率。'],['She explained the problem clearly.','manner。','方式。'],['Fortunately, nobody was hurt.','文全体への評価。','對整句的評價。']],contrasts:[['She carefully explained me the problem.','She carefully explained the problem to me.','副詞位置以前にexplainの構文にも注意。','除了副詞位置，也要注意 explain 句型。']],drillJP:'usually/carefully/probably/fortunately/almostを使う文を各2つ。',drillTC:'用 usually/carefully/probably/fortunately/almost 各造2句。'},
 {id:'gradable',title:'very / absolutely / completely — 程度と形容詞の相性',level:'B1-C1',explainJP:'hot/importantのようなgradable adjectiveはvery/quite/extremelyと結びつきやすく、impossible/exhausted/perfectのような極端・絶対的形容詞にはabsolutely/completelyなどが自然です。',explainTC:'hot/important 等可分級形容詞常搭 very/quite/extremely；impossible/exhausted/perfect 等極端形容詞常搭 absolutely/completely。',rulesJP:['very hot / extremely useful','absolutely impossible / completely exhausted','really は両方で広く使える'],rulesTC:['very hot / extremely useful','absolutely impossible / completely exhausted','really 兩類都常用'],examples:[['The result is extremely important.','gradable。','可分級。'],['That is absolutely impossible.','extreme。','極端。'],['I am completely exhausted.','限界状態。','極限狀態。']],contrasts:[['very impossible','absolutely impossible','impossibleは通常veryと相性が悪い。','impossible 通常不搭 very。']],drillJP:'gradable 5語、extreme 5語を選び適切なdegree adverbと組み合わせる。',drillTC:'選5個可分級與5個極端形容詞，搭配適當程度副詞。'}]
},
{
 id:'comparison',level:'A1-C1',domain:'Modification & Comparison',title:'17 · Comparison & Degree — 比較級だけでなく「差の大きさ」まで表す',titleTc:'17 · 比較與程度 — 不只比較級，也表達差距大小',
 overviewJP:'比較表現には-er/more、最上級、as...as、less、倍数、比較級強調、the more... the more...などがあります。比較対象の論理的一致も重要です。',overviewTC:'比較包含 -er/more、最高級、as...as、less、倍數、比較級強調、the more... the more...，也要注意比較對象邏輯一致。',
 outcomesJP:['比較級・最上級を形成できる','as/less/倍数表現を使える','比較対象の不整合を修正できる'],outcomesTC:['形成比較級/最高級','使用 as/less/倍數','修正不合理比較對象'],
 units:[
 {id:'comparative-superlative',title:'Comparative / superlative — 形と不規則',level:'A1-A2',explainJP:'短い形容詞は-er/-est、長い形容詞はmore/mostが基本ですが、good-better-best, bad-worse-worstなど不規則もあります。thanの後ろは比較対象が明確である必要があります。',explainTC:'短形容詞常用 -er/-est，長形容詞用 more/most；good-better-best、bad-worse-worst 等不規則。than 後比較對象需清楚。',rulesJP:['small-smaller-smallest','useful-more useful-most useful','better/best, worse/worst, farther/further'],rulesTC:['small-smaller-smallest','useful-more/most useful','不規則 better/best 等'],examples:[['This model is faster than the old one.','比較級。','比較級。'],['This is the most reliable version.','最上級。','最高級。'],['The result was better than expected.','不規則better。','不規則 better。']],contrasts:[['more easier','easier','二重比較にしない。','不要雙重比較。']],drillJP:'短形容詞5、長形容詞5、不規則3で比較文。',drillTC:'用5短、5長、3不規則形容詞造比較句。'},
 {id:'as-less',title:'as...as / not as...as / less',level:'A2-B1',explainJP:'as + adjective/adverb + as は同程度、not as...asは劣る比較を柔らかく表せます。lessは不可算量だけでなく形容詞・副詞の程度比較にも使えます。',explainTC:'as...as 表同程度；not as...as 可較委婉表示較差；less 也可修飾形容詞/副詞表示程度較低。',rulesJP:['as fast as','not as expensive as','less reliable than'],rulesTC:['as fast as','not as expensive as','less reliable than'],examples:[['This approach is as accurate as the baseline.','同程度。','同程度。'],['The new motor is not as heavy as the old one.','軽いことを間接表現。','間接表達較輕。'],['This option is less expensive.','程度が低い。','程度較低。']],contrasts:[['as faster as','as fast as','asの間は原級。','as 中間用原級。']],drillJP:'as...as / not as...as / less...than を各3文。',drillTC:'三種結構各造3句。'},
 {id:'degree-difference',title:'much / far / slightly / a little + comparative',level:'B1-C1',explainJP:'比較級の差の大きさをmuch/far/a lot（大差）、slightly/a little/a bit（小差）で示せます。very betterではなくmuch betterです。',explainTC:'比較級可用 much/far/a lot 表大差，用 slightly/a little/a bit 表小差。不是 very better，而是 much better。',rulesJP:['much/far/a lot + comparative','slightly/a little/a bit + comparative','by + amount で差を数値化'],rulesTC:['much/far/a lot + 比較級','slightly/a little/a bit + 比較級','by + 數值表示差距'],examples:[['The new version is much faster.','大差。','大幅更快。'],['Accuracy is slightly higher.','小差。','稍高。'],['It is faster by 20 percent.','数値差。','快20%。']],contrasts:[['very faster','much faster','比較級の強調にveryは通常使わない。','比較級通常不用 very 強調。']],drillJP:'同じ比較をlarge/small/numeric differenceの3種類で表現。',drillTC:'同一比較分別用大差、小差、數值差表達。'},
 {id:'advanced-comparison',title:'the more..., the more... / twice as... / no more than',level:'B2-C1',explainJP:'上級比較には相関比較、倍数、限定的比較表現があります。no more thanとnot more thanでは話し手の評価が異なる場合があります。',explainTC:'高階比較包含相關比較、倍數與限制比較。no more than 與 not more than 有時帶不同評價。',rulesJP:['The more X, the more Y','twice/three times as + adj + as','no more than = only の含意を持つことがある'],rulesTC:['The more X, the more Y','twice/three times as...as','no more than 有「僅僅」含意'],examples:[['The more data we collect, the better the model becomes.','相関。','相關比較。'],['This sensor is twice as expensive as that one.','倍数。','倍數。'],['It took no more than ten minutes.','わずか10分。','不過10分鐘。']],contrasts:[['twice more expensive than','twice as expensive as','標準的にはtwice as...asが安全。','標準用法以 twice as...as 最穩妥。']],drillJP:'the more構文3文＋倍数比較3文。',drillTC:'the more 結構3句＋倍數比較3句。'}]
},
{
 id:'prepositions',level:'A1-C1',domain:'Modification & Comparison',title:'18 · Prepositions — 日本語訳で覚えず「関係」を捉える',titleTc:'18 · 介系詞 — 不靠直譯，而理解關係',
 overviewJP:'at/in/on、to/for、by/withなどは一対一の日本語訳では習得できません。空間・時間の概念と、動詞/形容詞/名詞とのcollocationを分けて学びます。',overviewTC:'at/in/on、to/for、by/with 無法靠一對一翻譯掌握。要分成空間/時間概念與動詞、形容詞、名詞搭配來學。',
 outcomesJP:['at/in/onの空間・時間モデルを使う','to/for/by/withの関係を区別する','prepositional collocationを塊で覚える'],outcomesTC:['掌握 at/in/on 空間時間模型','區分 to/for/by/with','以搭配記介系詞'],
 units:[
 {id:'at-in-on-place',title:'at / in / on for place — 点・内部・面',level:'A1-A2',explainJP:'基本イメージは at=点、in=境界の内部、on=表面・線上です。ただし交通機関・住所・施設など慣用パターンもあります。',explainTC:'基本概念是 at=點、in=邊界內部、on=表面/線上，但交通、地址、設施等也有慣用模式。',rulesJP:['at the station / at home','in Tokyo / in a room / in a car','on the table / on a train / on the wall'],rulesTC:['at 表點','in 表內部','on 表表面或大型交通工具'],examples:[['Meet me at the station.','地点として。','作為地點。'],['I live in Tokyo.','都市内部。','城市內。'],['The diagram is on the wall.','表面。','表面。']],contrasts:[['in the train','on the train','公共交通はonが一般的。','公共交通一般用 on。']],drillJP:'家から学校までの移動をat/in/onを使って8文。',drillTC:'用 at/in/on 寫8句從家到學校的路線。'},
 {id:'at-in-on-time',title:'at / on / in for time — 時刻・日・期間',level:'A1-A2',explainJP:'atは時刻・一点、onは日・日付、inは月・年・季節・長い期間が基本です。nightはat night、morningはin the morningなど固定表現もあります。',explainTC:'at 用時間點；on 用日期/星期；in 用月份、年份、季節與較長期間。也有 at night / in the morning 等固定搭配。',rulesJP:['at 7 / at noon / at night','on Monday / on August 17','in 2026 / in summer / in the morning'],rulesTC:['at 時刻','on 日期/星期','in 年月季節'],examples:[['The class starts at nine.','時刻。','時間點。'],['I will see you on Friday.','曜日。','星期。'],['I moved here in 2022.','年。','年份。']],contrasts:[['in Monday','on Monday','曜日はon。','星期用 on。']],drillJP:'1日の予定＋1年の予定をat/on/inで書く。',drillTC:'用 at/on/in 寫一天與一年行程。'},
 {id:'to-for',title:'to vs for — 到達点と目的・受益',level:'A2-B1',explainJP:'toは方向・到達点・受け手、forは目的・利益・交換・期間などを表すのが基本です。ただし動詞ごとのcollocationも重要です。',explainTC:'to 基本表示方向、到達點、接受者；for 常表示目的、利益、交換、期間，但也需學動詞搭配。',rulesJP:['give/send/explain X to someone','buy/make/do X for someone','for + duration'],rulesTC:['to 表接受者/方向','for 表受益/目的','for + 持續時間'],examples:[['I sent the file to my professor.','受け手。','接受者。'],['I made dinner for my friend.','受益者。','受益者。'],['I studied for two hours.','期間。','期間。']],contrasts:[['I explained the problem for him.','I explained the problem to him.','explainの受け手はto。','explain 接受者用 to。']],drillJP:'give/send/explain/buy/makeのto/forパターンを例文化。',drillTC:'用 give/send/explain/buy/make 練 to/for。'},
 {id:'collocations',title:'Verb / adjective / noun + preposition collocations',level:'B1-C1',explainJP:'depend on, interested in, responsible for, reason for, solution to のような前置詞は意味だけで完全予測できません。語彙の一部として塊で覚えます。',explainTC:'depend on、interested in、responsible for、reason for、solution to 等無法完全從意思預測，要作為搭配整塊記憶。',rulesJP:['verb + prep を1語として覚える','adjective + prep','noun + prep はTOEIC/Writingでも重要'],rulesTC:['動詞+介系詞整塊記','形容詞+介系詞','名詞+介系詞對考試/寫作重要'],examples:[['It depends on the data.','depend on。','depend on。'],['I am interested in robotics.','interested in。','interested in。'],['We need a solution to this problem.','solution to。','solution to。']],contrasts:[['discuss about the issue','discuss the issue','すべての意味関係に前置詞が必要とは限らない。','不是所有語意關係都需要介系詞。']],drillJP:'自分用preposition notebookを作りverb/adjective/noun各15 collocations。',drillTC:'建立介系詞筆記，動詞/形容詞/名詞搭配各15個。'}]
},
{
 id:'infinitives-gerunds',level:'A2-C1',domain:'Verb Patterns & Voice',title:'19 · Infinitives & Gerunds — to do / doing を意味と動詞パターンで選ぶ',titleTc:'19 · 不定詞與動名詞 — 依語意與動詞句型選 to do / doing',
 overviewJP:'to不定詞と動名詞は「未来/過去」という単純ルールでは説明できません。各動詞のcomplement patternと、形を変えると意味が変わる動詞を体系的に学びます。',overviewTC:'to 不定詞與動名詞不能只用「未來/過去」解釋。要學各動詞的補語模式，以及形式改變時意思也改變的動詞。',
 outcomesJP:['verb + to / -ing の主要群を使える','remember/stop/try/regretの意味差を説明できる','目的・結果・評価のto不定詞を使える'],outcomesTC:['掌握 verb+to / -ing 主要群','解釋 remember/stop/try/regret 意義差','使用表示目的/結果/評價的不定詞'],
 units:[
 {id:'verb-to',title:'Verb + to-infinitive — want, decide, plan, hope...',level:'A2-B1',explainJP:'want/decide/plan/hope/expect/agree/refuse/manageなどはto不定詞を補語に取ります。動詞ごとのパターンとして覚えるのが安全です。',explainTC:'want/decide/plan/hope/expect/agree/refuse/manage 等接 to 不定詞，最好作為動詞句型記憶。',rulesJP:['verb + to + base','否定は not to do','目的語 + to do を取る動詞は別パターン'],rulesTC:['動詞 + to + 原形','否定 not to do','動詞 + 受詞 + to do 是另一模式'],examples:[['I decided to apply.','decide + to。','decide + to。'],['She refused to answer.','refuse + to。','refuse + to。'],['We managed to solve it.','成功含意。','manage 暗示成功。']],contrasts:[['I decided applying.','I decided to apply.','decideはtoを取る。','decide 接 to。']],drillJP:'want/decide/plan/hope/manage/refuseで各1文。',drillTC:'六個動詞各造1句。'},
 {id:'verb-ing',title:'Verb + -ing — enjoy, avoid, finish, consider...',level:'A2-B1',explainJP:'enjoy/avoid/finish/consider/suggest/mind/keepなどは-ingを取ります。suggestはsuggest doing / suggest that...であり、通常suggest someone to doとはしません。',explainTC:'enjoy/avoid/finish/consider/suggest/mind/keep 等接 -ing。suggest 常用 suggest doing / suggest that，不用 suggest someone to do。',rulesJP:['verb + gerund','prepositionの後ろも-ing','mind + possessive/object + -ing など'],rulesTC:['動詞 + 動名詞','介系詞後也用 -ing','mind 等可接人 + -ing'],examples:[['I enjoy learning English.','enjoy + ing。','enjoy + ing。'],['We considered changing the design.','consider + ing。','consider + ing。'],['She suggested taking a break.','suggest + ing。','suggest + ing。']],contrasts:[['She suggested me to take a break.','She suggested that I take a break.','suggestの代表的誤用。','suggest 常見錯誤。']],drillJP:'enjoy/avoid/finish/consider/suggest/mindで例文。',drillTC:'六個 -ing 動詞各造句。'},
 {id:'meaning-change',title:'remember / forget / stop / try / regret — 形で意味が変わる',level:'B1-C1',explainJP:'同じ動詞でもto不定詞と-ingで意味が変わります。これは上級文法・会話で重要で、単純な未来/過去ルールより個別意味を理解する必要があります。',explainTC:'同一動詞接 to 或 -ing 時意思可改變。這是重要高階文法，需理解個別語意。',rulesJP:['remember to do=することを忘れない / remember doing=した記憶','stop to do=〜するため止まる / stop doing=〜するのをやめる','try to do=努力 / try doing=試しに'],rulesTC:['remember to 做記得要做；remember doing 記得做過','stop to 為了做而停；stop doing 停止做','try to 努力；try doing 試試看'],examples:[['Remember to lock the door.','これからする。','記得去做。'],['I remember locking the door.','した記憶。','記得做過。'],['Try restarting the computer.','方法として試す。','試試重啟。']],contrasts:[['I stopped to smoke.','I stopped smoking.','前者=吸うため立ち止まった、後者=禁煙した。','前者為抽菸而停，後者停止抽菸。']],drillJP:'remember/stop/try/regretをto/-ing両方で8対作る。',drillTC:'四個動詞各做 to/-ing 對比，共8組。'},
 {id:'infinitive-functions',title:'Purpose / adjective + infinitive / too...to / enough to',level:'A2-B2',explainJP:'to不定詞は動詞補語だけでなく目的、形容詞の補足、結果・可能性の構文にも使います。',explainTC:'to 不定詞不只作動詞補語，也可表示目的、補足形容詞、結果與可能性。',rulesJP:['to do = purpose','easy/difficult/ready/happy to do','too adj to / adj enough to'],rulesTC:['to do 表目的','形容詞 + to do','too...to / enough to'],examples:[['I went out to buy coffee.','目的。','目的。'],['This tool is easy to use.','形容詞の補足。','補充形容詞。'],['The box is too heavy to lift.','不可能結果。','太重無法抬。']],contrasts:[['I went out for buy coffee.','I went out to buy coffee.','目的の動詞はto-infinitive。','動作目的用 to 不定詞。']],drillJP:'目的・形容詞補足・too/enoughを各3文。',drillTC:'目的、形容詞補語、too/enough 各造3句。'}]
},
{
 id:'participles',level:'A2-C1',domain:'Verb Patterns & Voice',title:'20 · Participles — -ing / -ed を形容詞・圧縮表現として使う',titleTc:'20 · 分詞 — 用 -ing / -ed 作形容詞與壓縮表達',
 overviewJP:'現在分詞・過去分詞は進行/受動を作るだけでなく、名詞修飾や補語として使われます。boring/boredのような感情形容詞、後置修飾、分詞句までつながります。',overviewTC:'現在分詞/過去分詞不只形成進行與被動，也能修飾名詞或作補語，包含 boring/bored、後置修飾與分詞片語。',outcomesJP:['-ing/-ed形容詞を意味で選ぶ','分詞の前置/後置修飾を使う','縮約関係節との関係を理解する'],outcomesTC:['依意思選 -ing/-ed 形容詞','使用分詞前/後置修飾','理解與縮減關係子句關係'],
 units:[
 {id:'emotion-adjectives',title:'boring vs bored — 原因側と経験者側',level:'A2-B1',explainJP:'-ing形容詞は感情を引き起こす性質、-ed形容詞はその感情を経験している状態を表すのが基本です。interesting/interested, confusing/confusedなど同じ原理です。',explainTC:'-ing 形容詞通常表示引發感受的性質，-ed 表示感受到該情緒的狀態。',rulesJP:['thing/situation is boring','person is bored','exciting/excited, tiring/tired, confusing/confused'],rulesTC:['事物令人…用 -ing','人感到…用 -ed','其他同類配對'],examples:[['The lecture was interesting.','講義が興味を起こす。','講座令人有興趣。'],['I was interested in the topic.','私は興味を感じる。','我感到有興趣。'],['The instructions were confusing.','説明が混乱を起こす。','說明令人困惑。']],contrasts:[['I am boring.（退屈している意味）','I am bored.','boringだと「人を退屈させる人」。','boring 變成「令人無聊的人」。']],drillJP:'5組の-ing/-ed emotion adjectivesで対比例。',drillTC:'選5組 -ing/-ed 情緒形容詞做對比。'},
 {id:'participle-modifiers',title:'a broken motor / students working in the lab',level:'A2-B2',explainJP:'分詞は名詞を前後から修飾できます。短い単語的修飾は前、目的語や副詞を伴う長い分詞句は後ろに置かれることが多いです。',explainTC:'分詞可前後修飾名詞。短的詞彙式修飾多在前，帶受詞/副詞的長分詞片語常在後。',rulesJP:['a broken sensor','the running motor','data collected yesterday / students working nearby'],rulesTC:['前置短修飾','後置較長分詞片語','-ing 多主動、-ed 多被動/結果'],examples:[['We replaced the damaged cable.','過去分詞前置。','過去分詞前置。'],['Students working in the lab must wear badges.','後置-ing。','後置 -ing。'],['Data collected yesterday was incomplete.','後置-ed。','後置 -ed。']],contrasts:[['the collected yesterday data','the data collected yesterday','長い分詞句は後置が自然。','長分詞片語後置。']],drillJP:'前置分詞5例＋後置分詞5例。',drillTC:'前置5例＋後置5例。'},
 {id:'perfect-participle',title:'having done / having been done — 時間関係を圧縮',level:'B2-C1',explainJP:'having + p.p. は主節より前に完了した出来事を分詞句で示します。having been + p.p.なら受動完了です。主語共有が必要です。',explainTC:'having + p.p. 用分詞句表示早於主句完成的事件；having been + p.p. 是被動完成。必須與主句共享邏輯主詞。',rulesJP:['Having finished..., S + V','Having been told..., S + V','dangling participleに注意'],rulesTC:['Having finished...','Having been told...','注意懸垂分詞'],examples:[['Having finished the test, I went home.','テスト完了後。','完成測試後。'],['Having been warned, they proceeded carefully.','警告された後。','被警告後。'],['Having worked there for years, she knew the system well.','長期経験が理由/背景。','長期經驗作背景。']],contrasts:[['Having finished the report, the computer crashed.','Having finished the report, I shut down the computer.','前者はcomputerがreportをfinishしたように読める。','前者邏輯主詞錯誤。']],drillJP:'having done 3文＋having been done 2文。',drillTC:'having done 3句＋having been done 2句。'}]
},
{
 id:'passive-causative',level:'A2-C1',domain:'Verb Patterns & Voice',title:'21 · Passive & Causative — 情報の焦点と「してもらう」',titleTc:'21 · 被動與使役 — 控制焦點與「請人做」',
 overviewJP:'受動態は能動態の書き換え問題ではなく、何を話題に置くかを制御する選択です。get passive、modal passive、have/get something done、make/let/have/getの使役も扱います。',overviewTC:'被動不是機械改寫主動，而是控制資訊焦點。也學 get passive、情態被動、have/get something done 與 make/let/have/get 使役。',outcomesJP:['受動を情報構造から選ぶ','by-agentの要否を判断する','causative patternsを使い分ける'],outcomesTC:['依資訊結構選被動','判斷是否需要 by-agent','區分使役句型'],
 units:[
 {id:'basic-passive',title:'be + p.p. — 対象を話題にする',level:'A2-B1',explainJP:'行為者が不明・自明・重要でない、または対象を話題として先に置きたいときに受動が自然です。研究・技術文書ではprocessやdataを主語にするため頻出します。',explainTC:'施事者未知、明顯、不重要，或想把受影響對象放在主題位置時使用被動。研究/技術文常把 process/data 作主詞。',rulesJP:['beの時制 + p.p.','by-agentは必要時のみ','自動詞は通常受動不可'],rulesTC:['be 帶時態 + 過去分詞','by-agent 只在需要時','不及物動詞通常不能被動'],examples:[['The samples were collected in July.','processを主題。','流程作主題。'],['The file was deleted accidentally.','行為者不重要。','施事者不重要。'],['English is spoken worldwide.','一般的行為者。','一般施事者。']],contrasts:[['He was happened to...','It happened to him.','happenは自動詞。','happen 不及物，不能被動。']],drillJP:'能動文10文のうち、受動にする意味があるものだけ選んで変換。',drillTC:'從10個主動句挑適合被動者再改寫。'},
 {id:'advanced-passive',title:'get passive / modal passive / passive infinitive',level:'B1-C1',explainJP:'get + p.p. は出来事性や口語感を強め、特に望ましくない/予期しない出来事に多い傾向があります。modal + be + p.p.、to be p.p.も重要です。',explainTC:'get + p.p. 常更口語、強調事件發生，尤其意外或不利事件。也需掌握 modal + be + p.p. 與 to be p.p.。',rulesJP:['get hurt / get caught / get promoted','must be submitted','needs to be checked'],rulesTC:['get + p.p. 常表事件','modal + be + p.p.','to be + p.p.'],examples:[['My bike got stolen.','出来事性。','事件感。'],['The form must be submitted by Friday.','modal passive。','情態被動。'],['The system needs to be updated.','passive infinitive。','被動不定詞。']],contrasts:[['The file must submitted.','The file must be submitted.','modal passiveにはbeが必要。','情態被動需要 be。']],drillJP:'get passive/modal passive/passive infinitiveを各3文。',drillTC:'三種被動各造3句。'},
 {id:'have-get-done',title:'have / get something done — 他者にしてもらう・被害',level:'B1-C1',explainJP:'have/get + object + p.p. は、サービスを依頼して何かをしてもらう、または望ましくない出来事を経験する意味があります。自分で行ったとは限りません。',explainTC:'have/get + 受詞 + 過去分詞 表示請別人處理，或經歷不利事件，不代表自己親手做。',rulesJP:['have my hair cut','get my laptop repaired','have my wallet stolen = 被害経験'],rulesTC:['請人剪髮','請人修電腦','遭遇錢包被偷'],examples:[['I had my laptop repaired.','業者に修理。','請人維修。'],['She got her hair cut.','美容サービス。','剪髮服務。'],['He had his phone stolen.','被害。','遭竊。']],contrasts:[['I repaired my laptop.','I had my laptop repaired.','前者は自分で修理、後者は他者に依頼。','前者自己修，後者請人修。']],drillJP:'サービス3例＋被害経験2例をhave/get doneで。',drillTC:'服務3例＋不利事件2例。'},
 {id:'causatives',title:'make / let / have / get + person — 使役の強さと構文',level:'B1-C1',explainJP:'make O doは強制・原因、let O doは許可、have O doは手配、get O to doは説得・働きかけという違いがあります。形もmake/let/haveはbare infinitive、getはto-infinitiveです。',explainTC:'make O do 表強制/造成；let O do 許可；have O do 安排；get O to do 說服/促使。make/let/have 接原形，get 接 to。',rulesJP:['make/let/have + O + base','get + O + to do','passive of make: be made to do'],rulesTC:['make/let/have + O + 原形','get + O + to do','make 被動：be made to do'],examples:[['The teacher made us rewrite it.','強制。','要求/強制。'],['They let me leave early.','許可。','允許。'],['I got him to check the code.','働きかけ。','說服/促使。']],contrasts:[['She made me to wait.','She made me wait.','active makeの後ろはbare infinitive。','主動 make 後不用 to。']],drillJP:'make/let/have/getを同じ場面で4文作りニュアンス比較。',drillTC:'同一情境用四種使役造句並比較。'}]
},
{
 id:'phrasal-verbs',level:'A2-C1',domain:'Verb Patterns & Voice',title:'22 · Phrasal & Multi-word Verbs — particleまで含めて1つの動詞として学ぶ',titleTc:'22 · 片語動詞與多字動詞',
 overviewJP:'give up, find out, look after, put up withのようなmulti-word verbは会話・TOEIC・自然なWritingで不可欠です。separable/inseparable、代名詞位置、formal synonymまで扱います。',overviewTC:'give up、find out、look after、put up with 等多字動詞對口語、TOEIC、自然寫作很重要。本章學可分/不可分、代名詞位置與正式同義詞。',outcomesJP:['particleの意味を捉える','separable/inseparableを区別する','代名詞の位置を正しくする','registerでsingle-word synonymと使い分ける'],outcomesTC:['理解 particle 意義','區分可分/不可分','正確放代名詞','依語域換正式單字'],
 units:[
 {id:'separable',title:'Separable phrasal verbs — turn it off',level:'A2-B1',explainJP:'turn off, pick up, put onなどは目的語を動詞とparticleの間に置けます。目的語が代名詞なら通常必ず間に置きます。',explainTC:'turn off、pick up、put on 等可把受詞放在動詞與 particle 中間；若受詞是代名詞，通常必須放中間。',rulesJP:['turn off the light / turn the light off','turn it off（○）','turn off it（通常×）'],rulesTC:['名詞可兩位置','代名詞通常放中間','turn it off'],examples:[['Please turn the light off.','separable。','可分。'],['Please turn it off.','代名詞位置。','代名詞位置。'],['I picked the package up.','名詞を間に。','名詞可置中。']],contrasts:[['Turn off it.','Turn it off.','代名詞はparticle前。','代名詞放 particle 前。']],drillJP:'turn off/pick up/put on/take off/write downを名詞と代名詞の両方で。',drillTC:'五個可分片語動詞用名詞與代名詞各造句。'},
 {id:'inseparable',title:'Inseparable / three-word verbs — look after / put up with',level:'B1-C1',explainJP:'look after, run into, deal withやput up with, look forward toなどは分離しません。特にthree-word verbの最後のtoがprepositionなら後ろは名詞/-ingです。',explainTC:'look after、run into、deal with、put up with、look forward to 等不可分。three-word verb 的 to 若為介系詞，後接名詞或 -ing。',rulesJP:['look after someone','put up with something','look forward to doing'],rulesTC:['不可分結構','put up with','look forward to + -ing'],examples:[['She looks after her younger brother.','不可分。','不可分。'],['I cannot put up with the noise.','three-word。','三字片語。'],['I look forward to hearing from you.','toはpreposition。','to 是介系詞。']],contrasts:[['I look forward to hear from you.','I look forward to hearing from you.','toは不定詞マーカーではない。','to 不是不定詞標記。']],drillJP:'inseparable 10個を選び、目的語まで含めchunkで覚える。',drillTC:'選10個不可分片語，連受詞一起記。'},
 {id:'particles-meaning',title:'up / out / off / on — particleの意味ネットワーク',level:'B1-C1',explainJP:'particleには空間的意味から派生した傾向があります。upはcompletion/increase、outはemergence/exhaustion、offはseparation、onはcontinuationなど。完全予測はできませんが記憶の助けになります。',explainTC:'particle 有從空間概念延伸的語意傾向：up 常完成/增加，out 顯現/耗盡，off 分離，on 持續。不能完全預測但可幫記憶。',rulesJP:['use up = 使い切る','find out = 情報が明らかになる','carry on = 続ける'],rulesTC:['use up 用完','find out 發現','carry on 繼續'],examples:[['We used up all the memory.','completion。','耗盡。'],['I found out what happened.','情報の出現。','資訊顯現。'],['Please carry on.','継続。','繼續。']],contrasts:[['look up the hill','look up the word','literal vs idiomatic particle。','字面與片語意義不同。']],drillJP:'up/out/off/onごとにphrasal verbを5個ずつ分類。',drillTC:'up/out/off/on 各收集5個片語動詞分類。'},
 {id:'register-synonyms',title:'Phrasal verb vs formal single-word verb',level:'B2-C1',explainJP:'phrasal verbは口語的なものが多い一方、正式文書ではsingle-word verbが好まれる場合があります。ただし全phrasal verbがinformalとは限りません。文脈で使い分けます。',explainTC:'許多片語動詞偏口語，正式寫作可能偏好單字動詞，但並非所有片語動詞都 informal，要依語境選擇。',rulesJP:['find out ↔ discover/determine','put off ↔ postpone','carry out ↔ conduct（carry out自体も正式で頻出）'],rulesTC:['find out ↔ discover','put off ↔ postpone','carry out ↔ conduct'],examples:[['We found out why it failed.','会話的。','較口語。'],['The study determined why it failed.','よりformal。','較正式。'],['We carried out an experiment.','formalでも自然なphrasal verb。','正式文也自然。']],contrasts:[['Phrasal verbs are always informal.','Register depends on the expression and context.','一律ルールではない。','不能一概而論。']],drillJP:'phrasal verb 10個についてcasual/formal synonymを対で記録。',drillTC:'找10個片語動詞及較正式同義詞。'}]
},
{
 id:'verb-complementation',level:'B1-C2',domain:'Verb Patterns & Voice',title:'23 · Verb Complementation — 動詞の後ろに何を置けるか',titleTc:'23 · 動詞補語 — 動詞後面可以接什麼',
 overviewJP:'動詞ごとに that-clause / wh-clause / to-infinitive / -ing / object + to / bare infinitive など許される補語パターンが違います。自然な英語の核心です。',overviewTC:'不同動詞允許不同補語：that-clause、wh-clause、to-infinitive、-ing、object+to、bare infinitive 等。這是自然英文核心。',outcomesJP:['主要complement patternを分類する','tell/say/explain/suggest/allowなど頻出誤用を修正する','meaningとpatternの変化を理解する'],outcomesTC:['分類主要補語句型','修正常見 tell/say/explain/suggest/allow 錯誤','理解句型改變造成的意義差'],
 units:[
 {id:'that-wh',title:'Verb + that-clause / wh-clause',level:'B1-C1',explainJP:'think/believe/know/sayなどはthat節、know/wonder/askなどはwh節を取れます。thatは会話で省略できる場合がありますが、すべての動詞で同じではありません。',explainTC:'think/believe/know/say 可接 that 子句；know/wonder/ask 可接 wh 子句。that 在口語有時可省略，但不是所有動詞都相同。',rulesJP:['I think (that)...','I know why/how/where...','wonder if/whether...'],rulesTC:['think + that','know + wh','wonder + if/whether'],examples:[['I think that the result is correct.','that-clause。','that 子句。'],['I do not know why it failed.','wh-clause。','wh 子句。'],['I wonder whether we should wait.','whether節。','whether 子句。']],contrasts:[['I wonder that he will come.','I wonder whether he will come.','wonderのyes/no内容はif/whether。','wonder 的 yes/no 內容用 if/whether。']],drillJP:'think/know/wonder/ask/explainでclause complementを各2文。',drillTC:'五個動詞各用子句補語造2句。'},
 {id:'object-to',title:'Verb + object + to-infinitive',level:'B1-C1',explainJP:'want/ask/tell/allow/expect/encourage/remindなどは人を目的語にしてto-infinitiveを続けます。ただしsuggestは通常この形を取りません。',explainTC:'want/ask/tell/allow/expect/encourage/remind 等可接 人 + to-infinitive；suggest 通常不能。',rulesJP:['tell/ask/remind O to do','allow/enable O to do','want/expect O to do'],rulesTC:['tell/ask/remind O to do','allow/enable O to do','want/expect O to do'],examples:[['She told me to wait.','tell pattern。','tell 句型。'],['The tool allows users to export data.','allow O to。','allow O to。'],['I expected him to call.','expect O to。','expect O to。']],contrasts:[['She suggested me to wait.','She suggested that I wait. / suggested waiting.','suggestはobject + to不可。','suggest 不用 object + to。']],drillJP:'tell/ask/allow/enable/encourage/remind/expectを各1文。',drillTC:'七個 object+to 動詞各造一句。'},
 {id:'bare-infinitive',title:'Bare infinitive — modal / make / let / perception',level:'B1-C1',explainJP:'助動詞の後、make/let/have + O、see/hear/watch + O などではtoなしの原形を使うパターンがあります。知覚動詞ではbare infinitiveと-ingで見え方が変わります。',explainTC:'助動詞後、make/let/have + O、see/hear/watch + O 常用無 to 原形。知覺動詞接原形或 -ing 時視角不同。',rulesJP:['modal + base','make/let + O + base','see O do = 全体 / see O doing = 途中'],rulesTC:['modal + 原形','make/let + O + 原形','see O do 看完整事件 / doing 看進行'],examples:[['You must leave now.','modal + base。','modal + 原形。'],['They made me repeat it.','make O base。','make O 原形。'],['I saw him cross the street.','一連の出来事全体。','看到完整事件。']],contrasts:[['I saw him to cross the street.','I saw him cross the street.','active perception verbの後はbare。','主動知覺動詞後無 to。']],drillJP:'see/hear/watchをbare/-ing両方で比較。',drillTC:'用 see/hear/watch 比較原形與 -ing。'},
 {id:'pattern-meaning',title:'同じ動詞でも補語で意味が変わる',level:'B2-C2',explainJP:'mean doing / mean to do, go on doing / go on to do, need doing / need to doなど、補語形式が語義の一部になっています。上級では辞書のgrammar patternを確認する習慣が重要です。',explainTC:'mean doing / mean to do、go on doing / go on to do、need doing / need to do 等，補語形式本身影響語義。高階學習要習慣查字典句型。',rulesJP:['mean doing = 結果として伴う / mean to do = 意図','go on doing = 続ける / go on to do = 次にする','need doing = need to be done'],rulesTC:['mean doing = 意味著/造成；mean to do = 打算','go on doing 繼續；go on to do 接著做另一事','need doing = need to be done'],examples:[['This change means rewriting the code.','結果として必要。','意味著需重寫。'],['I meant to call you.','意図。','原本打算。'],['The device needs repairing.','needs to be repaired。','需要被修。']],contrasts:[['I mean calling you.','I meant to call you.','「電話するつもりだった」ならto。','「本來打算打電話」用 to。']],drillJP:'mean/go on/needの各patternを対比で作る。',drillTC:'用 mean/go on/need 各做句型對比。'}]
}
);