window.grammarChapters = window.grammarChapters || [];
window.grammarChapters.push(
{
  id:'sentence-architecture', level:'A1-B2', domain:'Sentence & Clause Architecture',
  title:'01 · Sentence Architecture — 英文の骨格を完全に理解する', titleTc:'01 · 句子骨架 — 完整理解英文結構',
  overviewJP:'英文は「単語の意味」だけではなく、語順と動詞が要求する要素によって意味が組み立てられます。この章では S/V/O/C、5文型、自動詞・他動詞、補語、目的語、句と節までを一つの体系として学びます。',
  overviewTC:'英文不只靠單字意思，也靠語序與動詞所要求的成分建立意義。本章把 S/V/O/C、五大句型、不及物/及物動詞、補語、受詞、片語與子句整合起來學。',
  outcomesJP:['文の主動詞と主語を素早く特定できる','OとCの違いを意味で説明できる','動詞ごとに可能な構文を判断できる','長文でも主節の骨格を抜き出せる'],
  outcomesTC:['快速找出主要動詞與主詞','能解釋 O 與 C 的差異','依動詞判斷可用句型','長句也能抓出主句骨架'],
  units:[
    {id:'svoc',title:'S / V / O / C は「役割」で見る',level:'A1',explainJP:'S/V/O/C は単語の種類ではなく、文の中での役割です。特に C は S または O の「正体・状態・性質」を説明します。O は動作の対象であり、C とは交換できません。',explainTC:'S/V/O/C 是句中角色，不是詞性。C 用來說明 S 或 O 的身分、狀態或性質；O 則是動作的對象。',rulesJP:['まず有限動詞を探し、その動詞の主語を決める','SVC の C は S と意味的に同一関係、SVOC の C は O を説明する','副詞句は骨格の S/V/O/C に含まれないことが多い'],rulesTC:['先找限定動詞，再找主詞','SVC 的 C 說明 S；SVOC 的 C 說明 O','副詞片語通常不屬於 S/V/O/C 核心'],examples:[['The experiment failed.','実験は失敗した。SV。','實驗失敗了。SV。'],['The result seems reliable.','result = reliable なので SVC。','result = reliable，因此是 SVC。'],['They found the interface confusing.','interface = confusing なので SVOC。','interface = confusing，因此是 SVOC。']],contrasts:[['She became a doctor.','She met a doctor.','前者の a doctor はSを説明するC、後者は動作対象O。','前者 a doctor 是補語，後者是受詞。']],drillJP:'10文を用意し、修飾語を括弧に入れてS/V/O/Cだけを残す。',drillTC:'準備10句，把修飾語括起來，只留下 S/V/O/C。'},
    {id:'five-patterns',title:'5文型は暗記表ではなく「動詞の設計図」',level:'A1-A2',explainJP:'5文型の目的は文をラベル付けすることではありません。動詞が後ろに何を要求するかを予測するための道具です。give は人＋物を取れますが、explain は通常 explain 人 物 の形を取りません。',explainTC:'五大句型不是為了貼標籤，而是預測動詞後面需要什麼。give 可接「人＋物」，explain 通常不能直接接「人＋物」。',rulesJP:['SV: complete intransitive / SVC: linking verb / SVO: transitive','SVOO は「人に物を与える」意味群で多い','SVOC は make/find/keep/call/consider などで頻出'],rulesTC:['SV 不及物；SVC 連綴；SVO 及物','SVOO 常見於「給某人某物」','SVOC 常見於 make/find/keep/call/consider'],examples:[['She gave me some advice.','give + 人 + 物。','give + 人 + 物。'],['Please keep the door closed.','door = closed。','door = closed。'],['We considered the plan unrealistic.','plan = unrealistic。','plan = unrealistic。']],contrasts:[['He explained me the rule.','He explained the rule to me.','explain は通常SVOO不可。','explain 通常不能用 SVOO。']],drillJP:'give/show/tell/explain/describe/suggest の6動詞について、取れる構文を辞書で確認して例文を1つずつ作る。',drillTC:'查 give/show/tell/explain/describe/suggest 可用句型，各造一句。'},
    {id:'transitivity',title:'自動詞・他動詞・両用動詞',level:'A2-B1',explainJP:'日本語訳が同じでも英語では目的語の取り方が違います。arrive は自動詞、reach は他動詞です。また change/open/break のように自動詞・他動詞の両方で使える動詞も多くあります。',explainTC:'即使翻譯相近，英文動詞的受詞結構可能不同。arrive 不及物、reach 及物；change/open/break 等可同時作及物與不及物。',rulesJP:['自動詞の後ろに名詞を直接置けない場合は前置詞が必要','他動詞の後ろに不要な前置詞を入れない','同じ動詞でも意味によってtransitivityが変わることがある'],rulesTC:['不及物動詞後接名詞常需介系詞','及物動詞後不要多加介系詞','同一動詞依意思可能改變及物性'],examples:[['We arrived at the station.','arrive + at。','arrive + at。'],['We reached the station.','reach + 目的語。','reach + 受詞。'],['The door opened. / She opened the door.','open は両用。','open 可及物也可不及物。']],contrasts:[['We discussed about the issue.','We discussed the issue.','discuss は他動詞。','discuss 是及物動詞。']],drillJP:'arrive/reach, enter/go into, discuss/talk about, marry/get married to を対で5回音読する。',drillTC:'成對朗讀 arrive/reach、enter/go into、discuss/talk about、marry/get married to。'},
    {id:'phrases-clauses',title:'Phrase / Clause / Main clause — 長文の骨組み',level:'B1-B2',explainJP:'長い英文が難しい原因の多くは、どこが主節でどこが埋め込みなのかを見失うことです。Clauseには主語＋有限動詞があり、主節・従属節・関係節・名詞節などが入れ子になります。',explainTC:'長句的難點常是分不清主句與嵌入句。Clause 通常含主詞與限定動詞，主句、從句、關係子句、名詞子句會層層嵌入。',rulesJP:['有限動詞の数を数えると節の候補が見える','that/who/which/if/because/when などは節の入口になりやすい','前置詞句や分詞句は長くても主節ではない'],rulesTC:['數限定動詞可估計子句數','that/who/which/if/because/when 常引導子句','介系詞片語或分詞片語再長也不一定是主句'],examples:[['The model that we trained yesterday performs well.','主節: The model performs well.','主句：The model performs well.'],['Although the test failed, we learned why the system was unstable.','Although節＋主節＋why名詞節。','Although從句＋主句＋why名詞子句。'],['Data collected from three cameras was synchronized.','collected... は分詞句、主動詞は was。','collected... 是分詞片語，主動詞是 was。']],contrasts:[['The students working in the lab.','The students working in the lab are busy.','前者は通常完全な文ではなく名詞句。','前者通常不是完整句子。']],drillJP:'100語程度の英文から有限動詞を丸で囲み、主節だけを抜き出す。',drillTC:'從約100字英文圈出限定動詞，再只抽出主句。'}
  ]
},
{
  id:'be-system', level:'A1-B2', domain:'Sentence & Clause Architecture',
  title:'02 · BE System — be動詞を「＝」だけで終わらせない', titleTc:'02 · BE 系統 — 不只把 be 當成「等於」',
  overviewJP:'be は英語の中心的な文法装置です。状態・存在・位置を表す本動詞であると同時に、進行形と受動態を作る助動詞でもあります。',overviewTC:'be 是英文核心文法裝置，既能表示狀態、存在、位置，也能形成進行式與被動態。',
  outcomesJP:['be＋名詞/形容詞/前置詞句を使い分ける','there be と通常のbeを区別する','進行形・受動態のbeを認識する'],outcomesTC:['區分 be＋名詞/形容詞/介系詞片語','區分 there be 與一般 be','辨識進行式與被動的 be'],
  units:[
    {id:'copular-be',title:'Copular be — 主語を説明する',level:'A1',explainJP:'be の最も基本的な働きは主語と補語を結ぶことです。補語は名詞・形容詞・前置詞句などになり、主語の身分・状態・位置を表します。',explainTC:'be 最基本功能是連接主詞與補語。補語可為名詞、形容詞或介系詞片語，說明身分、狀態或位置。',rulesJP:['be＋名詞: 身分・分類','be＋形容詞: 状態・性質','be＋前置詞句: 場所・状態'],rulesTC:['be＋名詞：身分/分類','be＋形容詞：狀態/性質','be＋介系詞片語：位置/狀態'],examples:[['She is an engineer.','身分。','身分。'],['The server is busy.','状態。','狀態。'],['The keys are on the desk.','位置。','位置。']],contrasts:[['She is work today.','She is working today. / She works today.','一般動詞をそのままbeの後ろに置かない。','一般動詞不能直接放在 be 後。']],drillJP:'自分について be＋名詞、be＋形容詞、be＋前置詞句を各3文。',drillTC:'用 be＋名詞、形容詞、介系詞片語各造3句。'},
    {id:'existential-there',title:'There is / are — 存在を新情報として導入する',level:'A1-B1',explainJP:'There is/are の there は場所を意味する副詞ではなく、存在構文を作る形式要素です。会話や文章に新しい対象を登場させるときに自然です。',explainTC:'There is/are 的 there 並非單純地點副詞，而是存在構文的形式元素，常用來引入新資訊。',rulesJP:['There is + 単数/不可算、There are + 複数が基本','具体的な既知の主語には通常のbe文を使う','there seems/appears to be など上級形もある'],rulesTC:['There is 接單數/不可數，There are 接複數','已知具體主詞通常用一般 be 句','也有 there seems/appears to be'],examples:[['There is a problem with the sensor.','問題を新しく導入。','引入一個新問題。'],['There are several reasons for this.','複数存在。','表示多個原因存在。'],['There seems to be a mismatch.','控えめな存在判断。','較保守地判斷存在。']],contrasts:[['A problem is in the sensor.','There is a problem with the sensor.','存在を導入するならthere構文が自然。','引入存在時 there 構文較自然。']],drillJP:'部屋・研究室・町について there is/are を5文。',drillTC:'用 there is/are 寫5句描述房間、實驗室或城市。'},
    {id:'be-auxiliary',title:'Auxiliary be — Progressive と Passive',level:'A2-B1',explainJP:'be が助動詞として使われると、その後ろの形が意味を決めます。be + V-ing は進行、be + 過去分詞は受動が基本です。',explainTC:'be 作助動詞時，後面的形式決定意義：be + V-ing 為進行，be + 過去分詞通常為被動。',rulesJP:['時制・人称はbeに乗る','進行形では本動詞は-ing','受動態では本動詞は過去分詞'],rulesTC:['時態與人稱由 be 承擔','進行式主動詞用 -ing','被動主動詞用過去分詞'],examples:[['The robot is moving.','現在進行。','現在進行。'],['The robot was repaired yesterday.','過去受動。','過去被動。'],['The data is being processed.','進行＋受動。','進行＋被動。']],contrasts:[['The data is process.','The data is processed. / is being processed.','process は過去分詞か-ingが必要。','process 需用過去分詞或 -ing。']],drillJP:'同じ動詞を active / progressive / passive / progressive passive の4形に変換する。',drillTC:'把同一動詞改成主動、進行、被動、進行被動四種。'}
  ]
},
{
  id:'aux-do-have', level:'A1-B2', domain:'Sentence & Clause Architecture',
  title:'03 · DO & HAVE — 否定・疑問・強調・完了の中枢',titleTc:'03 · DO & HAVE — 否定、疑問、強調與完成的核心',
  overviewJP:'do と have は一般動詞にも助動詞にもなります。助動詞としてのdoは否定・疑問・強調を、haveは完了を作ります。',overviewTC:'do 與 have 都可作主要動詞或助動詞。助動詞 do 建立否定、疑問與強調；have 建立完成式。',
  outcomesJP:['do-supportを自動化する','doによる強調を理解する','所有haveと完了haveを区別する'],outcomesTC:['自動化 do-support','理解 do 的強調','區分擁有 have 與完成 have'],
  units:[
    {id:'do-support',title:'Do-support — 一般動詞文の否定と疑問',level:'A1',explainJP:'一般動詞文に他の助動詞がないとき、否定・疑問には do/does/did を補います。時制と三単現の情報がdo側へ移るため、本動詞は原形へ戻ります。',explainTC:'一般動詞句沒有其他助動詞時，否定與疑問使用 do/does/did。時態與第三人稱資訊移到 do，因此主要動詞回原形。',rulesJP:['Do/Does + S + 原形?','S + do/does not + 原形','Did があれば本動詞は過去形にしない'],rulesTC:['Do/Does + S + 原形?','S + do/does not + 原形','用了 Did 後主動詞不再用過去式'],examples:[['Does she work here?','worksではない。','不是 works。'],['He does not know the answer.','does + know。','does + know。'],['Did you see it?','did + see。','did + see。']],contrasts:[['Did you went there?','Did you go there?','過去情報はdidが持つ。','過去資訊由 did 承擔。']],drillJP:'肯定文10文を否定文と疑問文に変換する。',drillTC:'把10個肯定句改成否定句與疑問句。'},
    {id:'emphatic-do',title:'Emphatic do — 本当に〜する、確かに〜した',level:'B1-B2',explainJP:'肯定文のdo/does/didは強調にも使えます。反論、訂正、強い肯定、丁寧な勧誘などで「本当に」「確かに」という意味を加えます。',explainTC:'肯定句中的 do/does/did 可用於強調，表示反駁、修正、強烈肯定或禮貌邀請，相當於「真的、確實」。',rulesJP:['do + 原形で強調','過去は did + 原形','イントネーションでも強調される'],rulesTC:['do + 原形表示強調','過去用 did + 原形','口語中通常也有重音'],examples:[['I do understand your concern.','本当に理解している。','我真的理解。'],['He did send the file.','確かに送った。','他確實寄了。'],['Do come in.','ぜひ入ってください。','請一定進來。']],contrasts:[['I very understand.','I do understand. / I understand very well.','veryは動詞understandを直接修飾しない。','very 不直接修飾 understand。']],drillJP:'反論・安心させる場面で emphatic do を3文作る。',drillTC:'用 emphatic do 寫3句反駁或安慰對方的句子。'},
    {id:'have-main-aux',title:'Have — 所有・経験・完了を構造で区別',level:'A1-B1',explainJP:'have は「持つ」だけではありません。have a meeting / have lunch のような軽動詞表現、have got、そして助動詞 have + p.p. の完了形があります。',explainTC:'have 不只表示「擁有」。還有 have a meeting / have lunch 等輕動詞用法、have got，以及助動詞 have + 過去分詞的完成式。',rulesJP:['所有: have + 名詞','活動: have + event/meal/experience 名詞','完了: have/has/had + 過去分詞'],rulesTC:['擁有：have + 名詞','活動：have + event/meal/experience 名詞','完成：have/has/had + 過去分詞'],examples:[['I have a laptop.','所有。','擁有。'],['We had a meeting.','活動。','活動。'],['I have finished the report.','完了。','完成。']],contrasts:[['I have finish it.','I have finished it.','完了haveの後ろは過去分詞。','完成式 have 後接過去分詞。']],drillJP:'haveを「所有・活動・完了」の3意味で各3文作る。',drillTC:'用 have 的「擁有、活動、完成」各造3句。'}
  ]
},
{
  id:'nouns-countability',level:'A1-C1',domain:'Noun Phrase System',
  title:'04 · Nouns & Countability — 名詞の数え方が文法を決める',titleTc:'04 · 名詞與可數性 — 名詞的可數性決定文法',
  overviewJP:'可算・不可算は単なる単語暗記ではなく、「その意味を個体として切り分けるか」という概念です。同じ名詞でも意味によって可算性が変わります。',overviewTC:'可數/不可數不是單純背單字，而是看該意思是否被視為可分割的個體。同一名詞依意思可改變可數性。',
  outcomesJP:['単数可算名詞にdeterminerが必要な理由を理解する','不可算名詞の典型群を使える','意味によるcountability shiftを判断する'],outcomesTC:['理解單數可數名詞為何需要限定詞','能使用常見不可數名詞','判斷依語意改變的可數性'],
  units:[
    {id:'count-nouns',title:'Count nouns — 単数と複数を必ず意識する',level:'A1',explainJP:'単数可算名詞は英語では通常、a/the/my/this/oneなどのdeterminerなしに裸で置けません。複数形では一般論として裸複数が可能です。',explainTC:'單數可數名詞通常不能沒有 a/the/my/this/one 等限定詞。複數名詞則可用裸複數表示一般概念。',rulesJP:['単数可算名詞: determiner + noun','複数一般論: Dogs are friendly.','複数特定: The dogs outside are noisy.'],rulesTC:['單數可數：限定詞 + 名詞','複數一般論可裸用','特定複數通常加 the 等'],examples:[['I bought a book.','単数なのでa。','單數所以用 a。'],['Books are expensive.','一般論の複数。','泛指複數。'],['The books on the table are mine.','限定されている。','被限定的特定複數。']],contrasts:[['I bought book.','I bought a book.','単数可算名詞を裸で置かない。','單數可數名詞不能裸用。']],drillJP:'身の回りの可算名詞10個を単数・複数の両方で文にする。',drillTC:'選10個可數名詞，各寫單數與複數句。'},
    {id:'mass-nouns',title:'Uncountable nouns — information, advice, research...',level:'A1-B2',explainJP:'不可算名詞は通常a/anや直接の複数-sを取りません。英語学習で頻出する information, advice, equipment, furniture, research, evidence, progress, knowledge などは特に注意が必要です。',explainTC:'不可數名詞通常不接 a/an，也不直接加複數 -s。information、advice、equipment、furniture、research、evidence、progress、knowledge 等特別常見。',rulesJP:['some/much/little + 不可算','数えるときは piece/item/bit など単位表現','動詞一致は通常単数'],rulesTC:['some/much/little + 不可數','要數時用 piece/item/bit 等單位','動詞通常用單數'],examples:[['I need some information.','information不可算。','information 不可數。'],['She gave me two pieces of advice.','pieceで数える。','用 piece 計數。'],['The equipment is expensive.','isを使う。','使用 is。']],contrasts:[['an advice / advices','a piece of advice / some advice','adviceは不可算。','advice 不可數。']],drillJP:'information/advice/equipment/research/evidence/progress を各1文。',drillTC:'用 information/advice/equipment/research/evidence/progress 各造一句。'},
    {id:'countability-shift',title:'意味が変わると可算性も変わる',level:'B1-C1',explainJP:'coffee, paper, experience, time, work, room, chicken などは意味によって可算・不可算が変わります。辞書で[C]/[U]を見るだけでなく、「物質/概念」か「個体/種類/出来事」かを考えます。',explainTC:'coffee、paper、experience、time、work、room、chicken 等依語意可變成可數或不可數。要看是物質/概念，還是個體/種類/事件。',rulesJP:['material → 不可算、unit/type → 可算になりやすい','experience=経験一般(U) / an experience=一つの体験(C)','work=仕事(U) / a work=作品(C, 特定の文脈)'],rulesTC:['物質常不可數，單位/種類常可數','experience 經驗(U) / an experience 一次體驗(C)','work 工作(U) / a work 作品(C)'],examples:[['Coffee keeps me awake.','飲料一般。','咖啡這種物質。'],['Two coffees, please.','2杯のcoffee。','兩杯咖啡。'],['I have little experience, but it was an unforgettable experience.','一般経験と一回の体験。','一般經驗與一次體驗。']],contrasts:[['I have many experience.','I have a lot of experience. / many experiences.','意味によりU/Cを選ぶ。','依意思選 U/C。']],drillJP:'paper/time/room/chicken/work を可算・不可算それぞれで例文化。',drillTC:'把 paper/time/room/chicken/work 各用可數與不可數造句。'}
  ]
},
{
  id:'articles',level:'A1-C2',domain:'Noun Phrase System',
  title:'05 · Articles — a / the / Ø を「意味」で選ぶ',titleTc:'05 · 冠詞 — 用語意選擇 a / the / Ø',
  overviewJP:'冠詞は日本語に直接対応しませんが、英語では話し手が名詞をどう提示するかを示す重要な意味装置です。「可算性→単複→特定可能性→一般/個別」の順で判断します。',overviewTC:'冠詞在日中語沒有直接對應，但英文中用來表示說話者如何呈現名詞。可依「可數性→單複→能否特定→泛指/特指」判斷。',
  outcomesJP:['a/anを「1つ」以上の意味で理解する','theの特定可能性を判断できる','zero articleの一般化を使える','地名・施設・固有名詞の主要パターンを使える'],outcomesTC:['理解 a/an 不只是「一個」','判斷 the 的可識別性','使用零冠詞做泛指','掌握地名、設施、專有名詞主要規則'],
  units:[
    {id:'a-an',title:'a / an — 聞き手にまだ特定されていない一例',level:'A1-B1',explainJP:'a/an は「1」という数だけではなく、ある集合から一つの例を取り出す働きがあります。職業、分類、初出、頻度などにも使われます。',explainTC:'a/an 不只表示數字1，也表示從一類中提出一個例子，可用於職業、分類、首次提及與頻率。',rulesJP:['初出の単数可算名詞','職業・分類: She is an engineer.','perの意味: twice a week'],rulesTC:['首次提到的單數可數名詞','職業/分類：an engineer','頻率：twice a week'],examples:[['I saw a dog outside.','初出。','首次提及。'],['She is a researcher.','分類。','職業分類。'],['I exercise three times a week.','per week。','每週三次。']],contrasts:[['She is engineer.','She is an engineer.','職業名も単数可算名詞。','職業名也是單數可數名詞。']],drillJP:'初出・職業・頻度の3用法でa/anを各2文。',drillTC:'用首次提及、職業、頻率三種 a/an 各造2句。'},
    {id:'the-identifiability',title:'the — 「話し手と聞き手がどれか分かる」',level:'A1-C1',explainJP:'the の核心は「唯一」ではなく、聞き手がその名詞を特定できることです。既出、状況共有、唯一性、後置修飾、最上級など複数の理由で特定可能になります。',explainTC:'the 的核心不是單純「唯一」，而是聽者能辨識是哪一個。已提及、共同情境、唯一性、後置修飾、最高級等都可使名詞可識別。',rulesJP:['既出: a ... → the ...','共有状況: Close the door.','後置修飾: the book on the desk','唯一・序数・最上級にも多い'],rulesTC:['已提及：a → the','共同情境：Close the door.','後置修飾：the book on the desk','唯一、序數、最高級常用 the'],examples:[['I bought a laptop. The laptop is light.','既出。','已提及。'],['Please turn off the light.','状況から特定。','由情境可識別。'],['The information you sent was helpful.','you sentが特定。','you sent 使其特定。']],contrasts:[['I like the music.（音楽一般）','I like music.','一般概念ならzero articleが普通。','泛指概念通常零冠詞。']],drillJP:'既出・共有状況・後置修飾・最上級のtheを各2文。',drillTC:'用已提及、共同情境、後置修飾、最高級的 the 各造2句。'},
    {id:'zero-generic',title:'Zero article — 一般概念・制度・活動',level:'A2-C1',explainJP:'複数可算名詞や不可算名詞を「種類全体・概念一般」として話すときはzero articleがよく使われます。また go to school / be in prison / go to bed のように施設の本来機能を表すときも無冠詞になることがあります。',explainTC:'複數可數或不可數名詞表示整類或一般概念時常用零冠詞。go to school / be in prison / go to bed 等表示制度本來功能時也常零冠詞。',rulesJP:['一般複数: Computers are useful.','不可算一般: Knowledge matters.','制度・機能: at school / in bed / at work'],rulesTC:['泛指複數：Computers...','不可數泛指：Knowledge...','制度/功能：at school / in bed / at work'],examples:[['Technology changes quickly.','概念一般。','一般概念。'],['Children need sleep.','children/sleepとも一般。','children/sleep 都是泛指。'],['She is at school.','学生として学校にいる。','以學生身分在學校。']],contrasts:[['I went to school to meet the teacher.','I went to the school to meet the teacher.','建物として特定の学校へ行くならtheが自然。','去特定學校建築時常用 the。']],drillJP:'一般概念5文＋institutional zero article 3文。',drillTC:'寫5個一般概念句＋3個制度性零冠詞句。'},
    {id:'proper-geography',title:'固有名詞・地名・組織名の冠詞',level:'B1-C2',explainJP:'固有名詞は原則無冠詞ですが、複数性・集合・記述的名称を含むとtheを取ることがあります。国・海・河川・山脈・ホテル・新聞・組織などはパターンで整理します。',explainTC:'專有名詞原則零冠詞，但複數、集合或描述性名稱常帶 the。國家、海洋、河川、山脈、飯店、報紙、組織可用模式整理。',rulesJP:['Japan / Taiwan / France は通常Ø','the United States / the Netherlands','the Pacific / the Nile / the Alps','Mount Fuji はØ、the Fuji?ではない'],rulesTC:['Japan/Taiwan/France 通常零冠詞','the United States / the Netherlands','the Pacific / the Nile / the Alps','Mount Fuji 不加 the'],examples:[['I live in Japan.','国名通常Ø。','國名通常零冠詞。'],['She traveled across the United States.','複数・記述的国名。','複數/描述性國名。'],['They crossed the Pacific.','海洋。','海洋。']],contrasts:[['the Mount Fuji','Mount Fuji','単独の山名は通常無冠詞。','單一山峰名稱通常零冠詞。']],drillJP:'国5、河川2、海2、山2、組織2を選んで冠詞付きで例文化。',drillTC:'選5國、2河、2海、2山、2組織造句並確認冠詞。'}
  ]
},
{
  id:'determiners-quantifiers',level:'A1-C1',domain:'Noun Phrase System',
  title:'06 · Determiners & Quantifiers — some / any / much / many / few / little',titleTc:'06 · 限定詞與量詞 — some / any / much / many / few / little',
  overviewJP:'量表現は「多い/少ない」の訳だけでなく、可算性、肯定/否定、話し手の期待、十分性の評価まで含みます。',overviewTC:'數量表現不只翻成「多/少」，還包含可數性、肯否定、說話者預期與是否足夠的評價。',
  outcomesJP:['some/anyの基本と例外を使える','many/much/a lot ofをレジスター込みで選ぶ','few/a few/little/a littleの評価差を理解する'],outcomesTC:['掌握 some/any 基本與例外','依語域選 many/much/a lot of','理解 few/a few/little/a little 的評價差'],
  units:[
    {id:'some-any',title:'some / any — 肯定・否定だけではない',level:'A1-B1',explainJP:'基本は肯定文some、否定・疑問anyですが、依頼や申し出で肯定的な答えを期待するとsomeを使います。anyは肯定文で「どれでも・誰でも」の意味にもなります。',explainTC:'基本上肯定句用 some，否定/疑問用 any，但邀請、請求且預期肯定回答時可用 some。any 在肯定句也可表示「任何」。',rulesJP:['some: 存在をある程度想定','any: 非限定・ゼロ可能性を開く','Would you like some...? は典型例外'],rulesTC:['some：預設某些存在','any：不限定/包含零可能','Would you like some...? 是典型'],examples:[['I need some help.','肯定。','肯定句。'],['I do not have any questions.','否定。','否定句。'],['Would you like some coffee?','申し出。','邀請。']],contrasts:[['Do you want any coffee?','Would you like some coffee?','前者は中立的質問、後者はofferとして自然。','前者中立，後者是邀請。']],drillJP:'some/anyを肯定・否定・疑問・offer・「どれでも」で各1文。',drillTC:'用 some/any 做肯定、否定、疑問、邀請、「任何」各1句。'},
    {id:'much-many-lot',title:'many / much / a lot of — 数量とレジスター',level:'A1-B2',explainJP:'manyは複数可算、muchは不可算。肯定文の会話ではa lot ofが自然なことが多く、muchは否定・疑問や比較的フォーマルな文脈で目立ちます。',explainTC:'many 接複數可數，much 接不可數。口語肯定句常用 a lot of；much 常見於否定、疑問或較正式文脈。',rulesJP:['many + plural count','much + uncountable','a lot of + 両方'],rulesTC:['many + 複數可數','much + 不可數','a lot of 兩者都可'],examples:[['Many students applied.','可算複数。','可數複數。'],['We do not have much time.','不可算。','不可數。'],['I have a lot of work today.','会話で自然。','口語自然。']],contrasts:[['I have much work today.','I have a lot of work today.','文法的には可能でも日常肯定文ではa lot ofが自然。','文法可行但日常肯定句 a lot of 更自然。']],drillJP:'同じ内容を casual と formal の2レジスターで量表現を変えて書く。',drillTC:'同內容用 casual/formal 兩種語域改寫數量表現。'},
    {id:'few-little',title:'few / a few / little / a little — 「少ない」の評価',level:'A2-B2',explainJP:'few/little は「ほとんどない」という否定的評価、a few/a little は「少しはある」という肯定的評価を持ちます。日本語訳が似ても話し手の見方が違います。',explainTC:'few/little 帶「幾乎沒有」的負面評價；a few/a little 帶「至少有一些」的正面評價。',rulesJP:['few/a few + 複数可算','little/a little + 不可算','only a few は量の少なさを強調'],rulesTC:['few/a few + 複數可數','little/a little + 不可數','only a few 強調少'],examples:[['Few people understood it.','ほとんど理解しなかった。','幾乎沒人懂。'],['A few people understood it.','何人かは理解した。','至少有幾個人懂。'],['We have a little time.','少し時間がある。','還有一點時間。']],contrasts:[['We have little time.','We have a little time.','前者は「時間がほぼない」、後者は「少しある」。','前者幾乎沒時間，後者還有一點。']],drillJP:'few/a few/little/a littleを使い、評価の違いが伝わる4組を作る。',drillTC:'用 few/a few/little/a little 各造句，表達評價差異。'},
    {id:'each-every-all-both',title:'each / every / all / both / either / neither',level:'A2-C1',explainJP:'これらは集合をどう見るかが違います。eachは個々を意識、everyは全成員を一括、allは集合全体、bothは2つ全部、either/neitherは2者選択です。',explainTC:'這些詞差在如何看集合：each 強調個別、every 強調所有成員、all 看整體、both 表示兩者皆、either/neither 處理二選一。',rulesJP:['each/every + 単数名詞','all + 複数/不可算','both/either/neither は基本2者'],rulesTC:['each/every + 單數名詞','all + 複數/不可數','both/either/neither 基本用於兩者'],examples:[['Each student received feedback.','個別性。','逐一。'],['Every student must register.','全員規則。','所有人。'],['Neither option is ideal.','2つとも理想的でない。','兩者都不理想。']],contrasts:[['Every students','Every student','everyの後ろは単数。','every 後接單數。']],drillJP:'3人以上の集合と2者の選択を使ってeach/every/all/both/either/neitherを例文化。',drillTC:'用三人以上集合與兩者選擇造句。'}
  ]
},
{
  id:'pronouns-possession',level:'A1-C1',domain:'Noun Phrase System',
  title:'07 · Pronouns & Possession — 代名詞・所有・照応',titleTc:'07 · 代名詞與所有 — 指涉與照應',
  overviewJP:'代名詞は短い単語ですが、主格/目的格/所有/再帰、単数they、one/ones、指示語など多くの体系があります。Writingでは「何を指すか」が曖昧にならないことも重要です。',overviewTC:'代名詞雖短，但包含主格/受格/所有/反身、單數 they、one/ones、指示詞等系統。寫作中也要避免指涉不清。',
  outcomesJP:['格と所有形を自動化する','再帰代名詞の必要/不要を判断する','単数theyを理解する','曖昧なpronoun referenceを修正できる'],outcomesTC:['自動化格與所有形式','判斷反身代名詞是否必要','理解單數 they','修正模糊指涉'],
  units:[
    {id:'personal-case',title:'I/me/my/mine — Case と Possession',level:'A1',explainJP:'人称代名詞は文中の役割によって形が変わります。主語はI/he/she/we/they、動詞・前置詞の目的語はme/him/her/us/them。所有限定詞myと所有代名詞mineも区別します。',explainTC:'人稱代名詞依句中角色變形。主詞用 I/he/she/we/they；動詞或介系詞受詞用 me/him/her/us/them。my 與 mine 也不同。',rulesJP:['主語形 vs 目的格','my + noun / mine 単独','前置詞の後ろは目的格'],rulesTC:['主格 vs 受格','my + 名詞 / mine 單獨','介系詞後用受格'],examples:[['She called me.','she=主語、me=目的語。','she 主詞、me 受詞。'],['This is my laptop.','my + noun。','my + 名詞。'],['This laptop is mine.','mine単独。','mine 單獨。']],contrasts:[['between you and I','between you and me','前置詞betweenの後ろは目的格。','介系詞 between 後用受格。']],drillJP:'I/me/my/mine, he/him/his, they/them/their/theirs を表にして例文。',drillTC:'整理 I/me/my/mine 等表格並造句。'},
    {id:'reflexive',title:'myself / yourself — Reflexive と emphasis',level:'A2-B2',explainJP:'再帰代名詞は主語と目的語が同じ人物のとき、または「自分自身で」という強調に使います。日本語の「自分」をそのまま全部myselfにしないことが重要です。',explainTC:'反身代名詞用於主詞與受詞為同一人，或表示「親自」。不能把日語/中文的「自己」全部機械翻成 myself。',rulesJP:['I hurt myself. のような真正再帰','I did it myself. は強調','by myself は一人で'],rulesTC:['真正反身：I hurt myself','強調：I did it myself','by myself：獨自'],examples:[['She introduced herself.','主語と目的語が同じ。','主詞與受詞相同。'],['I built it myself.','自分自身で。','親自做。'],['I went there by myself.','一人で。','獨自去。']],contrasts:[['Myself went to the meeting.','I went to the meeting.','通常myselfを普通の主語にはしない。','myself 通常不能作一般主詞。']],drillJP:'reflexive / emphatic / by oneself を各2文。',drillTC:'反身、強調、by oneself 各造2句。'},
    {id:'singular-they',title:'Singular they — 性別不明・非限定の人を自然に指す',level:'B1-C1',explainJP:'they/them/theirは複数だけでなく、性別が不明・重要でない単数の人、everyone/someoneなどを受ける形として広く使われます。現代英語では非常に一般的です。',explainTC:'they/them/their 不只複數，也常指性別未知或不重要的單數人物，或承接 everyone/someone。現代英語非常常見。',rulesJP:['someone/everyone + they は自然','性別を仮定しない表現として使える','動詞は they are/have の複数形態'],rulesTC:['someone/everyone + they 很自然','可避免假設性別','動詞仍用 they are/have'],examples:[['Someone left their phone here.','someoneをtheirで受ける。','someone 用 their 承接。'],['If a student needs help, they can ask me.','一般的な単数人。','泛指單數人物。'],['Everyone should bring their ID.','everyone + their。','everyone + their。']],contrasts:[['Every student should bring his ID.','Every student should bring their ID.','後者は性別を限定せず自然。','後者不限定性別，更自然。']],drillJP:'someone/everyone/a user/a student をsingular theyで受ける文を作る。',drillTC:'用 singular they 承接 someone/everyone/a user/a student。'},
    {id:'reference-clarity',title:'Pronoun reference — 「it/this/they」が何を指すか',level:'B2-C1',explainJP:'Writingでは文法的に正しくても、it/this/theyの先行詞が曖昧だと読みにくくなります。this result / this change のように名詞を添えると明確になることがあります。',explainTC:'寫作中即使文法正確，it/this/they 的先行詞不清楚也會難讀。加上 this result / this change 等名詞常能改善。',rulesJP:['先行詞が複数候補ある場合は名詞を繰り返す','文全体を受けるthisには名詞を添えると明確','数・人称の一致を保つ'],rulesTC:['有多個可能先行詞時重複名詞','this 承接整句時加名詞更清楚','保持數與人稱一致'],examples:[['The sensor failed, which delayed the test.','whichが前の出来事を受ける。','which 承接前一事件。'],['The model was retrained. This change improved accuracy.','this changeで明確。','this change 更清楚。'],['The team replaced the motor because it was damaged.','it=the motor。','it = motor。']],contrasts:[['The motor hit the frame and it was damaged.','The motor was damaged after it hit the frame.','itがmotor/frameどちらか曖昧。','it 可能指 motor 或 frame，模糊。']],drillJP:'自分のWritingからit/this/theyを全部探し、先行詞が一意か確認する。',drillTC:'從自己的文章找出所有 it/this/they，確認指涉是否唯一。'}
  ]
}
);