window.grammarChapters = window.grammarChapters || [];
window.grammarChapters.push(
{
 id:'relative-clauses',level:'A2-C2',domain:'Complex Clauses',title:'24 · Relative Clauses — 名詞に情報を正確に追加する',titleTc:'24 · 關係子句 — 精確為名詞補充資訊',
 overviewJP:'関係詞はwho/which/thatの穴埋めだけではありません。制限/非制限、目的格省略、whose、前置詞＋which/whom、reduced relativeまで扱います。',overviewTC:'關係詞不只是 who/which/that 填空，還要掌握限制/非限制、受詞省略、whose、介系詞+which/whom、縮減關係子句。',
 outcomesJP:['制限/非制限の意味差を説明する','relative pronounの格を判断する','前置詞関係詞と縮約形を使える'],outcomesTC:['解釋限制/非限制差異','判斷關係代名詞格','使用介系詞關係詞與縮減形式'],
 units:[
 {id:'defining',title:'Defining relative clauses — どの人・物かを限定する',level:'A2-B1',explainJP:'制限用法は先行詞を識別するために必要な情報を与えます。通常コンマを置かず、人はwho/that、物はwhich/thatが基本です。目的格は省略できる場合があります。',explainTC:'限制關係子句提供辨識先行詞所需資訊，通常不用逗號。人用 who/that，物用 which/that；受詞關係代名詞可省略。',rulesJP:['no comma','subject relativeは省略不可','object relativeは省略可'],rulesTC:['不用逗號','主格不可省','受格可省'],examples:[['The student who asked the question stayed after class.','whoが主語。','who 作主詞。'],['The book that I bought was expensive.','thatが目的語。','that 作受詞。'],['The method we used worked well.','目的格省略。','受格省略。']],contrasts:[['The student asked the question stayed.','The student who asked the question stayed.','主格relativeは必要。','主格關係詞不能省。']],drillJP:'主格3文＋目的格3文＋目的格省略3文。',drillTC:'主格3句＋受格3句＋省略受格3句。'},
 {id:'nondefining',title:'Non-defining relative clauses — 追加情報を挿入する',level:'B1-C1',explainJP:'非制限用法はすでに特定された先行詞へ追加情報を入れます。コンマで区切り、通常thatは使いません。文全体をwhichで受けることもできます。',explainTC:'非限制關係子句對已確定先行詞追加資訊，用逗號隔開，通常不用 that。which 也可承接前面整句。',rulesJP:['comma required','thatは通常不可','which can refer to whole clause'],rulesTC:['需逗號','通常不用 that','which 可指前整句'],examples:[['My laptop, which I bought last year, is already slow.','追加情報。','附加資訊。'],['Dr Lee, who leads the team, will speak first.','人への追加。','補充人物資訊。'],['The test failed, which surprised us.','whichが前文全体を受ける。','which 指前整句。']],contrasts:[['My brother who lives in Osaka...','My brother, who lives in Osaka,...','コンマ有無で「兄弟の中から限定」か「既知の兄への追加」か変わる。','逗號改變限制/補充意義。']],drillJP:'同じ先行詞でdefining/non-definingの意味差が出る3組。',drillTC:'用同一先行詞寫3組限制/非限制對比。'},
 {id:'whose-prep',title:'whose / whom / preposition + relative',level:'B2-C1',explainJP:'whoseは人だけでなく組織・物の所有関係にも使えます。formal writingではto whom, in whichのように前置詞を前へ出せますが、会話ではwho...to / which...inの方が自然なことも多いです。',explainTC:'whose 不只修飾人，也可表示組織/物的所有。正式寫作可用 to whom/in which；口語常把介系詞留在句尾。',rulesJP:['whose + noun','preposition + whom/which','thatの前にprepositionは置かない'],rulesTC:['whose + 名詞','介系詞 + whom/which','介系詞不可放在 that 前'],examples:[['A company whose products I use contacted me.','物の所有関係。','組織所有關係。'],['The person to whom I spoke was helpful.','formal。','正式。'],['The person who I spoke to was helpful.','会話的。','口語。']],contrasts:[['the person to that I spoke','the person to whom I spoke','preposition + that不可。','介系詞 + that 不可。']],drillJP:'whose 3文＋formal/informal preposition relative 3組。',drillTC:'whose 3句＋正式/口語介系詞關係句3組。'},
 {id:'reduced-relative',title:'Reduced relatives — 名詞修飾を圧縮する',level:'B2-C1',explainJP:'who is working → working、which was collected → collectedのように、関係節を分詞やto-infinitiveで縮約できます。意味上の主語が先行詞と一致する必要があります。',explainTC:'who is working → working、which was collected → collected，可用分詞或不定詞縮減關係子句。邏輯主詞需與先行詞一致。',rulesJP:['active/progressive → V-ing','passive → p.p.','the first/next/only + to do も多い'],rulesTC:['主動/進行 → V-ing','被動 → p.p.','first/next/only + to do 常見'],examples:[['Students working here need badges.','who are workingを縮約。','縮減 who are working。'],['The data collected yesterday is incomplete.','which was collectedを縮約。','縮減 which was collected。'],['She was the first person to arrive.','relative infinitive。','不定詞關係修飾。']],contrasts:[['Data collecting yesterday...','Data collected yesterday...','dataはcollectされる側。','data 是被收集，所以用 collected。']],drillJP:'完全関係節5文をreduced formへ変換。',drillTC:'把5個完整關係子句改成縮減形式。'}]
},
{
 id:'noun-clauses',level:'A2-C1',domain:'Complex Clauses',title:'25 · Noun Clauses — 文を名詞として扱う',titleTc:'25 · 名詞子句 — 把整個句子當名詞使用',
 overviewJP:'that節、whether/if節、wh節は主語・目的語・補語として名詞の位置に入ります。embedded questionとの語順、formal subject itとの関係も重要です。',overviewTC:'that 子句、whether/if 子句、wh 子句可作主詞、受詞、補語。需掌握間接問句語序與形式主詞 it。',outcomesJP:['that/wh/whether clauseを使い分ける','名詞節内の語順を正しくする','dummy itで重い主語を後置できる'],outcomesTC:['區分 that/wh/whether 子句','正確使用名詞子句語序','用形式主詞 it 後置重子句'],
 units:[
 {id:'that-clauses',title:'that-clause — think / know / fact / idea',level:'A2-B2',explainJP:'that節は「〜ということ」という命題内容を表します。動詞だけでなく、fact/idea/possibilityやbe + adjectiveの後ろにも現れます。',explainTC:'that 子句表示一個命題內容「…這件事」，可接在動詞、fact/idea/possibility、形容詞後。',rulesJP:['think/believe/say + (that)','the fact that...','It is clear that...'],rulesTC:['動詞 + that','名詞 + that','It is adjective that...'],examples:[['I think that the result is correct.','動詞補語。','動詞補語。'],['The fact that it failed matters.','名詞同格。','名詞同位內容。'],['It is clear that we need more data.','formal subject it。','形式主詞 it。']],contrasts:[['The fact which it failed...','The fact that it failed...','factの内容はthat-clause。','fact 的內容用 that 子句。']],drillJP:'verb/noun/adjectiveの3入口でthat-clauseを各3文。',drillTC:'動詞/名詞/形容詞三種入口各造3句。'},
 {id:'wh-noun',title:'wh-clause — what / why / how / where as a noun',level:'A2-B2',explainJP:'wh節は疑問の内容を名詞として埋め込みます。内部は平叙文語順です。whatは先行詞を含むfree relativeとして「〜するもの/こと」の意味にもなります。',explainTC:'wh 子句把疑問內容當名詞嵌入，內部用陳述語序。what 也可作自由關係詞，表示「…的東西/事情」。',rulesJP:['I know what he said.','why/how/where + S + V','what = the thing(s) that の用法'],rulesTC:['wh + S + V','內部陳述語序','what 可等於 the thing that'],examples:[['I know why it failed.','why節が目的語。','why 子句作受詞。'],['What you said makes sense.','what節が主語。','what 子句作主詞。'],['This is how the system works.','補語。','補語。']],contrasts:[['I know what did he say.','I know what he said.','名詞節内は平叙文語順。','名詞子句內用陳述語序。']],drillJP:'wh節を主語・目的語・補語に各3文。',drillTC:'wh 子句作主詞/受詞/補語各3句。'},
 {id:'whether-if',title:'whether / if — yes/no内容を名詞節にする',level:'B1-C1',explainJP:'whether/ifはyes/no内容を埋め込みますが、前置詞の後、to-infinitiveの前、or notを強く対比する場面ではwhetherが好まれます。',explainTC:'whether/if 都可嵌入 yes/no 內容，但介系詞後、to-infinitive 前、明確 or not 對比時通常用 whether。',rulesJP:['I do not know if/whether...','whether to do','depends on whether...'],rulesTC:['if/whether 皆可','whether to do','介系詞後用 whether'],examples:[['I do not know whether it will work.','中立。','中立。'],['We must decide whether to continue.','whether + to。','whether + to。'],['It depends on whether we have enough time.','preposition後。','介系詞後。']],contrasts:[['It depends on if we have time.','It depends on whether we have time.','formal standardではpreposition後whetherが安全。','正式標準用法介系詞後 whether 更安全。']],drillJP:'if/whether両方可3文＋whetherのみが自然な3文。',drillTC:'3句兩者皆可＋3句偏 whether。'}]
},
{
 id:'adverbial-clauses',level:'A2-C2',domain:'Complex Clauses',title:'26 · Adverbial Clauses & Linkers — 時間・理由・対比・目的・結果をつなぐ',titleTc:'26 · 副詞子句與連接詞 — 連接時間、原因、對比、目的、結果',
 overviewJP:'because/although/if/whenだけでなく、whereas, while, since, as, so that, in case, provided that, even thoughなどの意味差と句読法を扱います。',overviewTC:'除了 because/although/if/when，也學 whereas、while、since、as、so that、in case、provided that、even though 的差異與標點。',outcomesJP:['意味関係に合うlinkerを選ぶ','because/because of等clause/phraseを区別する','although/despiteの構造を区別する'],outcomesTC:['依邏輯選 linker','區分 because/because of 的子句/片語','區分 although/despite 結構'],
 units:[
 {id:'reason-cause',title:'because / since / as / because of / due to',level:'A2-B2',explainJP:'becauseは明確な理由を示し、since/asは既知・背景的理由として使われることがあります。because of/due toの後ろは名詞句です。',explainTC:'because 明確給原因；since/as 有時把原因當背景。because of/due to 後接名詞片語。',rulesJP:['because + clause','because of + noun/-ing','due to + noun phrase（formal）'],rulesTC:['because + 子句','because of + 名詞','due to + 名詞片語'],examples:[['The test failed because the cable was loose.','clause。','子句。'],['The test failed because of a loose cable.','noun phrase。','名詞片語。'],['The delay was due to bad weather.','formal nominal relation。','正式名詞關係。']],contrasts:[['because of the cable was loose','because the cable was loose / because of the loose cable','clauseかnoun phraseかを揃える。','需區分子句與名詞片語。']],drillJP:'同じ理由をbecause/because of/due toで3通り書く。',drillTC:'同一原因用三種形式改寫。'},
 {id:'contrast-concession',title:'although / even though / while / whereas / despite',level:'B1-C1',explainJP:'although/even thoughは譲歩、while/whereasは対照、despite/in spite ofは名詞句を取ります。butとalthoughを同じ節接続で二重に使わないのが標準です。',explainTC:'although/even though 表讓步；while/whereas 表對照；despite/in spite of 接名詞片語。標準英文不把 although 與 but 重複連接同一關係。',rulesJP:['although + clause','despite + noun/-ing','whereas = direct contrast'],rulesTC:['although + 子句','despite + 名詞/-ing','whereas 直接對比'],examples:[['Although it was late, we continued.','譲歩。','讓步。'],['Despite the delay, we finished on time.','noun phrase。','名詞片語。'],['The old model is cheaper, whereas the new one is faster.','対照。','對照。']],contrasts:[['Although it was late, but we continued.','Although it was late, we continued.','althoughとbutを重ねない。','不重複 although + but。']],drillJP:'although/despite/whereasで同じ2事実を3種類につなぐ。',drillTC:'用三種連接方式連接同兩事實。'},
 {id:'purpose-result',title:'so that / in order that / so...that / such...that',level:'B1-C1',explainJP:'purposeのso thatとresultのso...thatは形が似ていますが異なります。such + noun phrase + thatも結果を表します。',explainTC:'表示目的的 so that 與表示結果的 so...that 不同；such + 名詞片語 + that 也表結果。',rulesJP:['so that + clause = purpose','so + adjective/adverb + that = result','such + (a/an) + adj + noun + that'],rulesTC:['so that 子句表目的','so + 形容詞/副詞 + that 表結果','such + 名詞片語 + that'],examples:[['I wrote it down so that I would not forget.','目的。','目的。'],['The box was so heavy that I could not lift it.','結果。','結果。'],['It was such a useful tool that everyone wanted one.','noun-based result。','名詞型結果。']],contrasts:[['It was so useful tool that...','It was such a useful tool that...','名詞を中心にするならsuch。','以名詞為中心用 such。']],drillJP:'purpose 3文＋so...that 3文＋such...that 3文。',drillTC:'目的/so結果/such結果各3句。'},
 {id:'condition-linkers',title:'unless / in case / provided that / as long as',level:'B1-C1',explainJP:'条件はifだけではありません。unlessはif notに近いが常に完全同義ではなく、in caseは「〜の場合に備えて」、provided/as long asは条件制限を明確にします。',explainTC:'條件不只有 if。unless 接近 if not；in case 表「以防」；provided/as long as 明確限制條件。',rulesJP:['unless = except if','in case = precaution, not simple condition','provided/providing that = only if'],rulesTC:['unless = 除非','in case = 預防','provided that = 前提是'],examples:[['We will go unless it rains.','雨でない限り。','除非下雨。'],['Take an umbrella in case it rains.','雨に備えて。','以防下雨。'],['You can use it provided that you cite the source.','条件付き許可。','有條件許可。']],contrasts:[['I will call you in case I arrive.','I will call you if/when I arrive.','単純条件にin caseは不自然。','一般條件不用 in case。']],drillJP:'if/unless/in case/provided thatを各2文。',drillTC:'四種條件連接詞各造2句。'}]
},
{
 id:'conditionals',level:'A2-C2',domain:'Complex Clauses',title:'27 · Conditionals — 0/1/2/3型を「現実性×時間」で理解する',titleTc:'27 · 條件句 — 用「現實性×時間」理解，不死背0/1/2/3',
 overviewJP:'条件文は番号暗記ではなく、話し手が条件をどれほど現実的に見ているか、どの時間について話すかで理解します。mixed conditionalsやinversionまで扱います。',overviewTC:'條件句不要只背0/1/2/3，而要看條件的現實性與時間。也學 mixed conditionals 與倒裝。',outcomesJP:['real/unrealを区別する','second/thirdの時制を説明する','mixed conditionalを作る','if省略倒装を読める'],outcomesTC:['區分現實/非現實','解釋第二/第三條件句','製作混合條件句','理解省略 if 的倒裝'],
 units:[
 {id:'zero-first',title:'Zero & first — 一般事実と現実的未来',level:'A2-B1',explainJP:'zeroは条件が成立すれば一般に結果が成立する関係、firstは未来の現実的可能性を述べます。if節の未来意味でも通常現在形です。',explainTC:'zero 表一般規律；first 表現實可能的未來。即使 if 從句指未來，通常仍用現在式。',rulesJP:['If + present, present','If + present, will/can/may + base','if節に通常willを置かない'],rulesTC:['零條件：現在+現在','第一條件：現在 + will/can/may','if 從句通常不用 will'],examples:[['If you heat ice, it melts.','一般関係。','一般規律。'],['If I have time, I will call you.','現実的未来。','現實未來。'],['If the test passes, we can deploy it.','可能な結果。','可能結果。']],contrasts:[['If I will have time, I will call.','If I have time, I will call.','通常if節は現在形。','if 從句通常現在式。']],drillJP:'zero 3文＋first 5文。',drillTC:'零條件3句＋第一條件5句。'},
 {id:'second',title:'Second conditional — 現在/未来から距離を置く',level:'B1',explainJP:'If + past, would + baseは過去時間ではなく、現在/未来の非現実・低可能性・仮定的距離を表します。beではformal standardでIf I wereが有名です。',explainTC:'If + past, would + 原形 的 past 不表示過去時間，而表示現在/未來的非現實或心理距離。正式標準常用 If I were。',rulesJP:['if + past → hypothetical distance','would/could/might + base','If I were you...'],rulesTC:['過去形表示距離','would/could/might + 原形','If I were you'],examples:[['If I had more time, I would study abroad.','今の仮定。','現在假設。'],['If I were you, I would wait.','助言。','建議。'],['What would you do if you lost your phone?','仮想。','假想。']],contrasts:[['If I would have more time...','If I had more time...','if節にwouldを置かないのが基本。','一般 if 從句不用 would。']],drillJP:'現実と逆の現在仮定を5文＋low probability未来を3文。',drillTC:'現在反事實5句＋低可能未來3句。'},
 {id:'third',title:'Third conditional — 過去の反実と結果',level:'B1-C1',explainJP:'If + had p.p., would have p.p. は過去に実際とは違う条件を想像し、その仮想結果を述べます。後悔・原因分析に頻出します。',explainTC:'If + had p.p., would have p.p. 想像與實際不同的過去條件及其結果，常用於後悔與原因分析。',rulesJP:['if + past perfect','would/could/might have p.p.','actual eventは反対だった含意'],rulesTC:['if + 過去完成','would/could/might have p.p.','暗示實際情況相反'],examples:[['If I had known, I would have helped.','実際は知らなかった。','實際不知道。'],['If we had tested earlier, we might have found the bug.','反実分析。','反事實分析。'],['She could have passed if she had studied more.','可能な別結果。','可能的另一結果。']],contrasts:[['If I knew, I would have helped.','If I had known, I would have helped.','過去反実条件にはpast perfect。','過去反事實條件用 past perfect。']],drillJP:'最近の出来事をthird conditionalで5つ振り返る。',drillTC:'用第三條件句反思5件近期事件。'},
 {id:'mixed-inverted',title:'Mixed conditionals & inversion — 時間をまたぐ因果',level:'C1-C2',explainJP:'過去の条件が現在結果へ影響する、または現在の性質が過去結果へ影響した、という時間をまたぐ条件がmixed conditionalです。formalではHad I known... / Were I... / Should you...のようなif省略倒装もあります。',explainTC:'mixed conditional 表示過去條件影響現在結果，或現在狀態影響過去結果。正式英文可用 Had I known / Were I / Should you 等省略 if 倒裝。',rulesJP:['past condition → present result','present condition → past result','Had/Were/Should inversion'],rulesTC:['過去條件→現在結果','現在條件→過去結果','Had/Were/Should 倒裝'],examples:[['If I had accepted that job, I would live in Osaka now.','過去→現在。','過去→現在。'],['If I were more organized, I would not have missed the deadline.','現在性質→過去結果。','現在特質→過去結果。'],['Had I known, I would have acted differently.','If I had knownの倒装。','省略 if 倒裝。']],contrasts:[['Had I knew...','Had I known...','Had inversionの後はp.p.。','Had 倒裝後用過去分詞。']],drillJP:'mixed conditional 4文＋inverted conditional 3文。',drillTC:'混合條件4句＋倒裝條件3句。'}]
},
{
 id:'subjunctive-wish',level:'B1-C2',domain:'Complex Clauses',title:'28 · Subjunctive & Wish — 現実から距離を置く文法',titleTc:'28 · 假設語氣與 Wish — 表達與現實的距離',
 overviewJP:'wish/if only、as if、It is essential that..., suggest that...など、英語には「事実を直接述べない」ための複数のsubjunctive patternがあります。',overviewTC:'wish/if only、as if、It is essential that...、suggest that... 等都用來表達非直接事實或要求的假設語氣。',outcomesJP:['wishの時間別形を使える','mandative subjunctiveを使える','as if/as thoughの距離を理解する'],outcomesTC:['依時間使用 wish','使用命令型虛擬語氣','理解 as if/as though 的距離'],
 units:[
 {id:'wish-present',title:'wish + past — 今の事実への不満・願望',level:'B1',explainJP:'wish + pastは現在の現実と違う願望を表します。beはwereを使うformal patternがあります。couldは能力・可能性の不足、wouldは他者の行動変化への願望に使われます。',explainTC:'wish + past 表示與現在事實相反的願望。正式用法可用 were；could 表能力不足，would 常希望他人行為改變。',rulesJP:['wish + past simple','wish + could','wish + would（自分自身の単純能力には不自然な場合）'],rulesTC:['wish + 過去式','wish + could','wish + would 常針對行為改變'],examples:[['I wish I had more time.','実際は時間が少ない。','實際時間不足。'],['I wish I could speak more fluently.','能力願望。','能力願望。'],['I wish he would stop shouting.','他者行動への不満。','希望他人改變行為。']],contrasts:[['I wish I will have more time.','I hope I will have more time. / I wish I had more time.','現実的未来希望はhope、反実現在はwish+past。','現實未來用 hope，反事實現在用 wish+past。']],drillJP:'wish + past/could/wouldを各3文。',drillTC:'三種 wish 各造3句。'},
 {id:'wish-past',title:'wish + past perfect — 過去への後悔',level:'B1-C1',explainJP:'wish + had p.p. はすでに変えられない過去について「違っていればよかった」と後悔します。should haveと近い場面もありますが構造と焦点が違います。',explainTC:'wish + had p.p. 表示對無法改變的過去後悔。與 should have 有相近情境，但結構與焦點不同。',rulesJP:['wish + past perfect','if only + past perfect はより強い感情','actual pastは反対'],rulesTC:['wish + 過去完成','if only 更強烈','實際過去相反'],examples:[['I wish I had studied harder.','実際は十分勉強しなかった。','實際沒努力讀。'],['If only we had checked the cable.','強い後悔。','強烈後悔。'],['She wishes she had accepted the offer.','過去選択への後悔。','後悔過去選擇。']],contrasts:[['I wish I studied harder yesterday.','I wish I had studied harder yesterday.','過去反実はpast perfect。','過去反事實用過去完成。']],drillJP:'過去の後悔をwish/if onlyで5文。',drillTC:'用 wish/if only 寫5句過去後悔。'},
 {id:'mandative',title:'Mandative subjunctive — suggest / recommend / essential that + base',level:'B2-C2',explainJP:'formal American Englishを中心に、suggest/recommend/insistやessential/importantのthat節で動詞原形を使うmandative subjunctiveがあります。British Englishではshould + baseも一般的です。',explainTC:'正式英文尤其美式英文中，suggest/recommend/insist 或 essential/important 的 that 子句可用原形虛擬語氣；英式也常用 should + 原形。',rulesJP:['suggest that he go','It is essential that every member be present','BrE: should go も自然'],rulesTC:['that 子句用原形','be 仍用 be','英式可 should + 原形'],examples:[['I suggest that he wait.','waitsではなくbase。','用 wait 原形。'],['It is essential that the system be tested.','be。','be 原形。'],['They recommended that we should leave early.','BrE pattern。','英式形式。']],contrasts:[['I suggest him to wait.','I suggest that he wait. / I suggest waiting.','suggestの補語pattern。','suggest 句型。']],drillJP:'suggest/recommend/insist/essential/importantを使いthat-clause5文。',drillTC:'五個詞各造 mandative that 句。'},
 {id:'as-if',title:'as if / as though — 現実らしさと距離',level:'B2-C1',explainJP:'as if/as thoughの後ろは、話し手が内容を現実的と見るなら通常時制、非現実・距離を置くならpast/past perfectを使えます。',explainTC:'as if/as though 後，若內容可能真實可用一般時態；若非現實或保持距離，可用過去式/過去完成。',rulesJP:['looks as if it is going to rain','acts as if he knew everything','looked as if he had seen a ghost'],rulesTC:['現實可能用一般時態','非現實用 past','過去更早用 past perfect'],examples:[['It looks as if it is going to rain.','現実的兆候。','真實可能。'],['He talks as if he knew everything.','実際はそうでない含意。','暗示其實不知道。'],['She looked as though she had not slept.','過去のさらに前。','過去更早狀態。']],contrasts:[['He acts as if he knows everything.','He acts as if he knew everything.','前者は可能性を残し、後者は距離/非現実感が強い。','後者距離感更強。']],drillJP:'realistic/unreal as ifを3組。',drillTC:'寫3組真實可能/非現實 as if 對比。'}]
},
{
 id:'reported-speech',level:'B1-C2',domain:'Complex Clauses',title:'29 · Reported Speech — backshiftだけでは不十分',titleTc:'29 · 間接引語 — 不只是時態後移',
 overviewJP:'reported speechは時制変化だけでなく、視点・代名詞・時間場所表現・questions/commands・backshiftしない条件まで含む体系です。',overviewTC:'間接引語不只時態後移，也包含視角、代名詞、時間地點表達、問句/命令，以及不後移的情況。',outcomesJP:['backshiftを意味に応じて使う','pronoun/time/place shiftを判断する','reported questions/commandsを作れる'],outcomesTC:['依意思使用時態後移','判斷代名詞/時間/地點轉換','轉述問句/命令'],
 units:[
 {id:'statements-backshift',title:'Statements & backshift — said (that)...',level:'B1-B2',explainJP:'reporting verbが過去の場合、現在→過去、past→past perfect、will→wouldなどのbackshiftがよく起きます。ただし発言内容が今も真実・関連している場合、backshiftしないこともあります。',explainTC:'reporting verb 在過去時常發生時態後移：現在→過去、過去→過去完成、will→would。但內容現在仍為真時可不後移。',rulesJP:['said: “I am tired.” → said he was tired','will → would / can → could','universal/current truth may stay present'],rulesTC:['現在→過去','will→would / can→could','仍為真的內容可保留現在'],examples:[['She said she was tired.','典型backshift。','典型後移。'],['He said he would call later.','will→would。','will→would。'],['The teacher said water boils at 100°C.','一般事実は現在形維持可。','一般事實可保留現在式。']],contrasts:[['He said he is tired.','He said he was tired.','通常の過去報告ならwasが中立。今も疲れていると強調するならisも文脈上可能。','一般過去報告用 was；若強調現在仍累可用 is。']],drillJP:'direct statements 8文をreportし、backshift必要/不要の理由を書く。',drillTC:'把8個直接陳述改成間接引語並說明是否後移。'},
 {id:'deictic-shift',title:'Pronouns / this-that / now-then / today-that day',level:'B1-B2',explainJP:'reported speechでは発話時点・場所・話者が変わるため、代名詞や指示表現も必要に応じて変わります。機械的に必ず変えるのではなく、現在のreporting contextに合わせます。',explainTC:'轉述時說話者、時間、地點可能改變，因此代名詞與指示詞需依目前語境調整，不是機械全部改。',rulesJP:['this↔that, here↔there はcontext依存','today→that day, tomorrow→next/following day','I/youはreporter/listenerに応じ変更'],rulesTC:['this/that、here/there 依語境','today→that day 等','I/you 依轉述者改變'],examples:[['“I will do it tomorrow,” she said. → She said she would do it the next day.','時間視点変更。','時間視角改變。'],['“We like it here.” → They said they liked it there.','場所変更時。','地點改變時。'],['“This is my house.” → He said this was his house.','同じ場所ならthis維持も可能。','同地點可保留 this。']],contrasts:[['All reporting words must always change.','Change them only when the reporting context changes.','機械変換ではない。','不是機械轉換。']],drillJP:'同じdirect speechを「同じ日/翌日」「同じ場所/別場所」の2contextでreport。',drillTC:'同一句直接引語分同日/隔日、同地/異地兩情境轉述。'},
 {id:'reported-questions',title:'Reported questions — ask + statement word order',level:'B1-B2',explainJP:'reported questionではquestion markやinversionを使わず、WH + S + V / if-whether + S + Vの平叙文語順にします。',explainTC:'間接問句不用問號式倒裝，使用 WH + S + V 或 if/whether + S + V 的陳述語序。',rulesJP:['asked where he was','asked if/whether...','do/does/didは内部で消える'],rulesTC:['WH + S + V','if/whether + S + V','內部 do-support 消失'],examples:[['“Where are you?” → She asked where I was.','WH report。','WH 轉述。'],['“Did you finish?” → He asked whether I had finished.','yes/no report。','yes/no 轉述。'],['“Why did it fail?” → They asked why it had failed.','do消失。','do 消失。']],contrasts:[['She asked where was I.','She asked where I was.','reported questionはstatement order。','間接問句用陳述語序。']],drillJP:'WH direct questions 5＋yes/no 5をreported formへ。',drillTC:'5個WH＋5個yes/no直接問句改轉述。'},
 {id:'commands-requests',title:'Reported commands / requests — tell/ask + O + to',level:'B1-C1',explainJP:'命令・依頼は通常tell/ask/order/warn + object + to-infinitiveで報告します。否定命令はnot to doです。',explainTC:'命令與請求通常用 tell/ask/order/warn + 受詞 + to-infinitive 轉述；否定用 not to do。',rulesJP:['tell O to do','ask O to do','warn O not to do'],rulesTC:['tell O to do','ask O to do','否定 not to do'],examples:[['“Sit down.” → He told me to sit down.','command。','命令。'],['“Please wait.” → She asked us to wait.','request。','請求。'],['“Do not touch it.” → He warned me not to touch it.','negative command。','否定命令。']],contrasts:[['He said me to wait.','He told me to wait.','sayはobject+to patternを取らない。','say 不用 object+to。']],drillJP:'command/request/warningを各3個direct→reported。',drillTC:'命令/請求/警告各3個直接→間接。'}]
},
{
 id:'reporting-verbs',level:'B2-C2',domain:'Complex Clauses',title:'30 · Reporting Verbs — say/tellからacademic reportingまで',titleTc:'30 · 報導動詞 — 從 say/tell 到學術報導',
 overviewJP:'reporting verbは後ろの文型と話者態度を同時に決めます。admit, deny, suggest, recommend, warn, accuse, claim, argue, acknowledgeなどをpattern別に学びます。',overviewTC:'reporting verb 同時決定後面的句型與說話者態度。學 admit、deny、suggest、recommend、warn、accuse、claim、argue、acknowledge 等。',outcomesJP:['say/tellの構文差を自動化する','reporting verbを補語pattern別に分類する','academic stanceを調整できる'],outcomesTC:['自動化 say/tell 差異','依補語句型分類 reporting verb','調整學術語氣'],
 units:[
 {id:'say-tell',title:'say vs tell — 最頻出の構文差',level:'A2-B1',explainJP:'sayは通常内容を直接取り、人を明示するならsay something to someone。tellは人を直接目的語に取りtell someone something / tell someone to doです。',explainTC:'say 通常直接接內容；若加人用 say something to someone。tell 直接接人：tell someone something / tell someone to do。',rulesJP:['say + content','say something to someone','tell + person + content/to do'],rulesTC:['say + 內容','say X to 人','tell + 人 + 內容/to do'],examples:[['She said that she was tired.','say + clause。','say + 子句。'],['She told me that she was tired.','tell + person。','tell + 人。'],['He told me to wait.','tell O to。','tell O to。']],contrasts:[['She said me that...','She told me that... / She said to me that...','sayは人を直接目的語にしない。','say 不直接接人。']],drillJP:'say/tellを使う10文の穴埋めを自作し翌日解く。',drillTC:'自製10題 say/tell 填空隔天再做。'},
 {id:'verb-patterns-report',title:'admit / deny / promise / warn / accuse — patternごとに覚える',level:'B2-C1',explainJP:'reporting verbsはそれぞれ-ing, to-infinitive, that-clause, object + prepositionなど異なるpatternを取ります。意味と構文をセットで覚える必要があります。',explainTC:'reporting verbs 各自接 -ing、to-infinitive、that-clause、object+preposition 等不同句型，必須語意與句型一起記。',rulesJP:['admit/deny + -ing / that','promise + to / that','warn + O + not to / about','accuse + O + of -ing'],rulesTC:['admit/deny + -ing/that','promise + to/that','warn O not to/about','accuse O of -ing'],examples:[['He admitted making a mistake.','admit + ing。','admit + ing。'],['She promised to call.','promise + to。','promise + to。'],['They accused him of copying the data.','accuse O of ing。','accuse O of ing。']],contrasts:[['They accused him to copy.','They accused him of copying.','accuse pattern。','accuse 句型。']],drillJP:'admit/deny/promise/warn/accuse/remind/adviseをpattern表にする。',drillTC:'整理七個 reporting verb 句型表。'},
 {id:'suggest-recommend',title:'suggest / recommend / insist — 複数の正しいpattern',level:'B2-C1',explainJP:'suggest/recommendは-ingまたはthat節、insistはthat節/on -ingなどを取ります。特にsuggest someone to doは学習者に多い誤りです。',explainTC:'suggest/recommend 可接 -ing 或 that 子句；insist 可接 that 或 on -ing。suggest someone to do 是常見錯誤。',rulesJP:['suggest doing','suggest that S (should) do','recommend doing / recommend that','insist that / insist on'],rulesTC:['suggest doing','suggest that','recommend doing/that','insist that/on'],examples:[['I suggest waiting a little longer.','-ing。','-ing。'],['I suggest that we wait.','that。','that。'],['She insisted on paying.','on -ing。','on -ing。']],contrasts:[['I suggest you to wait.','I suggest that you wait.','standard patternではobject+toを避ける。','標準句型不用 object+to。']],drillJP:'suggest/recommend/insistを各2patternで例文化。',drillTC:'三個動詞各用兩種句型造句。'},
 {id:'academic-reporting',title:'claim / argue / suggest / indicate / acknowledge — stanceを表す',level:'C1-C2',explainJP:'academic writingではreporting verbが「その情報をどれほど支持するか」を示します。show/proveは強く、suggest/indicateは控えめ、claimは距離を置くことがあります。',explainTC:'學術寫作中 reporting verb 顯示作者對資訊的支持程度。show/prove 較強，suggest/indicate 較保守，claim 有時表示距離。',rulesJP:['X argues that... = 論証として提示','X suggests/indicates that... = 控えめ','X acknowledges that... = 認める'],rulesTC:['argue 表論證','suggest/indicate 保守','acknowledge 表承認'],examples:[['The authors argue that the method is scalable.','主張を論証として紹介。','介紹論證主張。'],['The results suggest that the change improved accuracy.','断定を避ける。','避免過度斷定。'],['The paper acknowledges several limitations.','限界を認める。','承認限制。']],contrasts:[['The results prove that...（証拠が限定的）','The results suggest that...','証拠強度に合わせてverbを選ぶ。','依證據強度選動詞。']],drillJP:'同じ研究結果をclaim/argue/suggest/indicate/showで書き換え、確信度の差を説明。',drillTC:'同一研究結果用五個 reporting verb 改寫並比較立場。'}]
}
);